# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IDADistrictsDataCenter
                                 A QGIS plugin
 IDA Districts Data Center
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-12-15
        git sha              : $Format:%H$
        copyright            : (C) 2021 by EQUA
        email                : peter.nageler@equa.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from plugins.utility_functions.dialog import *
from plugins.utility_functions.db import *
from plugins.utility_functions.utility import *
from plugins.utility_functions.topology import *
from plugins.utility_functions.layer_visualization import *
from plugins.utility_functions.workers import WorkerOpenAPI
from plugins.utility_functions.sensor_signals import AssettypeSensorSignals

from PyQt5.QtCore import Qt
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication,QThreadPool
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QComboBox,QAction, QFileDialog,QTableWidgetItem,QFileDialog

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ida_districts_data_center_dialog import IDADistrictsDataCenterDialog, IDA_Districts_NameDialog, DefaultsDialog, ConnectionsDialog
from .update_boundaries import *
from plugins.utility_functions.assettypeFiles import ExchangeConntypeFiles, WriteAssettypeFiles, RenameAssettypeFiles
from plugins.ida_districts_modeling_simulation.invoke import CopyAssettypeFiles

from plugins.utility_functions.util import *
import os.path
import psycopg2
import psycopg2.extras
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
import subprocess
import os
from qgis.core import QgsCredentials,QgsEditorWidgetSetup, QgsVectorLayer, QgsDataSourceUri, QgsSymbol, QgsRendererCategory, QgsStyle, QgsCategorizedSymbolRenderer, QgsGraduatedSymbolRenderer, QgsRendererRange, QgsMarkerSymbol, QgsClassificationRange, QgsApplication
from qgis.core import QgsProject,Qgis
from qgis.utils import iface
from PyQt5.QtGui import * 
from qgis.PyQt import QtGui 
import math
import numpy as np  
import shutil
from multiprocessing import Process
from qgis.PyQt.QtGui import QKeySequence
from qgis.PyQt.QtWidgets import QShortcut
from PyQt5.QtCore import Qt 
import copy
        
class IDADistrictsDataCenter:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'IDADistrictsDataCenter_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&IDA Districts Data Center')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        
        self.dictDB=""
        self.conn=""
        self.cur=""

        shortcut = QShortcut(QKeySequence('Alt+Shift+D'), iface.mainWindow())
        shortcut.setContext(Qt.ApplicationShortcut)
        shortcut.activated.connect(self.openPlugin)

    def openPlugin(self):
        self.run()
       
    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('IDADistrictsDataCenter', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/ida_districts_data_center/icon-data-center.png'
        self.add_action(
            icon_path,
            text=self.tr(u'IDA Districts Data Center'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IDA Districts Data Center'),
                action)
            self.iface.removeToolBarIcon(action)
      
    #duplicated code  
    def closeDialog(self,dlg,table,openFnArg):
        """ Closes dialog"""
        self.delIfNotInDBIds(table,openFnArg)
        print('close dialog: {}'.format(dlg))
        dlg.close()        

    def getValuesFromTableRow(self,dlg,dropdowns,row,columns,checkBoxes):
        values=[]
        p=False
        mdot=False
        #print(row)
        for col in range(dlg.tableWidget.columnCount()):
            if col in list([i[0] for i in dropdowns]):
                value=dlg.tableWidget.cellWidget(row, col).currentText()
            elif col in checkBoxes:
                value=dlg.tableWidget.cellWidget(row, col).isChecked()
            else:
                if dlg.tableWidget.item(row,col):
                    value=dlg.tableWidget.item(row,col).text()
                    #print(value)
                    if value and columns[col]=='p':
                        p=True
                    if value and columns[col]=='mdot':
                        mdot=True
                    if not value and (columns[col]=='p' or columns[col]=='mdot'):
                        value='Null'
                else:
                    if columns[col]=='p' or columns[col]=='mdot':
                        value='Null'
                    else:
                        value=''
            if isinstance(value, str) and ':' in value and value.split(':')[0].isnumeric():
                value=value.split(':')[0]
            if not value:
                return False
            if not isFloat(value) and value!='Null':
                value="'"+value + "'" 
            values.append(value)
        #print(values)
        if mdot and p:
            self.iface.messageBar().pushMessage("Error", "It is not possible to set tghe pressure and mass flow as boundary!", level=Qgis.Critical)
            return False
        return ','.join(str(i) for i in values)
        
    def saveContent(self,dlg,id,table,columns,filter,dropdowns,trace):
        """" Save table to DB an close dialog"""
        print('Save table to DB an close dialog')
        table_name="_".join(table.split('_')[0:-1])
        if trace in ['conn_type_trace','bt_conns_trace']:
            oldConnValues_dict={}
            ats=getAssetTypesByConnType(self.cur,self.dictDB,id) if trace=='conn_type_trace' else getAssetTypesByConnBundleType(self.cur,self.dictDB,id)
            for at in ats:
                if at['type']!='device':
                    oldConnValues_dict[at['at_name']]=getConnsValues(at['conn_bundle_type_id'],self.cur)
        
        sql="""DELETE FROM public.{} {} {};\n""".format(table,filter,id)
        print(sql)
        maxId=getMaxId(self.cur,table)
        counter=1
        for row in range(dlg.tableWidget.rowCount()):
            values=self.getValuesFromTableRow(dlg,dropdowns,row,columns,[])
            if not values:
                self.iface.messageBar().pushMessage("Error", "Invalid input!", level=Qgis.Critical)
                return False
            sql+="""INSERT INTO public.{} (id,{},{}) VALUES({},{},{});\n""".format(table,filter[5:-1],','.join(i for i in columns),maxId+counter,id,values)
            counter+=1
        print(sql)
        try:
            self.cur.execute(sql)
        except Exception as e:
            self.iface.messageBar().pushMessage("Error", str(e), level=Qgis.Critical)
            return False
        
        if trace in ['conn_type_trace','bt_conns_trace']:
            print(dlg.traceTableValues)
            if [True for traceValue in dlg.traceTableValues if 
                dlg.traceTableValues[traceValue][1] and dlg.traceTableValues[traceValue][3] and (dlg.traceTableValues[traceValue][0]!=dlg.traceTableValues[traceValue][1] or dlg.traceTableValues[traceValue][2]!=dlg.traceTableValues[traceValue][3]) or
                dlg.traceTableValues[traceValue][1] and not dlg.traceTableValues[traceValue][0] or 
                dlg.traceTableValues[traceValue][3] and not dlg.traceTableValues[traceValue][2]]:
                print('ExchangeConntypeFiles')
                #get changed conn bundle types --> get changed assettypes
                ats=getAssetTypesByConnType(self.cur,self.dictDB,id) if trace=='conn_type_trace' else getAssetTypesByConnBundleType(self.cur,self.dictDB,id)
                for at in ats:
                    if at['type']!='device':
                        print(at)
                for at in ats:
                    if at['type']!='device':
                        print('*****************************************************************************')
                        print(at['at_name'])
                        print(oldConnValues_dict[at['at_name']])
                        ExchangeConntypeFiles(self.plugin_dir,at['at_name'],at['type'],at['conn_bundle_type_id'],at['conn_bundle_type_id'],self.cur,oldConnValues=oldConnValues_dict[at['at_name']])
            
        elif trace:
            print(dlg.traceTableValues)
            for traceValue in dlg.traceTableValues:
                wroteAssettype=False
                if dlg.traceTableValues[traceValue][1]:
                    if dlg.traceTableValues[traceValue][0]!=dlg.traceTableValues[traceValue][1]:
                        print(dlg.traceTableValues[traceValue])
                        if not dlg.traceTableValues[traceValue][0]:
                            if dlg.traceTableValues[traceValue][3]:
                                WriteAssettypeFiles(self.plugin_dir,dlg.traceTableValues[traceValue][1],table_name,self.cur,dlg.traceTableValues[traceValue][3])
                            else:
                                self.iface.messageBar().pushMessage("Error", "No assettype is set in: "+str(dlg.traceTableValues[traceValue]), level=Qgis.Critical)
                                return False
                            wroteAssettype=True
                        else:
                            RenameAssettypeFiles(self.plugin_dir,dlg.traceTableValues[traceValue][0],table_name,dlg.traceTableValues[traceValue][1],self.cur)
                if dlg.traceTableValues[traceValue][3] and dlg.traceTableValues[traceValue][2] and not wroteAssettype:
                    if dlg.traceTableValues[traceValue][2]!=dlg.traceTableValues[traceValue][3]:
                        print('Changed conn bundle type')
                        print(dlg.traceTableValues[traceValue])
                        if dlg.traceTableValues[traceValue][1]:
                            name=dlg.traceTableValues[traceValue][1]
                        else:
                            name=dlg.traceTableValues[traceValue][0]
                        ExchangeConntypeFiles(self.plugin_dir,name,table_name,dlg.traceTableValues[traceValue][3],dlg.traceTableValues[traceValue][2],self.cur)
                        
            
            #delete templates in directory if they are not in dlg.traceTableValues[traceValue][0]
            dir=self.plugin_dir+'\\'+self.dictDB['projectName']+"\\{}_assettypes".format(table_name)
            files = []
            for file in os.listdir(dir):
                # check only .idm files
                if file.split('.')[0] not in files:
                    files.append(file.split('.')[0])
            print (files)
            traceTableFiles=[]
            for traceValue in dlg.traceTableValues: 
                if dlg.traceTableValues[traceValue][1]:
                    traceTableFiles.append(dlg.traceTableValues[traceValue][1])
                else:
                    traceTableFiles.append(dlg.traceTableValues[traceValue][0])
            print(traceTableFiles)
            sql="""SELECT assetgroup::text || '_' || assettype::text || '_' || assettype_name AS assettype_name FROM {}_assettypes WHERE assetgroup !={};""".format(table_name,id)
            self.cur.execute(sql)
            list_assettype_names=[i['assettype_name'] for i in self.cur.fetchall()]
            for file in files:
                if file not in traceTableFiles and file not in list_assettype_names:
                    print(file)
                    if os.path.exists(dir+'\\'+file+'.idm'):
                        os.remove(dir+'\\'+file+'.idm')
                    if os.path.exists(dir+'\\'+file+'.idc'):
                        os.remove(dir+'\\'+file+'.idc')
                    if os.path.exists(dir+'\\'+file):
                        shutil.rmtree(dir+'\\'+file)
                    
        dlg.close()
    
    def showAssettypes(self,type):
        """show asset types"""
        self.dlg_manageAssettype.tableWidget.setRowCount(0)
        sql='SELECT assettype, assettype_name,conn_type,description FROM public.{}_assettypes GROUP BY assettype,assettype_name,conn_type,description ORDER BY assettype;'.format(type)
        self.cur.execute(sql)
        data=self.cur.fetchall()
        print(data)
        for assettype in data:
            rowPosition = self.dlg_manageAssettype.tableWidget.rowCount()
            self.dlg_manageAssettype.tableWidget.insertRow(rowPosition)
            self.dlg_manageAssettype.tableWidget.setItem(rowPosition , 0, QTableWidgetItem(str(assettype['assettype'])))
            
            comboBox = QComboBox()
            comboBox.addItems(getAssetgroups(type,cur))
            self.dlg_manageAssettype.tableWidget.setCellWidget(rowPosition, 1, comboBox)  
            
            self.dlg_manageAssettype.tableWidget.setItem(rowPosition , 2, QTableWidgetItem(assettype['assettype_name']))
                     
            comboBox = QComboBox()
            comboBox.addItems(self.getConnectionTypes())
            comboBox.setCurrentText(str(assettype['conn_type']))
            self.dlg_manageAssettype.tableWidget.setCellWidget(rowPosition, 3, comboBox)            
            
            self.dlg_manageAssettype.tableWidget.setItem(rowPosition , 4, QTableWidgetItem(assettype['description']))
        
    def deleteAssettype(self,type):
        """ Delete selected assettype and refresh table"""
        row_index=self.dlg_manageAssettype.tableWidget.currentRow()
        print (row_index)
        if row_index!=-1:
            assettype=self.dlg_manageAssettype.tableWidget.item(row_index, 0).text()
            sql='DELETE FROM public.'+type+'_assettypes WHERE assettype='+assettype+';'.format(type)
            print(sql)
            self.cur.execute(sql)
            self.showAssettypes(type)
        else:
            self.iface.messageBar().pushMessage("Info", "No item selected!", level=Qgis.Info)
            
    def checkAssettype(self,type,id):
        sql='SELECT assettype FROM public.{}_assettypes WHERE assettype=\'{}\';'.format(type,id)
        print(sql)
        self.cur.execute(sql)
        if self.cur.fetchone():
            print('check assettype: already exists')
            return False
        else:
            print('check assettype: Ok')
            return True
            
    def checkIfIdExists(self,column,table,id):
        sql='SELECT {} FROM public.{} WHERE {}=\'{}\';'.format(column,table,column,id)
        print(sql)
        self.cur.execute(sql)
        if self.cur.fetchone():
            print('check id: already exists')
            return False
        else:
            print('check id: Ok')
            return True
                        
    #ToDo: merge getConnectionTypes & getAssetgroups to getIds
    def getConnectionTypes(self):
        """ get all connection types """
        sql='SELECT id FROM public.connection_types;'
        self.cur.execute(sql)
        connnectionTypes=[]
        for conn in self.cur.fetchall():
            connnectionTypes.append(str(conn['conn']))
        return connnectionTypes
       
    def loadIds(self,column,table):
        """ load the connection ids from DB and show it in the dropdown in dlg_showAddConnType"""
        sql='SELECT {} AS conn_id FROM public.{} GROUP BY {} ORDER BY {};'.format(column,table,column,column)
        print(sql)
        self.cur.execute(sql)
        ids=[]
        for id in self.cur.fetchall():
            ids.append(str(id['conn_id']))
        print (ids)
        self.dlg_showAddConnBundleType.inletConnectionType.clear()
        self.dlg_showAddConnBundleType.inletConnectionType.addItems(ids)
        self.dlg_showAddConnBundleType.outletConnectionType.clear()
        self.dlg_showAddConnBundleType.outletConnectionType.addItems(ids)
        
    def getQTableWidgetKeys(self,table,columnNr):
        """ Get the QTableWidget ids based on table and column Nr.; return tupel """
        keys=[]
        for row in range(table.rowCount()):
            keys.append(float(table.item(row,columnNr).text()))
        return tuple(keys)
            
    def getDBIds(self,column,table):
        """ load the ids from DB table"""
        sql='SELECT {} AS id FROM public.{} GROUP BY {} ORDER BY {};'.format(column,table,column,column)
        print(sql)
        self.cur.execute(sql)
        return list([id['id'] for id in self.cur.fetchall()])           
        
    def showIds(self,dropdown,column,table):
        connnectionTypes=self.getDBIds(column,table)
        dropdown.clear()
        dropdown.addItems(connnectionTypes)
    
    def addConnectionTypeRowToTable(self,dlg):
        """ Add new connection type to connection type table"""
        print('Add new connectiontype row to connection  table')
        rowPosition = dlg.tableWidget.rowCount()
        dlg.tableWidget.insertRow(rowPosition)
        dlg.tableWidget.setItem(rowPosition, 0, QTableWidgetItem(rowPosition))
        comboBox = QComboBox()
        comboBox.addItems(['Supply','Return'])
        dlg.tableWidget.setCellWidget(rowPosition, 1, comboBox)   

    def deleteTableRow (self,dlg,trace):
        """ Delete selected assettype and refresh table"""
        print('delete row')
        row_index=dlg.tableWidget.currentRow()
        print (row_index)
        if row_index!=-1:
            dlg.tableWidget.removeRow(row_index)
        else:
            self.iface.messageBar().pushMessage("Info", "No item selected!", level=Qgis.Info)
                
        #delete row to dlg.traceTableValues in order to trace the changed values         
        if trace:
            for row in sorted(dlg.traceTableValues):
                if row>row_index:
                    dlg.traceTableValues[row-1]=dlg.traceTableValues[row]
            dlg.traceTableValues.pop(len(dlg.traceTableValues)-1,None)
            print(dlg.traceTableValues)
            
    def showConnections(self,dlg,id):
        """ Show Connections from a connection type"""
        dlg.tableWidget.setRowCount(0)
        sql='SELECT sequence, type,temp,description,p FROM public.connections WHERE connection_id={};'.format(id)
        self.cur.execute(sql)
        data=self.cur.fetchall()
        print(data)
        for conn in data:
            rowPosition = dlg.tableWidget.rowCount()
            dlg.tableWidget.insertRow(rowPosition)
            dlg.tableWidget.setItem(rowPosition , 0, QTableWidgetItem(str(conn['sequence'])))
                     
            comboBox = QComboBox()
            comboBox.addItems(['Supply','Return'])
            comboBox.setCurrentText(str(conn[1]))
            dlg.tableWidget.setCellWidget(rowPosition, 1, comboBox)            
            
            dlg.tableWidget.setItem(rowPosition , 2, QTableWidgetItem(str(conn['temp'])))
            dlg.tableWidget.setItem(rowPosition , 3, QTableWidgetItem(str(conn['p'])))
            dlg.tableWidget.setItem(rowPosition , 4, QTableWidgetItem(conn['description']))
    
    def rowCountTable(self,dlg):
        """ Count the rows without empty key rows"""
        counter=0
        for row_index in range(dlg.tableWidget.rowCount()): 
            if dlg.tableWidget.item(row_index,0):
                counter+=1
        #print(counter)
        return counter
        
    def rowCountDB(self,table,filter):
        """ Count the rows of table with filter"""
        sql="SELECT count(*) AS count FROM {} {};".format(table,filter)
        self.cur.execute(sql)
        return self.cur.fetchone()['count']          
        
    def show_TableCurrentRowDialog(self,table,dlg,id,openFnArg):
        """ Show current row in table; openFnArg: 0) table; 1) columns in String; 2) headers in list; 3) filter in String; 4) dropdowns """
        print('Open current row dialog started: ')
        columns=openFnArg[1]
        headers=openFnArg[2]
        filter=openFnArg[3]
        orderby=openFnArg[4]
        dropdowns=openFnArg[5]
        trace=openFnArg[8]
        save_as=openFnArg[9]
        deactivated=openFnArg[10]
        if id!=-1:
            id=dlg.tableWidget.item(id, 0).text()
            title=openFnArg[0]+': ' + id
            dlg='self.dlg_'+openFnArg[0]        
            dlg = TableDialog(title,headers,openFnArg[6],False,save_as,trace)           
            if openFnArg[6]:
                dlg.btn_open.clicked.connect(lambda: openFnArg[6](openFnArg[7],dlg,id))
            if columns[0]=='time_h':
                dlg.btn_add.clicked.connect(lambda: self.addTableRow(dlg,dropdowns,trace,[]))
            else:
                dlg.btn_add.clicked.connect(lambda: self.addTableRow(dlg,dropdowns,trace,deactivated))
            dlg.btn_cancel.clicked.connect(lambda: self.closeDialog(dlg,table,openFnArg))   
            dlg.btn_ok.clicked.connect(lambda: self.saveContent(dlg,id,openFnArg[0],columns,filter,dropdowns,trace))
            if save_as:
                dlg.btn_saveAs.clicked.connect(lambda: self.saveAsAssettype(dlg,openFnArg[0],id,dropdowns))
            
            dlg.btn_delete.clicked.connect(lambda: self.deleteTableRow(dlg,trace))
            dlg.traceTableValues=self.showFilteredTableContent(dlg,openFnArg[0],columns,filter+id,orderby,dropdowns,trace,deactivated)
           
            if trace:
                dlg.tableWidget.itemChanged.connect(dlg.changeItem)
            dlg.show() 
        else:
            self.iface.messageBar().pushMessage("Info", "No item selected!", level=Qgis.Info)                     

    def openAssettype(self,type,dlg,assetgroup):
        """ Open an assettype macro in IDA; copy the assettype template from the installation folder"""
        print('Open Assettype')
        row_index=dlg.tableWidget.currentRow()
        if row_index!=-1:
            assettype=dlg.tableWidget.item(row_index, 0).text()
            sql="SELECT assettype_name,conn_bundle_type FROM public.{}_assettypes WHERE assettype={} AND assetgroup ={};".format(type,assettype,assetgroup)
            print(sql)
            self.cur.execute(sql)
            assettype_=self.cur.fetchone()
            if assettype_:
                assettype_name=assettype_['assettype_name']
                conn_bundle_type=assettype_['conn_bundle_type']
            else:
                if dlg.tableWidget.item(row_index, 1) and dlg.tableWidget.item(row_index, 1).text():
                    assettype_name=dlg.tableWidget.item(row_index, 1).text()
                else:
                    self.iface.messageBar().pushMessage("Info", "Please enter an assettype name!", level=Qgis.Info)
                    return False
                conn_bundle_type=dlg.tableWidget.cellWidget(row_index, 2).currentText()
                conn_bundle_type=conn_bundle_type.split(":")[0]
            name=assetgroup+'_'+assettype+'_'+assettype_name
            dir=self.plugin_dir.replace('/','\\')+"\\{}\\{}_assettypes\\".format(self.dictDB['projectName'],type)
            file=dir+"{}.idm".format(name)
            wroteAssettype=False
            if not os.path.exists(file): 
                WriteAssettypeFiles(self.plugin_dir,name,type,self.cur,conn_bundle_type)
                dlg.traceTableValues[row_index][0]=dlg.traceTableValues[row_index][1]
                dlg.traceTableValues[row_index][1]=''
                wroteAssettype=True
            
            if dlg.traceTableValues[row_index][3] and dlg.traceTableValues[row_index][2] and not wroteAssettype: # override connection bundle only if assettype exists before
                if dlg.traceTableValues[row_index][2]!=dlg.traceTableValues[row_index][3]:
                    print('Changed conn bundle type')
                    print(dlg.traceTableValues[row_index])
                    ExchangeConntypeFiles(self.plugin_dir,name,type,dlg.traceTableValues[row_index][3],dlg.traceTableValues[row_index][2],self.cur)
                    dlg.traceTableValues[row_index][2]=dlg.traceTableValues[row_index][3]
                    dlg.traceTableValues[row_index][3]=''
                    print(dlg.traceTableValues[row_index])
                       
            #AssettypeSensorSignals(self.cur,self.dictDB,dir,file,type,conn_bundle_type,assetgroup,assettype,assettype_name,name)
            
            if dlg.traceTableValues[row_index][1] and dlg.traceTableValues[row_index][0]:
                if dlg.traceTableValues[row_index][0]!=dlg.traceTableValues[row_index][1]:
                    print('~~~~~~~~~~~~~~~rename~~~~~~~~~~')
                    RenameAssettypeFiles(self.plugin_dir,dlg.traceTableValues[row_index][0],type,dlg.traceTableValues[row_index][1],self.cur)
                    dlg.traceTableValues[row_index][0]=dlg.traceTableValues[row_index][1]
                    dlg.traceTableValues[row_index][1]=''
                    file=dir+"{}.idm".format(dlg.traceTableValues[row_index][0])

            #write to DB
            sql="DELETE FROM public.{}_assettypes WHERE assettype={} AND assetgroup ={};".format(type,assettype,assetgroup)
            print(sql)
            self.cur.execute(sql)
            if type=='customer':
                description_index=4
            else:
                description_index=3
            if dlg.tableWidget.item(row_index, description_index):
                description=dlg.tableWidget.item(row_index, description_index).text()
            else:
                description=''

            sql="""INSERT INTO public.{}_assettypes (id,assetgroup, assettype,assettype_name,conn_bundle_type,description) VALUES({},{},{},'{}',{},'{}');\n""".format(
                type,getMaxId(self.cur,type+'_assettypes')+1,assetgroup,assettype,assettype_name,dlg.traceTableValues[row_index][2],description)
            print(sql)
            self.cur.execute(sql)
            
            # Open the building with the IDA ICE Python API
            print('**********************************')
            print(file)
            self.worker_openAssettype = WorkerOpenAPI(file,self.plugin_dir)
            self.threadpool_openAssettype = QThreadPool()
            self.threadpool_openAssettype.start(self.worker_openAssettype)
            
            print('finished open assettype')
        else:
            self.iface.messageBar().pushMessage("Info", "No item selected!", level=Qgis.Info)
        
    def log_change(self, item):
        print('item changed:'+str(item.text()))
        self.changed_items.append(item)
                        
    def writeClimateDataToDB(self,dlg):
        """ write climate data into DB"""
        print('Write climate data to DB')
        name=dlg.input[0].text()
        latitude=dlg.input[1].text()
        longitude=dlg.input[2].text()
        fileName=dlg.input[3].text()
        timezone=dlg.input[4].text()
        height=dlg.input[5].text()
        sql="""UPDATE {}.climate SET
        name = \'{}\',
        latitude = {},
        longitude = {},
        file_name = \'{}\',
        timezone = {},
        height = {};""".format(self.dictDB['versionName'],name,latitude,longitude,fileName,timezone,height)
        print (sql)
        self.cur.execute(sql)
        self.closeDialog(self.dlg_climate,'',['',[],[],'','',[]])
        

    def show_setClimateDialog(self):
        """ show set climate dialog"""
        title='Add bundle connection type'
        climateData=getClimateData(self.cur,self.dictDB,True)
        inputs=[{'label':'Name:','text':climateData['name']},{'label':'Latitude:','text':str(climateData['latitude'])},{'label':'Longitude:','text':str(climateData['longitude'])},{'label':'Climate file path:','text':climateData['filename']},{'label':'Time zone:','text':str(climateData['timezone'])},{'label':'Elevation height:','text':str(climateData['height'])}]
        print(inputs)
        self.dlg_climate=IDA_Districts_NameDialog(title,inputs,False,False)
        self.dlg_climate.btn_ok.clicked.connect(lambda: self.writeClimateDataToDB(self.dlg_climate))
        self.dlg_climate.btn_cancel.clicked.connect(lambda: self.closeDialog(self.dlg_climate,'',['',[],[],'','',[]]))
        self.dlg_climate.show()
        
    def getDefaults(self,table):
        """get the default values of a table """
        sql="""SELECT column_name, column_default
FROM information_schema.columns
WHERE (table_schema, table_name) = ('{}', '{}')
ORDER BY ordinal_position;""".format(self.dictDB['versionName'],table)
        print(sql)
        self.cur.execute(sql)
        defaults=self.cur.fetchall()
        return defaults
        
    def showDefaults(self,dlg,defaults,assetgroup_name):
        """show the default values of a table in the GUI"""
        for default in defaults:
            if default['column_name'] in ['assetgroup','pipe_bundle_type_id','subnetwork','assettype']:
                if default['column_name'] =='assetgroup':
                    dropdownItems=getDropDownItems(self.cur,[[0,'public','{}_assetgroups'.format(assetgroup_name),'id','assetgroup']])
                if default['column_name'] =='pipe_bundle_type_id':
                    dropdownItems=getDropDownItems(self.cur,[[0,'public','pipe_bundle_types','id','description']])
                if default['column_name'] =='subnetwork':  
                    dropdownItems=getDropDownItems(self.cur,[[0,self.dictDB['versionName'],'subnetwork','id','subnetwork']])
                if default['column_name'] =='assettype':  
                    if dlg.input['assetgroup'].currentText()=='(no selection)':
                        dropdownItems=[['(no selection)']]
                    else:
                        dropdownItems=[getFilteredDropDownItems(self.cur,[assetgroup_name+'_assettypes','assettype','assettype_name','assetgroup',dlg.input['assetgroup'].currentText().split(':')[0]])]
                        print(dropdownItems)
                dlg.input[default['column_name']].clear()    
                dlg.input[default['column_name']].addItems(['(no selection)']+dropdownItems[0])
                dlg.input[default['column_name']].setCurrentText("".join(i for i in dropdownItems[0] if i[0]==default['column_default']))
            if default['column_name'] in ['nominaltemperature','maximumtemperature','nominaloppressure','maximumoppressure',
                                'heat_e_kwh','heat_p_kw','tsup_h_deg','cool_e_kwh','cool_p_kw','tsup_c_deg','cold_e_kwh','cold_p_kw']:
                dlg.input[default['column_name']].setText(default['column_default'])
            if default['column_name'] in ['main_plant']:
                print(default['column_default'])
                dlg.input[default['column_name']].setChecked(bool(default['column_default']))
   
    def show_DefaultsLinesDialog(self):
        """ show the efaultsLinesDialog"""
        defaults=self.getDefaults("lines")
        self.dlg_defaultsLines=DefaultsDialog('line',"Defaults layer lines",[{'label': 'Asset group','value': ['assetgroup',0,'general']},{'label': 'Asset type','value': ['assettype',0,'general']},{'label': 'Pipe bundle type','value': ['pipe_bundle_type_id',0,'general']},{'label': 'Subnetwork','value': ['subnetwork',0,'general']},
                                                {'label': 'Nominal operating temperature, °C','value': ['nominaltemperature',1,'physical']},{'label': 'Maximum operating temperature, °C','value': ['maximumtemperature',1,'physical']},
                                                {'label': 'Nominal operating pressure, °C','value': ['nominaloppressure',1,'physical']},{'label': 'Maximum operating pressure, °C','value': ['maximumoppressure',1,'physical']}],self.cur)
        self.dlg_defaultsLines.btn_ok.clicked.connect(lambda: self.writeDefaultsToDB(self.dlg_defaultsLines,'lines'))
        self.dlg_defaultsLines.btn_cancel.clicked.connect(lambda: self.closeDialog(self.dlg_defaultsLines,'',['',[],[],'','',[]]))
        self.showDefaults(self.dlg_defaultsLines,defaults,'line')
        self.dlg_defaultsLines.show()
        
    def show_DefaultsCustomersDialog(self):
        """ show the efaultsLinesDialog"""
        defaults=self.getDefaults("customers")
        print(defaults)
        self.dlg_defaultsCustomers=DefaultsDialog('customer',"Defaults layer customers",[{'label': 'Asset group','value': ['assetgroup',0,'general']},{'label': 'Asset type','value': ['assettype',0,'general']},{'label': 'Subnetwork','value': ['subnetwork',0,'general']},
                                                {'label': 'Domestic hot water ID','value': ['dhw_id',0,'physical']},{'label': 'Heating demand, kWh','value': ['heat_e_kwh',1,'physical']},
                                                {'label': 'Nominal heating load, kW','value': ['heat_p_kw',1,'physical']},{'label': 'Nominal setpoint temp. heating, °C','value': ['tsup_h_deg',1,'physical']},
                                                {'label': 'Cooling demand, kWh','value': ['cool_e_kwh',1,'physical']},{'label': 'Nominal cooling load, kW','value': ['cool_p_kw',1,'physical']},
                                                {'label': 'Nominal setpoint temp. cooling, °C','value': ['tsup_c_deg',1,'physical']}],self.cur)
        self.dlg_defaultsCustomers.btn_ok.clicked.connect(lambda: self.writeDefaultsToDB(self.dlg_defaultsCustomers,'customers'))
        self.dlg_defaultsCustomers.btn_cancel.clicked.connect(lambda: self.closeDialog(self.dlg_defaultsCustomers,'',['',[],[],'','',[]]))
        self.showDefaults(self.dlg_defaultsCustomers,defaults,'customer')
        self.dlg_defaultsCustomers.show()
        
    def show_DefaultsPlantsDialog(self):
        """ show the defaultsDialog"""
        defaults=self.getDefaults("energy_plants")
        self.dlg_defaultsPlants=DefaultsDialog('energy_plant',"Defaults layer energy_plants",[{'label': 'Asset group','value': ['assetgroup',0,'general']},{'label': 'Asset type','value': ['assettype',0,'general']},{'label': 'Subnetwork','value': ['subnetwork',0,'general']},
                                                {'label': 'Is this the main plant','value': ['main_plant',2,'physical']},{'label': 'Heating supply, kWh','value': ['heat_e_kwh',1,'physical']},
                                                {'label': 'Nominal heating load, kW','value': ['heat_p_kw',1,'physical']},{'label': 'Nominal supply temp. heating, °C','value': ['tsup_h_deg',1,'physical']},
                                                {'label': 'Cooling supply, kWh','value': ['cold_e_kwh',1,'physical']},{'label': 'Nominal cooling load, kW','value': ['cold_p_kw',1,'physical']},
                                                {'label': 'Nominal supply temp. cooling, °C','value': ['tsup_c_deg',1,'physical']}],self.cur)
        self.dlg_defaultsPlants.btn_ok.clicked.connect(lambda: self.writeDefaultsToDB(self.dlg_defaultsPlants,'energy_plants'))
        self.dlg_defaultsPlants.btn_cancel.clicked.connect(lambda: self.closeDialog(self.dlg_defaultsPlants,'',['',[],[],'','',[]]))
        self.showDefaults(self.dlg_defaultsPlants,defaults,'energy_plant')
        self.dlg_defaultsPlants.show()
        
    def show_DefaultsDevicesDialog(self):
        """ show the defaultsDialog"""
        defaults=self.getDefaults("devices")
        self.dlg_defaultsDevices=DefaultsDialog('device',"Defaults layer devices",[{'label': 'Asset group','value': ['assetgroup',0,'general']},{'label': 'Asset type','value': ['assettype',0,'general']},{'label': 'Subnetwork','value': ['subnetwork',0,'general']}],self.cur)
        self.dlg_defaultsDevices.btn_ok.clicked.connect(lambda: self.writeDefaultsToDB(self.dlg_defaultsDevices,'devices'))
        self.dlg_defaultsDevices.btn_cancel.clicked.connect(lambda: self.closeDialog(self.dlg_defaultsDevices,'',['',[],[],'','',[]]))
        self.showDefaults(self.dlg_defaultsDevices,defaults,'device')
        self.dlg_defaultsDevices.show()
    
    def writeDefaultsToDB(self,dlg,table):
        """Write default values to DB """
        for input in dlg.input:
            print(input)
            value=""
            if input in ['assetgroup','assettype','pipe_bundle_type_id','subnetwork','dhw_id']:
                value=dlg.input[input].currentText()
            else:
                print(dlg.input[input].text())
                print(dlg.input[input].text().isnumeric())
                if dlg.input[input].text().isnumeric():
                    value=dlg.input[input].text()
            print(value)
            value=value.split(':')[0]
            print(value)
            if value:
                if value=='(no selection)':
                    sql='ALTER TABLE "{}".{} ALTER COLUMN {} DROP DEFAULT;'.format(self.dictDB['versionName'],table,input,value)
                    print(sql)
                    self.cur.execute(sql)    
                else:
                    sql='ALTER TABLE "{}".{} ALTER COLUMN {} SET DEFAULT {};'.format(self.dictDB['versionName'],table,input,value)
                    print(sql)
                    self.cur.execute(sql)
        dlg.close()
        uri = QgsDataSourceUri()
        uri.setConnection(self.dictDB['host'], self.dictDB['port'], self.dictDB['projectName'], self.dictDB['user'], self.dictDB['pwd'])
        print(uri)

        removeLayer(table)
        
        loadFeatureLayer(self.dictDB['versionName'],self.dictDB,self.plugin_dir,table,self.cur)
        
    def setClimate(self):
        """ set climate data to DB"""
        print('set climate')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_setClimateDialog()  
            
    def setDefaultsLines(self):
        """ set default values for layer lines"""
        print('set defaults lines')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_DefaultsLinesDialog()  
        
    def setDefaultsCustomers(self):
        """ set default values for layer customers"""
        print('set defaults customers')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_DefaultsCustomersDialog() 
            
    def setDefaultsPlants(self):
        """ set default values for layer plants"""
        print('set defaults plants')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_DefaultsPlantsDialog() 
            
    def setDefaultsDevices(self):
        """ set default values for layer devices"""
        print('set defaults plants')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_DefaultsDevicesDialog() 

    def showTableContent(self,dlg,table,dropdowns):
        """show table content"""
        print('show table content')
        cur=self.conn.cursor()
        sql='SELECT * FROM {} ORDER BY id;'.format(table)
        cur.execute(sql) 
        data = cur.fetchall()
        
        dlg.tableWidget.setRowCount(self.rowCountDB(table,''))
        
        dropdownItems=getDropDownItems(self.cur,dropdowns)
        rowPosition = 0
        for row in data:
            for col in range(len(row)):
                if col in list([i[0] for i in dropdowns]):
                    print('dropdown: '+str(col))
                    comboBox = QComboBox()
                    comboBox.addItems(dropdownItems[col])
                    comboBox.setCurrentText(str([i for i in dropdownItems[col] if str(row[col]) == i.split(':')[0]][0]))
                    dlg.tableWidget.setCellWidget(rowPosition, col, comboBox)   
                else:
                    if row[col]==None:
                        value=''
                    else:
                        value=str(row[col])
                    item=QTableWidgetItem(value)
                    if col == 0:
                        item.setFlags(QtCore.Qt.ItemIsEnabled)
                    dlg.tableWidget.setItem(rowPosition , col, item)
            rowPosition+=1
        
    def showFilteredTableContent(self,dlg,table,columns,filter,orderby,dropdowns,trace,deactivated):
        """show filtered table content"""
        print('show filtered table content')
        print(f'trace:{trace}')
        cur=self.conn.cursor()
        dlg.tableWidget.setRowCount(self.rowCountDB(table,filter))
        sql='SELECT {} FROM public.{} {} {} ;'.format(','.join(i for i in columns),table,filter,orderby)
        print(sql)
        cur.execute(sql) 
        data = cur.fetchall()
        dropdownItems=getDropDownItems(self.cur,dropdowns)
        print(dropdownItems)
        rowCount=0
        table_trace={}
        changedConnectionBundleType=''
        changedSimModel=''
        for row in data:
            for col in range(len(row)):
                if col in list([i[0] for i in dropdowns]):
                    comboBox = QComboBox()
                    comboBox.addItems(dropdownItems[col])
                    currentText=''
                    if dropdownItems[col]:
                        for dropDownItem in dropdownItems[col]:
                            if dropDownItem.split(':')[0]==str(row[col]):
                                currentText=dropDownItem
                    comboBox.setCurrentText(currentText)
                    if trace in ['conn_type_trace','bt_conns_trace']:
                        changedConnectionBundleType=currentText
                        comboBox.currentTextChanged.connect(lambda signal, row=rowCount, col=col: dlg.changedDropdownItem(signal,row,col))
                    elif trace:
                        if col in [2,3]:
                            if col==2:
                                changedConnectionBundleType=currentText
                            if col==3:
                                changedSimModel=currentText
                            comboBox.currentTextChanged.connect(lambda signal, row=rowCount, col=col: dlg.changedDropdownItem(signal,row,col))
                    dlg.tableWidget.setCellWidget(rowCount, col, comboBox)   
                else:
                    item=QTableWidgetItem(str(row[col]))
                    if col in deactivated:
                        item.setFlags(QtCore.Qt.ItemIsEnabled)
                    dlg.tableWidget.setItem(rowCount , col, item)
            if trace in ['conn_type_trace','bt_conns_trace']:
                table_trace[rowCount]= [str(row[0]),'',changedConnectionBundleType.split(':')[0],'']
            elif trace:
                table_trace[rowCount]= [filter.split('=')[-1]+'_'+str(row[0])+'_'+str(row[1]),'',changedConnectionBundleType.split(':')[0],'']
                print(table_trace)
            rowCount+=1
        print(table_trace)
        return table_trace

    def manageConnections(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            #self.show_TableDialog('Connections','connections',['Connection Id','Type','Design temperature, °C','Design pressure, Pa','Design massflow, kg/s','Description'],'(id,type,temp,p,mdot,description)',[[1,'public','prefered_conn_dir','id','name']],False, False,['',[],[],'','',[],False,'',False,False]) 
        
            print('Manage connections')
            dropdowns=[[1,'public','prefered_conn_dir','id','name']]
            checkBoxes=[2]
            columns='(id,type,p_ctrl,temp,p,mdot,description)'
            dlg = ConnectionsDialog('Connections',['Connection Id','Type','Pressure controlled','Design temperature, °C','Design pressure, Pa','Design massflow, kg/s','Description'])
            dlg.btn_ok.clicked.connect(lambda: self.saveConnectionsTable(dlg,'connections',columns,dropdowns,False,checkBoxes))
            dlg.btn_cancel.clicked.connect(lambda: closeDialog(dlg))
            dlg.btn_delete.clicked.connect(lambda: self.deleteTableRow(dlg,True))
            dlg.btn_add.clicked.connect(lambda: self.addConnectionsTableRow(dlg,dropdowns))
            self.showConnectionsContent(dlg,dropdowns)         
            dlg.tableWidget.itemChanged.connect(dlg.changedItem)
            dlg.show()
    
    def saveConnectionsTable(self,dlg,table,columns,dropdowns,openFnArg,checkBoxes):
        """ 1) check entries: is value (p,m,T)
            2) updates the changed boundary values in the templates
            3) save the table content in table public.connections"""
        if self.checkConnsInputValues(dlg):
            updateAssettypeBoundaryValues(dlg,self.plugin_dir,self.dictDB,self.cur)
            self.saveTable(dlg,table,columns,dropdowns,openFnArg,checkBoxes,False,False)
    
    def checkConnsInputValues(self,dlg):
        """is value (p,m,T)"""
        for row in range(dlg.tableWidget.rowCount()):
            if (dlg.tableWidget.cellWidget(row,2).isChecked() and not isNumber(dlg.tableWidget.item(row,5).text()) or #m
                not dlg.tableWidget.cellWidget(row,2).isChecked() and not isNumber(dlg.tableWidget.item(row,4).text()) or #p
                not isNumber(dlg.tableWidget.item(row,3).text())): #T
                    self.iface.messageBar().pushMessage("Error", "Please enter a number as input in table row: {}!".format(row), level=Qgis.Critical)
                    return False
        return True
        

            
    def addConnectionsTableRow(self,dlg,dropdowns):
        """Insert table row"""
        rowPosition = 0
        dlg.tableWidget.insertRow(rowPosition)
        dropdownItems=getDropDownItems(self.cur,dropdowns)
        values=[]
        for col in range(dlg.tableWidget.columnCount()):
            values.append('')
            if col in list([i[0] for i in dropdowns]):
                comboBox = QComboBox()
                comboBox.addItems(dropdownItems[col])
                dlg.tableWidget.setCellWidget(rowPosition, col, comboBox)
            elif col==2:
                checkBox=QCheckBox()
                dlg.tableWidget.setCellWidget(0, col, checkBox)
                checkBox.stateChanged.connect(lambda signal, row=0,colmn=col: dlg.changedCheckboxState(signal,row,colmn))
            else:
                if col in [0,5]:
                    if col==0:
                        item=QTableWidgetItem(str(getMaxTableId(dlg.tableWidget)))
                    else:
                        item=QTableWidgetItem('')
                    item.setFlags(QtCore.Qt.ItemIsEnabled)
                    dlg.tableWidget.setItem(0,col,item)
                else:
                    item=QTableWidgetItem('')
                    dlg.tableWidget.setItem(0,col,item)
        #add row to dlg.traceTableValues in order to trace the changed values     
        for row in reversed(sorted(dlg.traceTableValues)):
            dlg.traceTableValues[row+1]=dlg.traceTableValues[row]
        print(dlg.traceTableValues)
        dlg.traceTableValues[0]=['',dlg.tableWidget.item(0,4).text(),'',dlg.tableWidget.item(0,5).text(),'',dlg.tableWidget.item(0,3).text(),'',False] #p_old,p_new,m_old,m_new,t_old,t_new,ctrl_old,ctrl_new
        print(dlg.traceTableValues)
            
    def showConnectionsContent(self,dlg,dropdowns): 
        """show connections table content"""
        print('show filtered table content')
        table='connections'
        cur=self.conn.cursor()
        dlg.tableWidget.setRowCount(self.rowCountDB(table,''))
        sql='SELECT id,type,p_ctrl,temp,p,mdot,description FROM public.connections ORDER BY id;'
        print(sql)
        cur.execute(sql) 
        data = cur.fetchall()
        dropdowns=[[1,'public','prefered_conn_dir','id','name']]
        dropdownItems=getDropDownItems(self.cur,dropdowns)
        print(dropdownItems)
        rowCount=0

        for row in data:
            for col in range(len(row)):
                if col in list([i[0] for i in dropdowns]):
                    comboBox = QComboBox()
                    comboBox.addItems(dropdownItems[col])
                    currentText=''
                    if dropdownItems[col]:
                        for dropDownItem in dropdownItems[col]:
                            if dropDownItem.split(':')[0]==str(row[col]):
                                currentText=dropDownItem
                    comboBox.setCurrentText(currentText)
                    dlg.tableWidget.setCellWidget(rowCount, col, comboBox)   
                elif col==2:
                    checkBox=QCheckBox()
                    if row[col]==True:
                        checkBox.setChecked(True)
                    checkBox.stateChanged.connect(lambda signal, row=rowCount,colmn=col: dlg.changedCheckboxState(signal,row,colmn))
                    dlg.tableWidget.setCellWidget(rowCount, col, checkBox)
                else:
                    item=QTableWidgetItem('' if row[col]==None else str(row[col]))
                    if col == 0:
                        item.setFlags(QtCore.Qt.ItemIsEnabled)
                    elif col == 4 and row[2]==True:
                        item.setFlags(QtCore.Qt.ItemIsEnabled)
                    elif col == 5 and row[2]==False:
                        item.setFlags(QtCore.Qt.ItemIsEnabled)
                    dlg.tableWidget.setItem(rowCount , col, item)
            
            dlg.traceTableValues[rowCount]= ['' if row[4]==None else str(row[4]),'','' if row[5]==None else str(row[5]),'',str(row[3]),'',row[2],''] #p_old,p_new,m_old,m_new,t_old,t_new,ctrl_old,ctrl_new
            rowCount+=1
        print(dlg.traceTableValues)
                    
    def manageConnectionTypes(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_TableDialog(title='Connection types',table='connection_types',headers=['Connection Type Id','Description'],columns='(id,description)', openFn=self.show_TableCurrentRowDialog, openFnArg=['connection_type_connections',['sequence','connection_id'],['Sequence','Connection Id'],'WHERE connection_type_id =','ORDER BY sequence',[[1,'public','connections','id','description']],False,'','conn_type_trace',False,[]]) #title, table, list: table headers, String: column names, Import button function , Open button function, Open function arguments: table,columns,headers,filter, order by, dropdowns [[column_numbers],[tables],[table_cols],[table_names]],openFunction,openFunctionArg,trace, save as btn

    def manageConnBundleTypes(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_TableDialog(title='Connection bundles',table='conn_bundle_types',headers=['Connection bundle Id','Description'],columns='(id,description)', openFn=self.show_TableCurrentRowDialog, openFnArg=['bundle_type_conns',['sequence','conn_type_id','description'],['Sequence','Type','Description'],'WHERE conn_bundle_type_id =','ORDER BY sequence',[[1,'public','connection_types','id','description']],False,'','bt_conns_trace',False,[]]) 

    def managePipeBundlesTypes(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_TableDialog(title='Pipe bundles',table='pipe_bundle_types',headers=['Pipe bundle Id','Description'],columns='(id,description)', openFn=self.show_TableCurrentRowDialog, openFnArg=['bundle_pipes',['sequence','pipe_id','x','y','ambient'],['Sequence','Pipe ID','x, m','y, m','Ambient'],'WHERE pipe_bundle_type_id =','ORDER BY sequence',[[1,'public','pipes','id','name'],[4,'public','pipe_ambient','id','ambient']],False,'',False,False,[]]) 
            
    def manageMaterials(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_TableDialog(title='Materials',table='materials',headers=['Id','Name','Thermal conductivity, W/(m*K)','Specific heat, J/(kg*K)','Density, kg/m3'],columns='(id, name, thermal_conductivity_w7mkelvin, specific_heat_j7kgkelvin, density_kg7m3)') 

    def managePipeConstructions(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_TableDialog(title='Pipe constructions',table='pipe_constructions',headers=['Construction Id','Name'],columns='(id, name)', openFn=self.show_TableCurrentRowDialog,openFnArg=['pipe_layers',['sequence','materialid','thickness'],['Sequence', 'Material','Thickness'],'WHERE pipe_construction_id =','ORDER BY id',[[1,'public','materials','id','name']],False,'',False,False,[0]]) 

    def managePipes(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_TableDialog(title='Pipes',table='pipes',headers=['Id','Name','Inner pipe diameter, m','Absolute pipe roughness, m','Pipe construction Id','Description'],columns='(id, name, innerpipediameter, piperoughnessfactor, pipe_construction_id, description)',dropdowns=[[4,'public','pipe_constructions','id','name']]) 
       
    def manageDHWTimeseries(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_TableDialog(title='DHW timeseries',table='dhw_timeseries',headers=['DHW id','Name'],columns='(id, description)',importFn=self.importFn,openFn=self.show_TableCurrentRowDialog,openFnArg=['dhw',['time_h','kg7s'],['Time', 'dhw demand, kg/s',],'WHERE dhw_id =','ORDER BY time_h','',False,'',False,False,[0]]) 
    
    def manageTempTimeseries(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_TableDialog(title='Temperatur timeseries',table='temp_timeseries',headers=['Id','Description'],columns='(id, description)',importFn=self.importFn,openFn=self.show_TableCurrentRowDialog,openFnArg=['temp',['time_h','temp'],['Time', 'Temperature, °C',],'WHERE temp_id =','ORDER BY time_h','',False,'',False,False,[0]]) 
       
    def manageInternalLoadProfiles(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_TableDialog(title='Internal Load profiles',table='internal_loads_profiles',headers=['Id','Description'],columns='(id, description)',importFn=self.importFnInternalLoad,openFn=self.show_TableCurrentRowDialog,openFnArg=['internal_load',['time_h','person_w7m2','electricity_w7m2'],['Time, h', 'Persons, W/m2','Electricity, W/m2'],'WHERE internal_load_id =','ORDER BY time_h','',False,'',False,False,[0]]) 

    def manageAssetgroups(self,assetgroup):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            if assetgroup=='line':
                self.show_TableDialog(title='{} asset groups'.format(assetgroup),table='{}_assetgroups'.format(assetgroup),headers=['Id','Name'],columns='(id, assetgroup)',openFn= self.show_TableCurrentRowDialog,openFnArg=['{}_assettypes'.format(assetgroup),['assettype','assettype_name','description'],['Id', 'Asset type name', 'Description'],'WHERE assetgroup =','ORDER BY assettype','',False,'',False,False,[0]]) 
            elif assetgroup=='customer':
                self.show_TableDialog(title='{} asset groups'.format(assetgroup),table='{}_assetgroups'.format(assetgroup),headers=['Id','Name'],columns='(id, assetgroup)',openFn= self.show_TableCurrentRowDialog,openFnArg=['{}_assettypes'.format(assetgroup),['assettype','assettype_name','conn_bundle_type','description'],['Id', 'Asset type name','Connection bundle type', 'Description'],'WHERE assetgroup =','ORDER BY assettype',[[2,'public','conn_bundle_types','id','description']],self.openAssettype,assetgroup,True,True,[0]]) 
            else:
                self.show_TableDialog(title='{} asset groups'.format(assetgroup),table='{}_assetgroups'.format(assetgroup),headers=['Id','Name'],columns='(id, assetgroup)',openFn= self.show_TableCurrentRowDialog,openFnArg=['{}_assettypes'.format(assetgroup),['assettype','assettype_name','conn_bundle_type','description'],['Id', 'Asset type name','Connection bundle type', 'Description'],'WHERE assetgroup =','ORDER BY assettype',[[2,'public','conn_bundle_types','id','description']],self.openAssettype,assetgroup,True,True,[0]]) 

    def manageNetworks(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            self.show_TableDialog(title='Networks',table='"{}".network'.format(self.dictDB['versionName']),headers=['Id','Description'],columns='(id, description)',ok_fn=updateNetworkDependingFields,ok_fn_arg=[self.cur,self.dictDB]) 

    def delIfNotInDBIds(self,table,openFnArg):
        """delete entries in subtable, if filter and not listed in DB table """
        if openFnArg:
            filter=openFnArg[3]
            if filter:
                ids=self.getDBIds('id',table)
                print(ids)
                if ids:
                    ids=','.join([str(i) for i in ids])
                    sql="DELETE FROM public.{} {} NOT IN ({})".format(openFnArg[0],filter[:-1],ids)
                else:
                    sql="TRUNCATE public.{} CASCADE;".format(str(openFnArg[0]))
                print(sql)
                self.cur.execute(sql)
            
    def saveTable(self,dlg,table,columns,dropdowns,openFnArg,checkBoxes,ok_fn,ok_fn_arg):
        """" Save table to DB an close dialog"""
        print('Save table to DB an close dialog')
        sql="""TRUNCATE {} CASCADE;\n""".format(table)
        for row in range(dlg.tableWidget.rowCount()):
            values= self.getValuesFromTableRow(dlg,dropdowns,row,columns[1:-1].split(','),checkBoxes)
            #print(values)
            if not values:
                print('return')
                return False
            sql+="""INSERT INTO {} {} VALUES ({});\n""".format(table,columns,values)
        print(sql)
        self.cur.execute(sql)
        self.delIfNotInDBIds(table,openFnArg)
        if ok_fn:
            print('----ok-fn---')
            ok_fn(ok_fn_arg[0],ok_fn_arg[1])
        dlg.close()
        
    def addTableRow(self,dlg,dropdowns,trace,deactivated):
        """Insert table row"""
        rowPosition = 0
        traceTableValues=copy.deepcopy(dlg.traceTableValues)
        print('-------insert row---------------')
        dlg.tableWidget.insertRow(rowPosition)
        dropdownItems=getDropDownItems(self.cur,dropdowns)
        for col in range(dlg.tableWidget.columnCount()):
            if col in list([i[0] for i in dropdowns]):
                comboBox = QComboBox()
                comboBox.addItems(dropdownItems[col])
                dlg.tableWidget.setCellWidget(rowPosition, col, comboBox)
                if trace:
                    comboBox.currentTextChanged.connect(lambda signal, row=0,colmn=col: dlg.changedDropdownItem(signal,row,colmn))
            else:
                if col==0:
                    item=QTableWidgetItem(str(getMaxTableId(dlg.tableWidget)+1))
                else:
                    item=QTableWidgetItem('')
                if col in deactivated:
                    item.setFlags(QtCore.Qt.ItemIsEnabled)
                dlg.tableWidget.setItem(0,col,item)
                
        #add row to dlg.traceTableValues in order to trace the changed values     
        if trace:
            for row in reversed(sorted(traceTableValues)):
                dlg.traceTableValues[row+1]=traceTableValues[row]
            try:
                print('--add trace values of row 0--')
                print(dlg.traceTableValues)
                print(dlg.assetgroup)
                print(dlg.tableWidget.item(0,1))
                print(dlg.tableWidget.item(0,1).text())
                print(str(dlg.assetgroup)+'_'+dlg.tableWidget.item(0,0).text()+'_'+dlg.tableWidget.item(0,1).text())
                dlg.traceTableValues[0]=['',str(dlg.assetgroup)+'_'+dlg.tableWidget.item(0,0).text()+'_'+dlg.tableWidget.item(0,1).text(),'',dlg.tableWidget.cellWidget(0,2).currentText().split(':')[0]]
                print('--finished trace values of row 0--')
            except:
                pass
            print(dlg.traceTableValues)
                
        
    def importFn(self,dlg,table,args,dropdowns):
        print('Import Fn')
        print(args)
        filename, _filter = QFileDialog.getOpenFileName(
            self.dlg, "Import file","", '*.prn;*.txt')
        print(filename)
        if filename:
            id=getMaxTableId(dlg.tableWidget)
            print(id)
            self.addTableRow(dlg,dropdowns,False,[0])
            print(dlg.tableWidget.currentRow())
            dlg.tableWidget.setItem(0,0,QTableWidgetItem(str(id+1)))
            dlg.tableWidget.setItem(0,1,QTableWidgetItem(filename.split('/')[-1].split('.')[0]))
            
            i=0
            sql=""
            with open(filename, "r") as myfile:
                for line in myfile:
                    if i!=0:
                        sql+="""\nINSERT INTO public.{}({}_id,{},{}) VALUES ({},{},{});""".format(args[0],args[0],args[1][0],args[1][1],id+1,line.split()[0],line.split()[1])
                    i+=1
            print(sql)
            self.cur.execute(sql)
            
    def importFnInternalLoad(self,dlg,table,args,dropdowns):
        print('Import Fn internal loads')
        print(args)
        filename, _filter = QFileDialog.getOpenFileName(
            self.dlg, "Import file","", '*.prn;*.txt')
        print(filename)
        if filename:
            id=getMaxTableId(dlg.tableWidget)
            print(id)
            self.addTableRow(dlg,dropdowns,False,[0])
            print(dlg.tableWidget.currentRow())
            dlg.tableWidget.setItem(0,0,QTableWidgetItem(str(id+1)))
            dlg.tableWidget.setItem(0,1,QTableWidgetItem(filename.split('/')[-1].split('.')[0]))
            
            i=0
            sql=""
            with open(filename, "r") as myfile:
                for line in myfile:
                    if i!=0:
                        line=line.split()
                        sql+="""\nINSERT INTO public.internal_load(internal_load_id,time_h,person_w7m2,electricity_w7m2) VALUES ({},{},{},{});""".format(id+1,line[0],line[1],line[2])
                    i+=1
            print(sql)
            self.cur.execute(sql)
            
    def saveAsAssettype(self,dlg,table_name,assetgroup,dropdowns):
        """Save as the assettype"""
        row_idx=dlg.tableWidget.currentRow()
        
        if row_idx!=-1:
            description=""
            if dlg.tableWidget.item(row_idx,3):
                description=dlg.tableWidget.item(row_idx,3).text()
            sql=""
            assettype_id=int(dlg.tableWidget.item(row_idx,0).text())
            maxId=getMaxTableId(dlg.tableWidget)
            assettype_name=dlg.tableWidget.item(row_idx, 1).text()+' (copy)'
            conn_bundle_type_old=dlg.tableWidget.cellWidget(row_idx, 2).currentText()
            file_name_old=assetgroup+'_'+str(assettype_id)+'_'+dlg.tableWidget.item(row_idx, 1).text()
            file_name_new=assetgroup+'_'+str(maxId+1)+'_'+assettype_name
            if not os.path.exists(self.plugin_dir+"\\{}\\{}\\{}.idm".format(self.dictDB['projectName'],table_name,file_name_new)): 
                CopyAssettypeFiles(source_dir=self.plugin_dir+"\\{}\\{}".format(self.dictDB['projectName'],table_name),source_name=file_name_old,target_dir=self.plugin_dir+"\\{}\\{}".format(self.dictDB['projectName'],table_name),target_name=file_name_new)
            
            self.addTableRow(dlg,dropdowns,True,[])
            dlg.tableWidget.setItem(0,0,QTableWidgetItem(str(maxId+1)))
            dlg.tableWidget.setItem(0,1,QTableWidgetItem(assettype_name))
            dlg.tableWidget.cellWidget(0, 2).setCurrentText(conn_bundle_type_old)
            dlg.tableWidget.setItem(0,3,QTableWidgetItem(description))
            
            #replace values of dlg.traceTableValues [0] in order to trace the changed values         
            dlg.traceTableValues[0]=[file_name_new,'',conn_bundle_type_old.split(':')[0],'']
            print(dlg.traceTableValues)

        else:
            self.iface.messageBar().pushMessage("Info", "No item selected!", level=Qgis.Info) 

        
    def show_TableDialog(self,title='',table='',headers=[],columns='',dropdowns='',importFn=False,ok_fn=False,ok_fn_arg=[],openFn=False,openFnArg=['',[],[],'','',[],False,'',False,False,[0]]):
        """Show types from table in DB"""
        print('Manage connection types')
        openBtn=False
        if openFn:
            openBtn=True
        importBtn=False
        if importFn:
            importBtn=True
            
        dlg='self.dlg_' + table
        dlg = TableDialog(title,headers,openBtn,importFn,False,False)
        if openFn:
            dlg.btn_open.clicked.connect(lambda: openFn(table,dlg,dlg.tableWidget.currentRow(),openFnArg))
        if importFn:
            dlg.btn_import.clicked.connect(lambda: importFn(dlg,table,openFnArg,dropdowns))
        dlg.btn_ok.clicked.connect(lambda: self.saveTable(dlg,table,columns,dropdowns,openFnArg,[],ok_fn,ok_fn_arg))
        dlg.btn_cancel.clicked.connect(lambda: self.closeDialog(dlg,table,openFnArg))
        dlg.btn_delete.clicked.connect(lambda: self.deleteTableRow(dlg,False))
        dlg.btn_add.clicked.connect(lambda: self.addTableRow(dlg,dropdowns,False,[]))
        self.showTableContent(dlg,table,dropdowns)
        dlg.show()
    
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = IDADistrictsDataCenterDialog()
            self.dlg.btn_climate.clicked.connect(self.setClimate)
            self.dlg.btn_defaults_lines.clicked.connect(self.setDefaultsLines)
            self.dlg.btn_defaults_customers.clicked.connect(self.setDefaultsCustomers)
            self.dlg.btn_defaults_plants.clicked.connect(self.setDefaultsPlants)
            self.dlg.btn_defaults_devices.clicked.connect(self.setDefaultsDevices)
            self.dlg.btn_connections.clicked.connect(lambda: self.manageConnections())
            self.dlg.btn_connection_types.clicked.connect(lambda: self.manageConnectionTypes())
            self.dlg.btn_conn_bundle_types.clicked.connect(lambda: self.manageConnBundleTypes())
            self.dlg.btn_pipe_bundle_types.clicked.connect(lambda: self.managePipeBundlesTypes())
            self.dlg.btn_materials.clicked.connect(lambda: self.manageMaterials())
            self.dlg.btn_pipe_constructions.clicked.connect(lambda: self.managePipeConstructions())
            self.dlg.btn_pipes.clicked.connect(lambda: self.managePipes())
            self.dlg.btn_dhw_profiles.clicked.connect(lambda: self.manageDHWTimeseries())
            self.dlg.btn_temp_profiles.clicked.connect(lambda: self.manageTempTimeseries())
            self.dlg.btn_internal_loads.clicked.connect(lambda: self.manageInternalLoadProfiles())
            self.dlg.btn_manageLinesAssetgroups.clicked.connect(lambda: self.manageAssetgroups('line'))
            self.dlg.btn_manageCustomerAssetgroups.clicked.connect(lambda: self.manageAssetgroups('customer'))
            self.dlg.btn_manageEnergyPlantAssetgroups.clicked.connect(lambda: self.manageAssetgroups('energy_plant'))
            self.dlg.btn_manageDevicesAssetgroups.clicked.connect(lambda: self.manageAssetgroups('device'))
            self.dlg.btn_manageNetworks.clicked.connect(self.manageNetworks)
            # show the dialog
            self.dlg.show()
            print ('finish')
        else:
            self.dlg.show()
            self.dlg.activateWindow()
            print('activate')

        
