# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IDADistrictsModelingSimulation
                                 A QGIS plugin
 This plugin does districts modeling and simulation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-03-29
        git sha              : $Format:%H$
        copyright            : (C) 2022 by EQUA
        email                : peter.nageler@equa.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from plugins.utility_functions.util import *
from plugins.utility_functions.macros import *
from plugins.utility_functions.files import *
from plugins.utility_functions.ida_components import *
from plugins.utility_functions.db import *
from plugins.utility_functions.dialog import *
from plugins.utility_functions.topology import *
from plugins.utility_functions.templateFiles import *
from .update_sensors import *
from .cosim import *

import math
import time
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QTableWidgetItem, QInputDialog
from scipy.interpolate import interp1d

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ida_districts_modeling_simulation_dialog import BuildBuildingModelDialog, LoadResultsDialog,CalibrateCustomers, OpenModelDialog,SupervisoryCtrlDlg, FeatureDecouplingDlg, FeatureModelParmDlg, ModellingSettings, IDADistrictsModelingSimulationDialog, RequestedOutputs, BuildNetworkModelDialog, CheckableComboBox, RunNetworkModelDialog
from .supervisory_control import Supervisory_control
from .invoke import *
from .outputs import *
from .load_results import *
from .calibrate_features import *
from .invoke_network import InvokeNetworkModel, WorkerBuildNetworkModel
from .calibrate_customers import *
import os
from qgis.core import QgsProject
import psycopg2
import psycopg2.extras
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
import subprocess
  
from plugins.utility_functions.workers import *
from plugins.utility_functions.util import *
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from multiprocessing import Process
from qgis.PyQt.QtGui import QKeySequence
from qgis.PyQt.QtWidgets import QShortcut
from PyQt5.QtCore import Qt
import datetime


class IDADistrictsModelingSimulation:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__).replace('/','\\')
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'IDADistrictsModelingSimulation_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&IDADistricts Modeling Simulation')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.requestedOutputs=loadRequestedOutputs(self.plugin_dir,self.dictDB)
        self.modellingSettings=loadModellingSettings(self.plugin_dir,self.dictDB)
        #print(self.requestedOutputs)
        
        shortcut = QShortcut(QKeySequence('Alt+Shift+M'), iface.mainWindow())
        shortcut.setContext(Qt.ApplicationShortcut)
        shortcut.activated.connect(self.openPlugin)
        self.process_running=False

    def openPlugin(self):
        self.run()
    
    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('IDADistrictsModelingSimulation', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/ida_districts_modeling_simulation/icon-mo-sim.png'
        self.add_action(
            icon_path,
            text=self.tr(u'IDA Districts Modelling Simulation'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IDADistricts Modeling Simulation'),
                action)
            self.iface.removeToolBarIcon(action)
        
    def setNetworkSimData(self,dlg):
        """run network simulation"""
        #print("run network simulation")
        networkSimData={}
        #-----------calc type------------
        if dlg.rbtn_calc_type_periodic.isChecked():
            networkSimData['calc_type']='periodic'
        else:
            networkSimData['calc_type']='dynamic'
        
        #-----------startup type------------
        if dlg.rbtn_startup_type_periodic.isChecked():
            networkSimData['startup_type']='periodic'
        else:
            networkSimData['startup_type']='dynamic'

        networkSimData['numb_of_periods']=dlg.numb_periods.text()
        networkSimData['startup_time_from']=dlg.dateedit_startupFrom.text()
        networkSimData['startup_time_to']=dlg.dateedit_startupTo.text()
        networkSimData['calc_time_from']=dlg.dateedit_calcFrom.text()
        networkSimData['calc_time_to']=dlg.dateedit_calcTo.text()
        if not is_number(dlg.max_timestep.text()):
            iface.messageBar().pushMessage("Warning", "Please enter a number as maximal timestep!", level=Qgis.Warning)
            return False
        else:
            networkSimData['max_timestep']=dlg.max_timestep.text()
        #print(networkSimData)                
        writeNetworkSimData(self.plugin_dir,self.dictDB,networkSimData)
        return networkSimData
        
    def showFeatureParm(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
                self.dlg_featureParm=FeatureModelParmDlg(self.cur,self.dictDB)
                self.dlg_featureParm.btn_add.clicked.connect(lambda: addParmTableRow(self.dlg_featureParm,self.cur,self.dictDB))
                self.dlg_featureParm.btn_remove.clicked.connect(lambda: deleteSelectedTableRow(self.dlg_featureParm.tableWidget_parameters))
                self.dlg_featureParm.btn_ok.clicked.connect(lambda: setFeatureParm(self.dlg_featureParm,self.conn,self.dictDB,self.plugin_dir))
                self.dlg_featureParm.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_featureParm))
                self.dlg_featureParm.show()
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)  
        
    def setModellingSettings(self,dlg):
        """set modelling settings"""
        #print("set modelling settings")
        
        #pipe settings
        #-------------fd pipe------------
        self.modellingSettings['fd_meterPerNode']=dlg.fd_meterPerNode.text()
        #-------------node------------
        self.modellingSettings['node_vol']=dlg.node_vol.text()
        
        #ambient settings
        #ground settings
        #-------------ground model------------
        self.modellingSettings['ground_model']=dlg.amb_ground_model.currentText() 

        #-------------kusuda------------
        #-------------tsurfmean------------
        self.modellingSettings['kusuda_tsurfmean']=dlg.amb_kusuda_tsurfmean.text()
        #-------------tsurfampl------------
        self.modellingSettings['kusuda_tsurfampl']=dlg.amb_kusuda_tsurfampl.text()  
        #-------------theta------------
        self.modellingSettings['kusuda_theta']=dlg.amb_kusuda_theta.text()     
        #-------------rho------------
        self.modellingSettings['kusuda_rho']=dlg.amb_kusuda_rho.text()       
        #-------------cp------------
        self.modellingSettings['kusuda_cp']=dlg.amb_kusuda_cp.text()  
        #-------------lambda------------
        self.modellingSettings['kusuda_lambda']=dlg.amb_kusuda_lambda.text()   
        #-------------depth------------
        self.modellingSettings['kusuda_depth']=dlg.amb_kusuda_depth.text()

        #-------------profile------------
        self.modellingSettings['ground_timeseries']=dlg.amb_ground_profile.currentText()
        
        #-------------temperatur------------
        self.modellingSettings['ground_temp']=dlg.amb_ground_temp.text()
        
        #duct settings
        #-------------duct model------------
        self.modellingSettings['duct_model']=dlg.amb_duct_model.currentText() 
        
        #-------------profile------------
        self.modellingSettings['duct_timeseries']=dlg.amb_duct_profile.currentText()
        
        #-------------temperatur------------
        self.modellingSettings['duct_temp']=dlg.amb_duct_temp.text()
    
        #ambient air settings
        #-------------air model------------
        self.modellingSettings['ambient_air_model']=dlg.amb_ambient_air_model.currentText()
        
        writeModellingSettings(self.plugin_dir,self.dictDB,self.modellingSettings)
        closeDialog(dlg)
        
    def openSupervisoryCtrl(self):
        Supervisory_control(self.plugin_dir)
        
        file = self.plugin_dir+'\\network_models\\{}\\{}\\supervisory_control\\supervisory_control.idm'.format(self.dictDB['projectName'],self.dictDB['versionName'])
        file=file.replace('/','\\')
        #print(file)
        self.worker_openSupervisory = WorkerOpenAPI(file,self.plugin_dir)
        self.threadpool_openSupervisory = QThreadPool()
        self.threadpool_openSupervisory.start(self.worker_openSupervisory)
        self.worker_openSupervisory.signals.error.connect(show_error_message)
        
    def calibrateCustomers(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.dlg_calibrateCustomers=CalibrateCustomers(self.dictDB,self.conn)
                self.dlg_calibrateCustomers.btn_startCallibration.clicked.connect(lambda: startCallibration(self.dlg_calibrateCustomers,self.plugin_dir,self.conn,self.dictDB,self.iface))
                self.dlg_calibrateCustomers.btn_saveCallibration.clicked.connect(lambda: saveCallibValues(self.dlg_calibrateCustomers,self.dictDB,self.conn,self.plugin_dir))
                self.dlg_calibrateCustomers.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_calibrateCustomers))
                self.dlg_calibrateCustomers.btn_openTemplate.clicked.connect(lambda: openTemplate(self.dlg_calibrateCustomers,plugin_dir,conn))
                self.dlg_calibrateCustomers.btn_showCallibCust.clicked.connect(lambda: openResult(self.dlg_calibrateCustomers,plugin_dir,conn,cur))
                loadCustomerCalibrationData(self.dlg_calibrateCustomers,self.dictDB,self.conn,self.plugin_dir)
                self.dlg_calibrateCustomers.show()
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)  

    def showRunModel(self):
        """ Run IDA submodels; loop over submodels"""
        #print('Run IDA model')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
                self.dlg_runModel=RunNetworkModelDialog(self.plugin_dir,self.dictDB)
                self.dlg_runModel.combo_submodels.addItem('Check all items')
                dir=self.plugin_dir+'\\network_models\\{}\\{}'.format(self.dictDB['projectName'],self.dictDB['versionName'])
                submodels=getNetworkFileSubmodels(dir)
                self.dlg_runModel.combo_submodels.addItems(submodels)
                for i in range(len(submodels)):
                    self.dlg_runModel.combo_submodels.setItemChecked(int(i)+1,False)
                self.dlg_runModel.show()
                self.dlg_runModel.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_runModel))
                self.dlg_runModel.btn_runModel.clicked.connect(lambda: self.runModel(self.dlg_runModel))
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)  

    def showOpenModel(self,mode='network'):
        """ Show IDA submodels; loop over submodels"""
        #print('Show IDA model')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
                self.dlg_openModel=OpenModelDialog(mode)
                self.dlg_openModel.combo_submodels.addItem('Check all items')
                dir=self.plugin_dir+'\\network_models\\{}\\{}'.format(self.dictDB['projectName'],self.dictDB['versionName'])
                if os.path.exists(dir):
                    submodels=getNetworkFileSubmodels(dir) if mode=='network' else getBuildingFileSubmodels(dir) 
                    #print(submodels)
                    self.dlg_openModel.combo_submodels.addItems(submodels)
                    for i in range(len(submodels)):
                        self.dlg_openModel.combo_submodels.setItemChecked(i+1,False)
                    self.dlg_openModel.show()
                    self.dlg_openModel.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_openModel))
                    self.dlg_openModel.btn_openModel.clicked.connect(lambda: self.openModel(self.dlg_openModel,mode))  
                else:
                    self.iface.messageBar().pushMessage("Info", "Simulation model has not yet been built!", level=Qgis.Info)
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)  
 
    def openModel(self,dlg,mode='network'):
        #print('-***-')
        if len([i for i in range(dlg.combo_submodels.count()) if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i)])==0:
            self.iface.messageBar().pushMessage("Info", "Please select one or more submodels!", level=Qgis.Info)
            return False
        self.requestedOutputs=loadRequestedOutputs(self.plugin_dir,self.dictDB)
        for i in range(dlg.combo_submodels.count()):
            if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i):        
                submodel=dlg.combo_submodels.itemText(i)
                #print(submodel)
                dir=self.plugin_dir+'\\network_models\\{}\\{}\\'.format(self.dictDB['projectName'],self.dictDB['versionName'])
                fname=dir+'{}_{}.idm'.format(mode,submodel)
                #print(fname)
                self.worker_openNetwork = WorkerOpenAPI(fname,self.plugin_dir,submodel=submodel)
                self.threadpool_openNetwork = QThreadPool()
                self.threadpool_openNetwork.start(self.worker_openNetwork) 
                self.worker_openNetwork.signals.error.connect(show_error_message)
                self.worker_openNetwork.signals.progress.connect(dlg.update_progress)

    def runModel(self,dlg):
        networkSimData=self.setNetworkSimData(dlg)
        if networkSimData:
            #print('-***-')
            dlg.n_sims=len([i for i in range(dlg.combo_submodels.count()) if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i)])
            if dlg.n_sims==0:
                self.iface.messageBar().pushMessage("Info", "Please select one or more submodels!", level=Qgis.Info)
                return False
            self.requestedOutputs=loadRequestedOutputs(self.plugin_dir,self.dictDB)
            self.invokedOutputs=loadInvokedOutputs(self.plugin_dir,self.dictDB)
            if self.checkSimOutputs():
                dlg.updateStatusBar('Running')
                self.worker_runNetwork={}
                self.threadpool_runNetwork = QThreadPool()
                dlg.finished_sims=0
                for i in range(dlg.combo_submodels.count()):
                    if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i):        
                        submodel=dlg.combo_submodels.itemText(i)
                        #print(submodel)
                
                        #print('----Update simulation data----')
                        dir=self.plugin_dir+'\\network_models\\{}\\{}\\'.format(self.dictDB['projectName'],self.dictDB['versionName'])
                        fname=dir+'network_{}.idm'.format(submodel)
                        #print(fname)
                        components_idm=propertyListCompsIDM(getIDAListComponents(readFileToString(fname)))
                        
                        data_idm=[]
                        for comp in components_idm:
                            #print(comp)
                            if getCompClass(comp)=='SIMULATION_DATA':
                                #print('++++++++simulation data+++++++')
                                data_idm.append(propertyListCompsIDM(getIDAListComponents(getSimData(self.requestedOutputs,networkSimData))))             
                            else:
                                data_idm.append(comp) 
                        
                        writePropertyListIDMToFile(data_idm,dir,fname)
                        writeSimulatedOutputs(self.plugin_dir,self.dictDB,self.requestedOutputs)
                        
                        self.worker_runNetwork[i] = WorkerSimulateAPI(fname,self.plugin_dir)
                        self.threadpool_runNetwork.start(self.worker_runNetwork[i]) 
                        self.worker_runNetwork[i].signals.error.connect(dlg.show_error_message)
                        self.worker_runNetwork[i].signals.status.connect(dlg.updateStatusBar)   
            else:
                self.iface.messageBar().pushMessage("Info", "The requested outputs differ from the invoked outputs. Please reinvoke the templates.", level=Qgis.Info)
    
    def checkSimOutputs(self):
        #check customers plants
        for type in ['customers','energy_plants']:
            for i in self.invokedOutputs['customers']:
                for j in self.invokedOutputs['customers'][i]:
                    if self.invokedOutputs['customers'][i][j]!=self.requestedOutputs[j]:
                        return False
        
        #check lines
        for i in self.invokedOutputs['lines']:
            if self.invokedOutputs['lines'][i]!=self.requestedOutputs[i]:
                return False
        
        return True
        
    def showModellingSettings(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
                self.modellingSettings=loadModellingSettings(self.plugin_dir,self.dictDB)
                self.dlg_modellingSettings=ModellingSettings(self.plugin_dir,self.modellingSettings,self.cur)
                self.dlg_modellingSettings.btn_ok.clicked.connect(lambda: self.setModellingSettings(self.dlg_modellingSettings))
                self.dlg_modellingSettings.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_modellingSettings))
                self.dlg_modellingSettings.show() 
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)  

    def addBuildingSubmodelTableRow(self,dlg):
        """Insert table row"""
        #print('-------insert row---------------')
        dlg.tableWidget.insertRow(0)

        comboBox = QComboBox() #submodels
        submodels=getUsedBuildingSubmodels(self.cur,self.dictDB)
        comboBox.addItems(submodels)
        dlg.tableWidget.setCellWidget(0, 0, comboBox) 

        comboBox = QComboBox() #building templates
        sql="""SELECT template_name FROM building_templates ORDER BY id;"""
        self.cur.execute(sql)
        building_templates=[i['template_name'] for i in self.cur.fetchall()]
        comboBox.addItems(building_templates)
        dlg.tableWidget.setCellWidget(0, 1, comboBox) 
        
    def addTableRow(self,dlg):
        """Insert table row"""
        #print('-------insert row---------------')
        dropdowns=[[20,'public','liquids','id','liquid']]

        maxId=max([getMaxIdAcrossSchemas(self.dictDB,self.cur,'borehole_fields')+1]+[int(dlg.tableWidget.item(i,0).text())+1 for i in range(dlg.tableWidget.rowCount())])
        dlg.tableWidget.insertRow(0)
        dropdownItems=getDropDownItems(self.cur,dropdowns)

        item = QTableWidgetItem(str(maxId))
        item.setFlags(item.flags() & ~Qt.ItemIsEditable)
        dlg.tableWidget.setItem(0 , 0, item)
        
        comboBox = QComboBox()
        comboBox.addItems([str(i['id']) for i in getTableIds(self.cur,self.dictDB['versionName'],'energy_plants','id')])
        dlg.tableWidget.setCellWidget(0, 1, comboBox) #plant id
        dlg.tableWidget.setItem(0,2,QTableWidgetItem('190')) #zhole
        dlg.tableWidget.setItem(0,3,QTableWidgetItem('0.0575')) #rhole
        dlg.tableWidget.setItem(0,4,QTableWidgetItem('0.039')) #RB
        dlg.tableWidget.setItem(0,5,QTableWidgetItem('0.001')) #RPIPEGROUT
        dlg.tableWidget.setItem(0,6,QTableWidgetItem('100')) #RPIPEEARTH
        dlg.tableWidget.setItem(0,7,QTableWidgetItem('0.0147')) #RGROUTGROUT
        dlg.tableWidget.setItem(0,8,QTableWidgetItem('0.0423')) #RGROUTEARTH
        dlg.tableWidget.setItem(0,9,QTableWidgetItem('0.0147')) #RRINGEARTH
        dlg.tableWidget.setItem(0,10,QTableWidgetItem('840')) #cpgrd
        dlg.tableWidget.setItem(0,11,QTableWidgetItem('3.8')) #lambgrd
        dlg.tableWidget.setItem(0,12,QTableWidgetItem('2880')) #rhogrd
        dlg.tableWidget.setItem(0,13,QTableWidgetItem('4180')) #cpgrout
        dlg.tableWidget.setItem(0,14,QTableWidgetItem('0.6')) #lambgrout
        dlg.tableWidget.setItem(0,15,QTableWidgetItem('1000')) #rhogrout
        dlg.tableWidget.setItem(0,16,QTableWidgetItem('0.016')) #rpipe
        dlg.tableWidget.setItem(0,17,QTableWidgetItem('0.0026')) #thickpipe
        dlg.tableWidget.setItem(0,18,QTableWidgetItem('2200')) #cppipe
        dlg.tableWidget.setItem(0,19,QTableWidgetItem('0.42')) #lambpipe
        comboBox = QComboBox()
        comboBox.addItems(dropdownItems[20])
        dlg.tableWidget.setCellWidget(0, 20, comboBox) #liquid
        dlg.tableWidget.setItem(0,21,QTableWidgetItem('0')) #Tfreeze
        dlg.tableWidget.setItem(0,22,QTableWidgetItem('0.42')) #lambliq
        dlg.tableWidget.setItem(0,23,QTableWidgetItem('2')) #lcasting
        dlg.tableWidget.setItem(0,24,QTableWidgetItem('0.1')) #lambda
        dlg.tableWidget.setItem(0,25,QTableWidgetItem('1000')) #rhosurface
        dlg.tableWidget.setItem(0,26,QTableWidgetItem('4180')) #cpsurface
        dlg.tableWidget.setItem(0,27,QTableWidgetItem('0')) #mir
        dlg.tableWidget.setItem(0,28,QTableWidgetItem('100')) #rmax
        dlg.tableWidget.setItem(0,29,QTableWidgetItem('10')) #nring
        dlg.tableWidget.setItem(0,30,QTableWidgetItem('10')) #nzhole
        dlg.tableWidget.setItem(0,31,QTableWidgetItem('12')) #nlayt
        dlg.tableWidget.setItem(0,32,QTableWidgetItem('0')) #n1
        dlg.tableWidget.setItem(0,33,QTableWidgetItem('0')) #n2
        dlg.tableWidget.setItem(0,34,QTableWidgetItem('0')) #n3
        dlg.tableWidget.setItem(0,35,QTableWidgetItem('0')) #toutput
        dlg.tableWidget.setItem(0,36,QTableWidgetItem('5')) #tmean
        dlg.tableWidget.setItem(0,37,QTableWidgetItem('0')) #geotgrad

    def setBoreholeFieldSettings(self,dlg):
        table=dlg.tableWidget
        boreholefieldsData={}
        
        sql=""
        for row in range(dlg.tableWidget.rowCount()):
            boreholefieldsData[int(table.item(row, 0).text())]={'ep_id': dlg.tableWidget.cellWidget(row, 1).currentText(),'zhole': table.item(row,2).text(),'rhole': table.item(row,3).text(),'rb': table.item(row,4).text(),
                'rpipegrout': table.item(row,5).text(),'rpipeearth': table.item(row,6).text(),'rgroutgrout': table.item(row,7).text(),'rgroutearth': table.item(row,8).text(), 'rringearth': table.item(row,9).text(),
                'cpgrd': table.item(row,10).text(),'lambgrd': table.item(row,11).text(),'rhogrd': table.item(row,12).text(),'cpgrout': table.item(row,13).text(),
                'lambgrout': table.item(row,14).text(),'rhogrout': table.item(row,15).text(),'rpipe': table.item(row,16).text(),'thickpipe': table.item(row,17).text(),
                'cppipe': table.item(row,18).text(),'lambpipe': table.item(row,19).text(),'liqtype': table.cellWidget(row, 20).currentText().split(':')[0],'tfreeze': table.item(row,21).text(),
                'lambliq': table.item(row,22).text(),'lcasting': table.item(row,23).text(),'lambda': table.item(row,24).text(),'rhosurface': table.item(row,25).text(),
                'cpsurface': table.item(row,26).text(),'mir': table.item(row,27).text(),'rmax': table.item(row,28).text(),'nring': table.item(row,29).text(),
                'nzhole': table.item(row,30).text(),'nlayt': table.item(row,31).text(),'n1': table.item(row,32).text(),'n2': table.item(row,33).text(),
                'n3': table.item(row,34).text(),'toutput': table.item(row,35).text(),'tmean': table.item(row,36).text(),'geotgrad': table.item(row,37).text()}
        
        #print(self.loadedBoreholefieldsData)
        #print(boreholefieldsData)
        
        #deleted
        for key_loaded in self.loadedBoreholefieldsData:
            if key_loaded not in boreholefieldsData: 
                #print('removed sensor')
                sql+="""DELETE FROM "{}".borehole_fields WHERE id={};""".format(self.dictDB['versionName'],key_loaded)
        
        #added
        for key_table in boreholefieldsData:
            if key_table not in self.loadedBoreholefieldsData: 
                #print('added field data')
                sql+="""INSERT INTO "{}".borehole_fields (id,ep_id,zhole,rhole,rb,rpipeearth,rpipegrout,rringearth,rgroutearth,rgroutgrout,mir,rmax,nring,nzhole,nlayt,n1,n2,n3,toutput,cpgrd,lambgrd,rhogrd,cpgrout,lambgrout,rhogrout,rpipe,thickpipe,cppipe,lambpipe,lcasting,lambda,rhosurface,cpsurface,liqtype,tfreeze,lambliq,tmean,geotgrad) VALUES({},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},'{}',{},{},{},{});\n""".format(
                    self.dictDB['versionName'],key_table,boreholefieldsData[key_table]['ep_id'],boreholefieldsData[key_table]['zhole'],boreholefieldsData[key_table]['rhole'],
                    boreholefieldsData[key_table]['rb'],boreholefieldsData[key_table]['rpipeearth'],boreholefieldsData[key_table]['rpipegrout'],boreholefieldsData[key_table]['rringearth'],
                    boreholefieldsData[key_table]['rgroutearth'],boreholefieldsData[key_table]['rgroutgrout'],boreholefieldsData[key_table]['mir'],boreholefieldsData[key_table]['rmax'],
                    boreholefieldsData[key_table]['nring'],boreholefieldsData[key_table]['nzhole'],boreholefieldsData[key_table]['nlayt'],boreholefieldsData[key_table]['n1'],
                    boreholefieldsData[key_table]['n2'],boreholefieldsData[key_table]['n3'],boreholefieldsData[key_table]['toutput'],boreholefieldsData[key_table]['cpgrd'],
                    boreholefieldsData[key_table]['lambgrd'],boreholefieldsData[key_table]['rhogrd'],boreholefieldsData[key_table]['cpgrout'],boreholefieldsData[key_table]['lambgrout'],
                    boreholefieldsData[key_table]['rhogrout'],boreholefieldsData[key_table]['rpipe'],boreholefieldsData[key_table]['thickpipe'],
                    boreholefieldsData[key_table]['cppipe'],boreholefieldsData[key_table]['lambpipe'],boreholefieldsData[key_table]['lcasting'],boreholefieldsData[key_table]['lambda'],               
                    boreholefieldsData[key_table]['rhosurface'],boreholefieldsData[key_table]['cpsurface'],boreholefieldsData[key_table]['liqtype'],boreholefieldsData[key_table]['tfreeze'],               
                    boreholefieldsData[key_table]['lambliq'],boreholefieldsData[key_table]['tmean'],boreholefieldsData[key_table]['geotgrad'])               
            else:   
                #Check for updated columns
                for col in ['ep_id','zhole','rhole','rb','rpipeearth','rpipegrout','rringearth','rgroutearth','rgroutgrout','mir','rmax','nring','nzhole','nlayt','n1','n2','n3','toutput','cpgrd','lambgrd','rhogrd','cpgrout','lambgrout','rhogrout','rpipe','thickpipe','cppipe','lambpipe','lcasting','lambda','rhosurface','cpsurface','liqtype','tfreeze','lambliq','tmean','geotgrad']:
                    if self.loadedBoreholefieldsData[key_table][col]!=boreholefieldsData[key_table][col]:
                        sql+="""UPDATE "{}".borehole_fields SET {} = {} WHERE id = {} ;\n""".format(self.dictDB['versionName'],col,boreholefieldsData[key_table][col],key_table)   
        
        try:
            #print(sql)
            self.cur.execute(sql)
            closeDialog(dlg)
        except Exception as e:
            self.iface.messageBar().pushMessage("Error", str(e), level=Qgis.Critical)

    def showBoreholeFieldSettingsData(self,dlg):
        sql="""SELECT * FROM "{}".borehole_fields;""".format(self.dictDB['versionName'])
        self.cur.execute(sql)
        boreholes_data=self.cur.fetchall()
        dropdowns=[[20,'public','liquids','id','liquid']]
        dlg.tableWidget.setRowCount(len(boreholes_data))
        boreholefieldsData={}

        for counter,i in enumerate(boreholes_data):
            #print(counter)
            #print(i)
            boreholefieldsData[i['id']]={'ep_id': str(i['id']),'zhole': str(i['zhole']),'rhole': str(i['rhole']),'rb': str(i['rb']),'rpipegrout': str(i['rpipegrout']),'rgroutearth': str(['rgroutearth']),'rpipeearth': str(i['rpipeearth']),
                'rgroutgrout': str(i['rgroutgrout']),'rringearth': str(i['rringearth']),'cpgrd': str(i['cpgrd']),'lambgrd': str(i['lambgrd']),'rhogrd': str(i['rhogrd']),'cpgrout': str(i['cpgrout']),'lambgrout': str(i['lambgrout']),
                'rhogrout': str(i['rhogrout']),'rpipe': str(i['rpipe']),'thickpipe': str(i['thickpipe']),'cppipe': str(i['cppipe']),'lambpipe': str(i['lambpipe']),'liqtype': str(i['liqtype']),'tfreeze': str(i['tfreeze']),
                'lambliq': str(i['lambliq']),'lcasting': str(i['lcasting']),'lambda': str(i['lambda']),'rhosurface': str(i['rhosurface']),'cpsurface': str(i['cpsurface']),'mir': str(i['mir']),'rmax': str(i['rmax']),
                'nring': str(i['nring']),'nzhole': str(i['nzhole']),'nlayt': str(i['nlayt']),'n1': str(i['n1']),'n2': str(i['n2']),'n3': str(i['n3']),'toutput': str(i['toutput']),'tmean': str(i['tmean']),'geotgrad': str(i['geotgrad'])}
            dropdownItems=getDropDownItems(self.cur,dropdowns)
            
            item = QTableWidgetItem(str(i['id'])) #id
            item.setFlags(item.flags() & ~Qt.ItemIsEditable)
            dlg.tableWidget.setItem(counter,0,item)
            comboBox = QComboBox()
            comboBox.addItems([str(ids['id']) for ids in getTableIds(self.cur,self.dictDB['versionName'],'energy_plants','id')])
            comboBox.setCurrentText(str(i['id']))
            dlg.tableWidget.setCellWidget(counter, 1, comboBox) #plant id
            dlg.tableWidget.setItem(counter,2,QTableWidgetItem(str(i['zhole']))) #zhole
            dlg.tableWidget.setItem(counter,3,QTableWidgetItem(str(i['rhole']))) #rhole
            dlg.tableWidget.setItem(counter,4,QTableWidgetItem(str(i['rb']))) #RB
            dlg.tableWidget.setItem(counter,5,QTableWidgetItem(str(i['rpipegrout']))) #RPIPEGROUT
            dlg.tableWidget.setItem(counter,6,QTableWidgetItem(str(i['rpipeearth']))) #RPIPEEARTH
            dlg.tableWidget.setItem(counter,7,QTableWidgetItem(str(i['rgroutgrout']))) #RGROUTGROUT
            dlg.tableWidget.setItem(counter,8,QTableWidgetItem(str(i['rgroutearth']))) #RGROUTEARTH
            dlg.tableWidget.setItem(counter,9,QTableWidgetItem(str(i['rringearth']))) #RRINGEARTH
            dlg.tableWidget.setItem(counter,10,QTableWidgetItem(str(i['cpgrd']))) #cpgrd
            dlg.tableWidget.setItem(counter,11,QTableWidgetItem(str(i['lambgrd']))) #lambgrd
            dlg.tableWidget.setItem(counter,12,QTableWidgetItem(str(i['rhogrd']))) #rhogrd
            dlg.tableWidget.setItem(counter,13,QTableWidgetItem(str(i['cpgrout']))) #cpgrout
            dlg.tableWidget.setItem(counter,14,QTableWidgetItem(str(i['lambgrout']))) #lambgrout
            dlg.tableWidget.setItem(counter,15,QTableWidgetItem(str(i['rhogrout']))) #rhogrout
            dlg.tableWidget.setItem(counter,16,QTableWidgetItem(str(i['rpipe']))) #rpipe
            dlg.tableWidget.setItem(counter,17,QTableWidgetItem(str(i['thickpipe']))) #thickpipe
            dlg.tableWidget.setItem(counter,18,QTableWidgetItem(str(i['cppipe']))) #cppipe
            dlg.tableWidget.setItem(counter,19,QTableWidgetItem(str(i['lambpipe']))) #lambpipe
            comboBox = QComboBox()
            comboBox.addItems(dropdownItems[20])
            sql="SELECT liquid FROM liquids WHERE id = {};".format(i['liqtype'])
            self.cur.execute(sql)
            comboBox.setCurrentText(str(i['liqtype'])+':'+self.cur.fetchone()['liquid'])
            dlg.tableWidget.setCellWidget(counter, 20, comboBox) #liquid
            dlg.tableWidget.setItem(counter,21,QTableWidgetItem(str(i['tfreeze']))) #tfreeze
            dlg.tableWidget.setItem(counter,22,QTableWidgetItem(str(i['lambliq']))) #lambliq
            dlg.tableWidget.setItem(counter,23,QTableWidgetItem(str(i['lcasting']))) #lcasting
            dlg.tableWidget.setItem(counter,24,QTableWidgetItem(str(i['lambda']))) #lambda
            dlg.tableWidget.setItem(counter,25,QTableWidgetItem(str(i['rhosurface']))) #rhosurface
            dlg.tableWidget.setItem(counter,26,QTableWidgetItem(str(i['cpsurface']))) #cpsurface
            dlg.tableWidget.setItem(counter,27,QTableWidgetItem(str(i['mir']))) #mir
            dlg.tableWidget.setItem(counter,28,QTableWidgetItem(str(i['rmax']))) #rmax
            dlg.tableWidget.setItem(counter,29,QTableWidgetItem(str(i['nring']))) #nring
            dlg.tableWidget.setItem(counter,30,QTableWidgetItem(str(i['nzhole']))) #nzhole
            dlg.tableWidget.setItem(counter,31,QTableWidgetItem(str(i['nlayt']))) #nlayt
            dlg.tableWidget.setItem(counter,32,QTableWidgetItem(str(i['n1']))) #n1
            dlg.tableWidget.setItem(counter,33,QTableWidgetItem(str(i['n2']))) #n2
            dlg.tableWidget.setItem(counter,34,QTableWidgetItem(str(i['n3']))) #n3
            dlg.tableWidget.setItem(counter,35,QTableWidgetItem(str(i['toutput']))) #toutput
            dlg.tableWidget.setItem(counter,36,QTableWidgetItem(str(i['tmean']))) #tmean
            dlg.tableWidget.setItem(counter,37,QTableWidgetItem(str(i['geotgrad']))) #geotgrad
        return boreholefieldsData

    def showBoreholeFieldSettings(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
                headers=["Id","Plant ID","Drilling (Borehole) Depth, m","Drilling (Borehole) Radius, m", "Borehole heat resistance (RB). If RB set to zero, give detailed heat resistances",
                    "Heat resistance between pipe and inner grout, (m2 K)/W","Heat resistance between pipe and earth, (m2 K)/W", "Heat resistance between inner and outer grout, (m2 K)/W","Heat resistance between grout and earth, (m2 K)/W","Heat resistance between groutring and earth, (m2 K)/W",
                    "Heat capacity of ground, J/(kg K)","Heat transfer coefficient of ground, W/(m K)","Density of ground, kg/m3",
                    "Heat capacity of grout, J/(kg K)","Heat transfer coefficient of grout, W/(m K)","Density of grout, kg/m3",
                    "Radius of pipe, m","Thickness of Pipwe wall, m","Heat capacity of pipe, J/(kg K)","Heat transfer coefficient of pipe, W/(m K)",
                    "Type of liquid","Freezing point of liquid, °C","Heat transfer coefficient of liquid, W/(m K)",
                    "Lenght of surface casting, m","Heat transfer coefficient of surface layer, W/(m K)","Density of surface layer, kg/m3", "Heat capacity of surface layer, J/(kg K)",
                    "MIR","Distance from the borehole to the boundary of the calculation region","Number of earth rings around borehole","Number of nodes in borehole","Total number of nodes in extended domain in z-direction",
                    "Number of points in direction 1 of rectangulat result plane","Number of points in direction 2 of rectangulat result plane","Number of points in direction 3 of cubes","Timestep for output of temp field",
                    "Yearly mean temperature, °C","Temperature gradient in ground, K"]
                self.dlg_boreholeFieldSettings=TableDialog("Borehole field settings",headers,False,False,False,False)
                self.dlg_boreholeFieldSettings.btn_ok.clicked.connect(lambda: self.setBoreholeFieldSettings(self.dlg_boreholeFieldSettings))
                self.dlg_boreholeFieldSettings.btn_add.clicked.connect(lambda: self.addTableRow(self.dlg_boreholeFieldSettings))
                self.dlg_boreholeFieldSettings.btn_delete.clicked.connect(lambda: deleteTableRow(self.dlg_boreholeFieldSettings))
                self.dlg_boreholeFieldSettings.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_boreholeFieldSettings))
                self.loadedBoreholefieldsData=self.showBoreholeFieldSettingsData(self.dlg_boreholeFieldSettings)
                self.dlg_boreholeFieldSettings.show()  
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)   
            
    def showSupervisoryCtrl(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
                self.dlg_supervisoryCrtl=SupervisoryCtrlDlg(self.cur,self.dictDB)
                self.dlg_supervisoryCrtl.btn_ok.clicked.connect(lambda: self.setSupervisoryCrtlSubmodel(self.dlg_supervisoryCrtl))
                self.dlg_supervisoryCrtl.btn_open.clicked.connect(lambda: self.openSupervisoryCtrl())
                self.dlg_supervisoryCrtl.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_supervisoryCrtl))
                self.dlg_supervisoryCrtl.show()  
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)   
            
    def setSupervisoryCrtlSubmodel(self,dlg):
        sql="""UPDATE "{}".supervisory_ctrl SET submodel={};""".format(self.dictDB['versionName'],dlg.combo_submodel.currentText())
        self.cur.execute(sql)
        closeDialog(dlg)
        
    def sensorSignals(self):
        """Create sensor signals for comunication between plants, customers and supervisory control"""
        #print('Create sensor signals for comunication between plants, customers and supervisory control')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
                self.updateSensor=UpdateSensors(dictDB=self.dictDB,cur=self.cur,plugin_dir=self.plugin_dir)
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)  
            
    def showFeatureDecoupling(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
                self.dlg_featureDecoupling=FeatureDecouplingDlg(self.plugin_dir,self.cur,self.dictDB)
                self.dlg_featureDecoupling.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_featureDecoupling))
                self.dlg_featureDecoupling.show()    
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)   
    
    def showInvokeFeatures(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.dictDB=getDBConnectionData(self.plugin_dir)
                self.invoke_features=InvokeFeatures(self.plugin_dir,self.dictDB,self.iface)
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)  
     
    def showBuildModel(self):
        """ Build IDA subnetwork models; loop over subnetworks"""
        #print('Build IDA model')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
                self.dlg_buildModel=BuildNetworkModelDialog()
                sql="""SELECT network FROM "{}".lines GROUP BY network ORDER BY network;""".format(self.dictDB['versionName'])
                self.cur.execute(sql)
                self.dlg_buildModel.combo_network_models.addItem('Check all items')
                networks=self.cur.fetchall()
                self.dlg_buildModel.combo_network_models.addItems([str(i['network']) for i in networks])
                for i in range(len(networks)):
                    self.dlg_buildModel.combo_network_models.setItemChecked(i+1,False)
                
                self.dlg_buildModel.combo_submodels.addItem('Check all items')
                submodels=getUsedNetworkSubmodels(self.cur,self.dictDB)
                self.dlg_buildModel.combo_submodels.addItems(submodels)
                for i in range(len(submodels)):
                    self.dlg_buildModel.combo_submodels.setItemChecked(i+1,False)
                self.dlg_buildModel.show()
                self.dlg_buildModel.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_buildModel))
                self.dlg_buildModel.btn_buildNetworkModel.clicked.connect(lambda: self.buildModel(self.dlg_buildModel))
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)  

    def showBuildBuildingModel(self):
        """ Build IDA building models; loop over subnetworks"""
        #print('Build IDA model')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
                self.dlg_buildBuildingModel=BuildBuildingModelDialog()
                
                self.dlg_buildBuildingModel.show()
                self.dlg_buildBuildingModel.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_buildBuildingModel))
                self.dlg_buildBuildingModel.btn_buildBuildingModel.clicked.connect(lambda: self.buildBuildingModel(self.dlg_buildBuildingModel))
                self.dlg_buildBuildingModel.btn_add.clicked.connect(lambda: self.addBuildingSubmodelTableRow(self.dlg_buildBuildingModel))
                self.dlg_buildBuildingModel.btn_delete.clicked.connect(lambda: deleteTableRow(self.dlg_buildBuildingModel))
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)  
            
    def buildModel(self,dlg):
        networks=[]
        for i in range(dlg.combo_network_models.count()):
            if dlg.combo_network_models.itemText(i) != 'Check all items' and dlg.combo_network_models.itemChecked(i):        
                networks.append(dlg.combo_network_models.itemText(i))
                    
        #print(networks)
        submodels=[dlg.combo_submodels.itemText(i) for i in range(dlg.combo_submodels.count()) if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i)]
        #print(submodels)
        if networks and submodels:
            self.worker_invokeNetwork = WorkerBuildNetworkModel(dictDB=self.dictDB,plugin_dir=self.plugin_dir,dlg=dlg,networks=networks,submodels=submodels)
            self.threadpool_invokeNetwork = QThreadPool()
            self.threadpool_invokeNetwork.start(self.worker_invokeNetwork) 
            self.worker_invokeNetwork.signals.error.connect(show_error_message)
            self.worker_invokeNetwork.signals.progress.connect(dlg.update_progress)   
            self.worker_invokeNetwork.signals.finished.connect(dlg.update_finished)   
        else:
            self.iface.messageBar().pushMessage("Info", "Please select one or more submodels and one or more networks!", level=Qgis.Info)

    def buildBuildingModel(self,dlg):
                    
        submodel_templates={dlg.tableWidget.cellWidget(i,0).currentText(): dlg.tableWidget.cellWidget(i,1).currentText() for i in range(dlg.tableWidget.rowCount())}

        if submodel_templates:
            #print(submodel_templates)
            self.dictDB=getDBConnectionData(self.plugin_dir)
            self.conn=dbConnect(self.dictDB,False)
            if self.conn:
                if self.dictDB['versionName']:
                    self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)  
                    for submodel in submodel_templates:
                        #print(submodel)
                        sql="""SELECT 
  (ST_XMax(ST_Extent(geom))-ST_XMin(ST_Extent(geom)))/2 + ST_XMin(ST_Extent(geom)) AS x_center, 
  (ST_YMax(ST_Extent(geom))-ST_YMin(ST_Extent(geom)))/2 + ST_YMin(ST_Extent(geom)) AS y_center
FROM {}.buildings
WHERE submodel={};""".format(self.dictDB['versionName'],submodel)
                        self.cur.execute(sql)
                        center=self.cur.fetchone()
                        #print(center)
                        
                        sql="""SELECT b.id,b_id,z_id,ST_AsText(geom) AS geom,z_height_m,z_bh_m, win_facade_ratio, z_construction, zt.name AS z_template, u.name AS room_unit 
    FROM {}.buildings b, room_units u, zone_templates zt
    WHERE b.submodel={} AND u.id=b.room_unit AND zt.id=b.z_template
    ORDER BY b_id,z_id;""".format(self.dictDB['versionName'],submodel)
                        #print(sql)
                        self.cur.execute(sql)
                        zones=self.cur.fetchall()
                        b_ids=set(str(zone["b_id"]) for zone in zones)
                        sql="""SELECT b.b_id,t.conn_bundle_type 
    FROM {}.buildings b,{}.customers c, customer_templates t
    WHERE b.b_id IN ({}) AND c.id=b.substation_id AND c.template=t.template
    GROUP BY t.conn_bundle_type, b.b_id;""".format(self.dictDB['versionName'],self.dictDB['versionName'],','.join(b_ids))
                        self.cur.execute(sql)
                        conn_data={i['b_id']: getConnsValuesIdentTypeDict(self.cur,i['conn_bundle_type']) for i in self.cur.fetchall()}
                        #print(conn_data)
                        conn_data_alist="""'({})""".format(' '.join(["""({} . ({}))""".format(i,' '.join(['(:N "'+j +
                                                                                                '" :T ' + str(conn_data[i][j][':T'])+
                                                                                                ' :V-VAR '+str(conn_data[i][j][':V-VAR'])+
                                                                                                ' :VAR "'+str(conn_data[i][j][':VAR'])+
                                                                                                '" :V-T '+str(conn_data[i][j][':V-T'])+')' for j in conn_data[i]])) for i in conn_data]))
                        #print(conn_data_alist)
                        ida_script="""((set-slot [@] 'name "building_{}")
(apply 'delete-components (:call :sections [@]))
(insert-district-distr [@] '({}))
(invoke-esbo-plant [@ plant])
(add-substations-to-plant [@] {} {})
(:UPDATE [@ plant]
{}
  (:ADD (:CEO :SYMBOL '(:AT ((36 24)) :R (14 14) :ICON "lib:emeter.ids" :SLOT ("EmeterWater") :NAME "EmeterWater" :DATA :CEO :D (:DICT (ICE DESCRIPTIONS EMETER))) :N "EmeterWater" :T EMETER)
   (:PAR :N N_IN :V 0)
   (:PAR :N N_MONTH :V 13))
  (:ADD (:CEO :SYMBOL '(:AT ((104 24)) :R (14 14) :ICON "lib:emeter.ids" :SLOT ("EmeterLocalChil") :NAME "EmeterLocalChil" :DATA :CEO :D (:DICT (ICE DESCRIPTIONS EMETER))) :N "EmeterLocalChil" :T EMETER)
   (:PAR :N N_IN :V 0)
   (:PAR :N N_MONTH :V 13))
  (:ADD (:CEO :SYMBOL '(:AT ((70 24)) :R (14 14) :ICON "lib:emeter.ids" :SLOT ("EmeterLocalBoil") :NAME "EmeterLocalBoil" :DATA :CEO :D (:DICT (ICE DESCRIPTIONS EMETER))) :N "EmeterLocalBoil" :T EMETER)
   (:PAR :N N_IN :V 0)
   (:PAR :N N_MONTH :V 13))
  (:ADD MACRO-OBJECT SCHEMA '((FORM-DOCUMENT :TYPE SCHEMA :PAGE-WIDTH 178 :PAGE-HEIGHT 97) (SELF-FRAME :AT ((352 190)) :R (342 176) :SLOT (:SELF) :DATA MACRO-OBJECT)) :SYMBOL '(:AT ((46 74)) :R (20 20) :ICON "sys:eo.ids" :SLOT ("Co-simulation-macro") :NAME "Co-simulation-macro" :DATA MACRO-OBJECT) :N "Co-simulation-macro" :T ICE-MACRO :D "ICE macro"))\n""".format(
    submodel,' '.join(b_ids),conn_data_alist,'T' if dlg.checkbox_cosim.isChecked() else 'nil',
  '\n'.join(["""  (:REMOVE "Emeterlocchil_{}")
  (:REMOVE "Emeterlocboil_{}")""".format(counter,counter) for counter,b_id in enumerate(b_ids,1)]) )
                        
                        zone_win_dict={}
                        for counter,zone in enumerate(zones):
                            #print(zone)
                            wkt_string=zone['geom']
                            
                            # Regular expression to match coordinates in the format (x y)
                            pattern = r"(\d+\.\d+ \d+\.\d+)"

                            # Find all the coordinates
                            coordinates = re.findall(pattern, wkt_string)
                            #print(coordinates)

                            corners = []
                            for coordinate in coordinates:
                                # Split each coordinate pair and adjust with the center
                                x, y = coordinate.split(' ')
                                corners.append((round(float(x) - center['x_center'],2), round(float(y) - center['y_center'],2)))

                            # Format the corners with brackets but no commas between coordinates
                            corners_str = f"({') ('.join([f'{x} {y}' for x, y in corners[:-1]])})"
                            #print(corners_str)
                            
                            #constructions
                            sql="""SELECT bc.construction_type_id, bc.construction_name,bct.type AS construction_type
    FROM building_constructions bc, building_construction_types bct
    WHERE bc.construction_standard_id={} AND bc.construction_type_id=bct.id 
    ORDER BY bc.construction_type_id;""".format(zone['z_construction'])
                            self.cur.execute(sql)
                            constructions=self.cur.fetchall()
                            constructions_dict={i['construction_type'] : i['construction_name'] for i in constructions}
                            #print(constructions)
                            #print(constructions_dict)
                            zone_win_dict["Zone_{}_{}".format(zone['b_id'],zone['z_id'])]={'temp_name':constructions_dict['win_template'],'win_facade_ratio':zone['win_facade_ratio']}
                            
                            ida_script+="""(make-zone-from-qgis [@] "Zone_{}_{}" {} {} {} #2A({}))\n""".format(
                                zone['b_id'],zone['z_id'],zone['z_bh_m'],zone['z_height_m'],str(len(corners)-1),corners_str)
                            
                            #internal loads (reset templates)
                            ida_script+="""(apply-zone-template [@] "Zone_{}_{}" "{}" '(:SETPOINTS :CONSTRUCTIONS :INTERNAL-MASSES :INTERNAL-GAINS :vent-system-type :vent-air-flows))\n""".format(
                                zone['b_id'],zone['z_id'],zone['z_template'])
                            
                            ida_script+="""(:SET z_ [@ "Zone_{}_{}"])\n""".format(zone['b_id'],zone['z_id'])
                            #constructions
                            construction_plist="'("+' '.join([":" + i + ' "' +constructions_dict[i]+'"' for i in constructions_dict])+")"
                            #print(construction_plist)
                            ida_script+="""(set-zone-constructions [@ z_] {})\n""".format(construction_plist)
                            
                            #room units
                            if zone['room_unit']=='Ideal units':
                                ida_script+="""(make-component z_ '((HC-UNIT :N "Ideal heater" :T IDEAL-HEATER)
  (:PAR :N PMAX :V (:EVAL (* [z_ GEOMETRY NET_FLOOR_AREA VALUE] [z_ zone-usage 'heating-power VALUE])))))
(make-component z_ '((HC-UNIT :N "Ideal cooler" :T IDEAL-COOLER)
  (:PAR :N PMAX :V (:EVAL (* [z_ GEOMETRY NET_FLOOR_AREA VALUE] [z_ zone-usage 'cooling-power VALUE])))))\n"""
                            elif zone['room_unit']=='Radiator':
                                ida_script+="""(make-component z_ '((HC-UNIT :N "WatRad" :T WATER_HEATER)
  (:PAR :N CONTROLLER :V PI_CONTR)             
  (:PAR :N PMAX :V (:EVAL (* [z_ GEOMETRY NET_FLOOR_AREA VALUE] [z_ zone-usage 'heating-power VALUE])))
  (:RES :N MODEL :F 2560)
  (:PAR :N HEAT_SUP :V (:EVAL (:CALL ESBO-ADV-DISTR-KEY [@ :building PLANT DISTRIBUTION HEAT TO-ZONE "heat{}"])))))\n""".format(zone['b_id'])
                            elif zone['room_unit']=='Heating/cooling floor':
                                ida_script+="""(make-component [z_ FLOOR] '((floor-heat :n "hc-floor" :t therm_floor)
  (:par :n pheat :v (:eval (* [z_ zone-usage 'heating-power VALUE]))))
  (:PAR :N HEAT_SUP :V (:EVAL (:CALL ESBO-ADV-DISTR-KEY [@ :building PLANT DISTRIBUTION HEAT TO-ZONE "heat{}"])))
  (:PAR :N HEAT_SUP :V (:EVAL (:CALL ESBO-ADV-DISTR-KEY[@ :building PLANT DISTRIBUTION COLD TO-ZONE "cold{}"]))))
(:set hc_ [z_ FLOOR "hc-floor"])
(make-component hc_ '(aggregate :n shape :t shape2d))
(:set corn (:call ice-surface-offset (:call ice-3d-pane hc_ t t) (or (:call :wall (:call parent hc_)) (:call parent hc_)) 0 (:zone hc_) 0))
(:set ncorn (:call length corn))
(:set corn-array (:call make-array (:call list ncorn 2) :initial-contents corn))
(set-values [hc_ SHAPE] 'ncorn ncorn 'CORNERS corn-array)\n""".format(zone['b_id'],zone['b_id'])

                        for zone in zone_win_dict:
                            ida_script+="""(insert-win-by-ratio [@] {} :zones (:call list [@ "{}"]) :sia_380_1 nil :win-template "{}")\n""".format(zone_win_dict[zone]['win_facade_ratio'],zone,zone_win_dict[zone]['temp_name'])
                        
                        ida_script+="""(:for (load  (:call :loads [@]))
  (move-internal-gain-to-center load))\n"""
                                
                        ida_script+="""(save-document [@]))"""
                        #print(ida_script)
                        
                        src_dir=getDataCenterDir(self.plugin_dir)+"\\{}\\building_templates\\".format(self.dictDB['projectName'])
                        #print(src_dir)
                        buildingModel_dir=self.plugin_dir+'\\network_models\\{}\\{}\\'.format(self.dictDB['projectName'],self.dictDB['versionName'])
                        #print(buildingModel_dir)
                        file_path=buildingModel_dir+'building_{}.idm'.format(submodel)
                        #print(file_path)
                        copyFile(src_dir+submodel_templates[submodel]+'.idm',buildingModel_dir,file_path)
                        copy_tree_filter_extensions_and_folders(src_dir+submodel_templates[submodel], buildingModel_dir+'building_'+str(submodel))
                    
                        
                        self.worker_buildBuildingModel = WorkerOpenRunScriptAPI(file_path,self.plugin_dir,ida_script,exit_ida=True,finished_fn=self.finishedBuildBuildingModel,finished_fn_args={'dlg': dlg,'submodel': submodel,'conn_data': conn_data})
                        self.threadpool_buildBuildingModel = QThreadPool()
                        self.threadpool_buildBuildingModel.start(self.worker_buildBuildingModel)
                        self.worker_buildBuildingModel.signals.error.connect(show_error_message)
                        self.worker_buildBuildingModel.signals.progress.connect(dlg.update_progress)
                        #self.finishedBuildBuildingModel({'dlg': dlg,'submodel': submodel,'conn_data': conn_data})

                        
                        """self.util=Util_api(self.plugin_dir)
                        #print(self.util.pid)
                        # IDA ICE connection test
                        connectionTest = self.util.ida_lib.connect_to_ida(b"5945", self.util.pid.encode())
                        #print(connectionTest)
                        self.building = self.util.call_ida_api_function(self.util.ida_lib.openDocument, file_path.encode('utf-8'))
                        #print(self.building)
                        changeWallFlag = self.util.call_ida_api_function(self.util.ida_lib.runIDAScript, self.building, ida_script.encode('utf-8'))"""          

                else:
                    self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
            else:
                self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)  
        else:
            self.iface.messageBar().pushMessage("Info", "Please select one or more submodels!", level=Qgis.Info)

    def finishedBuildBuildingModel(self,args):
        #print('------finished build building model----------')
        try:
            dlg=args['dlg']
            submodel=args['submodel']
            conn_data=args['conn_data']
            co_sim=dlg.checkbox_cosim.isChecked()
            reinvoke=dlg.checkbox_reinvokeFeatures.isChecked()
            #print(co_sim)
            #print(reinvoke)    
            #print(submodel)    
            #print(conn_data) 
            source_dir=self.plugin_dir+'\\network_models\\{}\\{}\\invoked_customers\\'.format(self.dictDB['projectName'],self.dictDB['versionName'])
            target_dir=self.plugin_dir+'\\network_models\\{}\\{}\\building_{}\\plant\\'.format(self.dictDB['projectName'],self.dictDB['versionName'],submodel)
            #print(source_dir) 
            sensor_data=getSensorData(self.cur,self.dictDB,filter='')
            #print(sensor_data)

                        
            for b_id in conn_data:
                #print(b_id)
                #idm
                source_f="{}\\Customer_{}\\Customer_{}.idm".format(source_dir,b_id,b_id)
                #print(source_f)
                if not os.path.exists(source_f) or reinvoke:
                    #print('reinvoke')
                    invokeOneFeature(False,str(b_id),self.plugin_dir,self.cur,self.dictDB,'customer',False)
            
            dir=self.plugin_dir+'\\network_models\\{}\\{}'.format(self.dictDB['projectName'],self.dictDB['versionName'])
            #print(dir)
                
            if co_sim:
                #print('+++++++cosim++++++')
                dec_templates=CopyDecoupledTemplateMacro(str(submodel),dir,self.dictDB,self.cur,self.plugin_dir,sensor_data,mode='building')
                #print('---finished dec---')
                #print(dec_templates.resources)
                if dec_templates.resources:
                    file_data=readFileToList("{}\\building_{}.idm".format(dir,submodel))
                    file_data[2:2]=dec_templates.resources
                    writeToFileFromList(file_data,dir,"{}\\building_{}.idm".format(dir,submodel))
                    
                #decoupling
                feature_dec_irefs=[]
                for submodel_ in getUsedSubmodels(self.cur, self.dictDB):
                    #decoupling: make macro with import/export connections for features which are connected to the submodel lines but not in the submodel  
                    #print('//////************------//////*------')
                    for i in readDecoupledFeatureSensorSignals(submodel_,dir,self.dictDB,self.cur,self.plugin_dir,sensor_data):
                        #print('++++++++--++')
                        #print(i)
                        if i not in feature_dec_irefs:
                            feature_dec_irefs.append(i)
                #print(feature_dec_irefs)

                sensor_dec_data=getSensorDecData(sensor_data,feature_dec_irefs,self.cur,self.dictDB)   
                #print(sensor_dec_data)

                #print(dir)
                #print(type(submodel))
                data_dec_idm=writeCosimMacroIdm(self.dictDB,self.cur,submodel,dir,self.plugin_dir,sensor_data,sensor_dec_data,mode='building')
                #print(data_dec_idm)

                writeCosimMacroIdc(self.dictDB,self.cur,submodel,dir,self.plugin_dir,mode='building')
        
            else:
                #resources
                template_names=getTemplateNamesFilteredByCustomerIds(self.cur,self.dictDB,conn_data) 
                resources=[]        
                for template in template_names:
                    #print('+++++resource: '+template)
                    source_f_idm="{}\\{}\\customer_templates\\{}.idm".format(getDataCenterDir(self.plugin_dir),self.dictDB['projectName'],template)
                    #print(source_f_idm)
                    file_data=readFileToList(source_f_idm)
                    resource=getResourcesFromFileDataList(file_data)
                    #print(resource)
                    if resource not in resources:
                        resources+=resource
                #print(resources)
                        
                if resources:
                    file_data=readFileToList("{}\\building_{}.idm".format(dir,submodel))
                    file_data[2:2]=resources
                    writeToFileFromList(file_data,dir,"{}\\building_{}.idm".format(dir,submodel))
                        
                for b_id in conn_data:
                    #print(b_id)
                    #idm
                    source_f_idm="{}Customer_{}\\Customer_{}.idm".format(source_dir,b_id,b_id)
                    #print(source_f_idm)
                    
                    components_idm=propertyListCompsIDM(getIDAListComponents(readFileToString(source_f_idm)))
                    #print(getConnsValuesByFeature(1,str(b_id),self.cur,self.dictDB))
                    building_pmt2s=['"'+getPMT2muxName(self.cur,i['conn_bundle_type_id'],i['conn_id'])+'"' for i in getConnsValuesByFeature(1,str(b_id),self.cur,self.dictDB) if i['type'] not in [1,2]]
                    #print(building_pmt2s)
                    data_idm=[]
                    for comp in components_idm:
                        if getCompName(comp) in building_pmt2s:
                            data=[]
                            for i in comp:
                                if getCompName(i)=='|M_var|':
                                    #print('|M_var|')
                                    i[':B']=['-1','|term_b|','1']
                                    data.append(i)
                                elif getCompName(i)=='|term_b|':
                                    instream_data=[]
                                    for j in i:
                                        if getCompName(j)=='|inStream(T)|':
                                            #print('|inStream(T)|')
                                            j[':B']=['-1','|term_b|','2']
                                        instream_data.append(j)
                                    data.append(instream_data)
                                else:
                                    data.append(i)
                            data_idm.append(data)
                        else:
                            data_idm.append(comp)
                    writePropertyListIDMToFile(data_idm,target_dir,target_dir+'substation b{}.idm'.format(b_id))


                    source_f_idc="{}Customer_{}\\Customer_{}.idc".format(source_dir,b_id,b_id)
                    #print(source_f_idc)
                    copyFile(source_f_idc,target_dir,target_dir+'substation b{}.idc'.format(b_id))
                    if os.path.exists("{}\\Customer_{}\\Customer_{}".format(source_dir,b_id,b_id)):
                        copy_tree_filter_extensions_and_folders("{}\\Customer_{}\\Customer_{}".format(source_dir,b_id,b_id),target_dir+'substation b{}'.format(b_id),exclude_extensions=['prn'])
        except Exception as e:
            #print(e)
            pass
                
    def loadResults(self,dlg):
        submodels=[dlg.combo_submodels.itemText(i) for i in range(dlg.combo_submodels.count()) if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i)]
        
        simulatedOutputs=loadSimulatedOutputs(self.plugin_dir,self.dictDB)
        if not simulatedOutputs:
            iface.messageBar().pushMessage("Info", "The project version is not yet simulated!", level=Qgis.Info)
            return False
            
        if dlg.checkbox_timestep.checkState() == Qt.Checked:
            if not is_number(dlg.interpolation_dt.text()):
                iface.messageBar().pushMessage("Info", "Please enter a numerical interpolation time!", level=Qgis.Info)
                return False
            
        if submodels:
            self.worker_loadResults = WorkerLoadResults(dictDB=self.dictDB,plugin_dir=self.plugin_dir,dlg=dlg,submodels=submodels,simulatedOutputs=simulatedOutputs)
            self.threadpool_loadResults = QThreadPool()
            self.threadpool_loadResults.start(self.worker_loadResults) 
            self.worker_loadResults.signals.error.connect(show_error_message)
            self.worker_loadResults.signals.progress.connect(dlg.update_progress)   
            self.worker_loadResults.signals.finished.connect(dlg.update_finished)   
        else:
            self.iface.messageBar().pushMessage("Info", "Please select one or more submodels!", level=Qgis.Info)
        
    def showRequestedOutputs(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)  
                self.dictDB=getDBConnectionData(self.plugin_dir)
                self.requestedOutputs=loadRequestedOutputs(self.plugin_dir,self.dictDB)
                self.dlg_outputs=RequestedOutputs(self.requestedOutputs)
                self.dlg_outputs.btn_ok.clicked.connect(lambda: setRequestedOutputs(self.dlg_outputs,self.requestedOutputs,self.iface,self.plugin_dir,self.dictDB,self.cur))
                self.dlg_outputs.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_outputs))
                self.dlg_outputs.show()
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)  
        
    def showLoadResults(self):
        """ show load results; loop over submodels"""
        #print('load results')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            if self.dictDB['versionName']:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
                self.dlg_loadResults=LoadResultsDialog()
                self.dlg_loadResults.combo_submodels.addItem('Check all items')
                dir=self.plugin_dir+'\\network_models\\{}\\{}'.format(self.dictDB['projectName'],self.dictDB['versionName'])
                submodels=getNetworkFileSubmodels(dir)
                self.dlg_loadResults.combo_submodels.addItems(submodels)
                for i in range(len(submodels)):
                   self. dlg_loadResults.combo_submodels.setItemChecked(int(i)+1,False)
                self.dlg_loadResults.show()
                self.dlg_loadResults.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_loadResults))
                self.dlg_loadResults.btn_loadResults.clicked.connect(lambda: self.loadResults(self.dlg_loadResults))
            else:
                self.iface.messageBar().pushMessage("Info", "No project version is loaded!", level=Qgis.Info)
        else:
            self.iface.messageBar().pushMessage("Info", "You are not connected to the DB!", level=Qgis.Info)  
        
    def run(self):
        """Run method that performs all the real work"""
        
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = IDADistrictsModelingSimulationDialog()
            self.dlg.btn_requestedOutputs.clicked.connect(self.showRequestedOutputs)
            self.dlg.btn_custModelParm.clicked.connect(self.showFeatureParm)
            self.dlg.btn_supervisoryContr.clicked.connect(self.showSupervisoryCtrl)
            self.dlg.btn_calibrateCustomers.clicked.connect(self.calibrateCustomers)
            self.dlg.btn_invokeFeatures.clicked.connect(self.showInvokeFeatures)
            self.dlg.btn_modellingSettings.clicked.connect(self.showModellingSettings)
            self.dlg.btn_boreholeFieldSettings.clicked.connect(self.showBoreholeFieldSettings)
            self.dlg.btn_sensorSignals.clicked.connect(self.sensorSignals)
            self.dlg.btn_featureDecoupling.clicked.connect(self.showFeatureDecoupling)
            
            self.dlg.btn_buildModel.clicked.connect(self.showBuildModel)
            self.dlg.btn_openModel.clicked.connect(lambda: self.showOpenModel(mode='network'))
            self.dlg.btn_runModel.clicked.connect(self.showRunModel)
            self.dlg.btn_buildBuildingModel.clicked.connect(self.showBuildBuildingModel)
            self.dlg.btn_openBuildingModel.clicked.connect(lambda: self.showOpenModel(mode='building'))
            self.dlg.btn_loadResults.clicked.connect(self.showLoadResults)

            # show the dialog
            self.dlg.show()
        else:
            self.dlg.show()
            self.dlg.activateWindow()
            #print('activate')


