# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IDADistrictsModelingSimulation
                                 A QGIS plugin
 This plugin does districts modeling and simulation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-03-29
        git sha              : $Format:%H$
        copyright            : (C) 2022 by EQUA
        email                : peter.nageler@equa.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from plugins.utility_functions.util import *
from plugins.utility_functions.macros import *
from plugins.utility_functions.files import *
from plugins.utility_functions.db import *
from plugins.utility_functions.dialog import *
from plugins.utility_functions.topology import *
import math
import time
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QTableWidgetItem, QInputDialog
from scipy.interpolate import interp1d

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ida_districts_modeling_simulation_dialog import LoadResultsDialog,OpenNetworkModelDialog,SupervisoryCtrlDlg, FeatureDecouplingDlg, CustomerModelParmDlg, CalibrateCustomers, ModellingSettings, IDADistrictsModelingSimulationDialog, RequestedOutputs, BuildNetworkModelDialog, CheckableComboBox, RunNetworkModelDialog
from .supervisory_control import Supervisory_control
from .invoke import *
from .invoke_network import InvokeNetworkModel
from .calibrate_customers import *
import os
from qgis.core import QgsProject
import psycopg2
import psycopg2.extras
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
import subprocess
  
from plugins.utility_functions.workerOpenAPI import WorkerOpenAPI,WorkerOpenParRunAPI
from plugins.utility_functions.util import *
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from multiprocessing import Process
from qgis.PyQt.QtGui import QKeySequence
from qgis.PyQt.QtWidgets import QShortcut
from PyQt5.QtCore import Qt
import datetime


def runSimulationCmd(ice_path,file_path,submodel):
    if os.path.exists(file_path):
        if os.path.exists(ice_path):
            cmd="""\"{}bin\\\\ice.exe" -c network_{} -r "{}\"""".format(ice_path.replace('\\','\\\\'),submodel,file_path)
            print(cmd)
            subprocess.call(cmd)
        else:
            iface.messageBar().pushMessage("Error", "ICE directory does not exists!", level=Qgis.Warning)
    else:
        iface.messageBar().pushMessage("Error", "File directory does not exists!", level=Qgis.Warning)
    
def openModelCmd(ice_path,file_path):
    if os.path.exists(file_path):
        if os.path.exists(ice_path):
            cmd="""\"{}bin\\\\ice.exe" -c supervisory_ctrl -o "{}\"""".format(ice_path.replace('\\','\\\\'),file_path)
            print(cmd)
            subprocess.call(cmd)
        else:
            iface.messageBar().pushMessage("Error", "ICE directory does not exists!", level=Qgis.Warning)
    else:
        iface.messageBar().pushMessage("Error", "File directory does not exists!", level=Qgis.Warning)
    
class IDADistrictsModelingSimulation:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'IDADistrictsModelingSimulation_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&IDADistricts Modeling Simulation')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.requestedOutputs=loadRequestedOutputs(self.plugin_dir,self.dictDB)
        self.modellingSettings=loadModellingSettings(self.plugin_dir,self.dictDB)
        print(self.requestedOutputs)
        
        shortcut = QShortcut(QKeySequence('Alt+Shift+M'), iface.mainWindow())
        shortcut.setContext(Qt.ApplicationShortcut)
        shortcut.activated.connect(self.openPlugin)

    def openPlugin(self):
        self.run()
    
    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('IDADistrictsModelingSimulation', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/ida_districts_modeling_simulation/icon-mo-sim.png'
        self.add_action(
            icon_path,
            text=self.tr(u'IDA Districts Modelling Simulation'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IDADistricts Modeling Simulation'),
                action)
            self.iface.removeToolBarIcon(action)
        
    def setRequestedOutputs(self,dlg):
        """set requested outputs"""
        print ("set requested outputs")
        
        #-----------customers------------
        #-----------power----------
        if dlg.checkBoxSubstationPower.isChecked():
            self.requestedOutputs['power_c']=True
        else:
            self.requestedOutputs['power_c']=False
        #-----------temperature----------
        if dlg.checkBoxSubstationConnTemp.isChecked():
            self.requestedOutputs['temp_c']=True
        else:
            self.requestedOutputs['temp_c']=False
        #-----------pressure----------
        if dlg.checkBoxSubstationPressure.isChecked():
            self.requestedOutputs['p_c']=True
        else:
            self.requestedOutputs['p_c']=False
        #-----------mdot----------
        if dlg.checkBoxSubstationMassflow.isChecked():
            self.requestedOutputs['mdot_c']=True
        else:
            self.requestedOutputs['mdot_c']=False
        #-----------heat balance----------
        if dlg.checkBoxSubstationHeatbalance.isChecked():
            self.requestedOutputs['heatbalance_c']=True
        else:
            self.requestedOutputs['heatbalance_c']=False
        #-----------tair----------
        if dlg.checkBoxSubstationTair.isChecked():
            self.requestedOutputs['tair_c']=True
        else:
            self.requestedOutputs['tair_c']=False
        
        #-------------network------------
        #+++lines+++
        #temp
        if dlg.checkBoxTempPipe.isChecked():
            self.requestedOutputs['temp_lines']=True
        else:
            self.requestedOutputs['temp_lines']=False
        #v
        if dlg.checkBoxVPipe.isChecked():
            self.requestedOutputs['v_lines']=True
        else:
            self.requestedOutputs['v_lines']=False
            
        #+++nodes+++
        #mdot
        if dlg.checkBoxMdotNode.isChecked():
            self.requestedOutputs['mdot_lines']=True
        else:
            self.requestedOutputs['mdot_lines']=False
        #pressure
        if dlg.checkBoxPressureDistribution.isChecked():
            self.requestedOutputs['p_lines']=True
        else:
            self.requestedOutputs['p_lines']=False
        
        #-----------energy plants------------
        #-----------power----------
        if dlg.checkBoxPlantPower.isChecked():
            self.requestedOutputs['power_ep']=True
        else:
            self.requestedOutputs['power_ep']=False
        #-----------temperature----------
        if dlg.checkBoxPlantConnTemp.isChecked():
            self.requestedOutputs['temp_ep']=True
        else:
            self.requestedOutputs['temp_ep']=False
        #-----------pressure----------
        if dlg.checkBoxPlantPressure.isChecked():
            self.requestedOutputs['p_ep']=True
        else:
            self.requestedOutputs['p_ep']=False
        #-----------massflow----------
        if dlg.checkBoxPlantMassflow.isChecked():
            self.requestedOutputs['mdot_ep']=True
        else:
            self.requestedOutputs['mdot_ep']=False
            
        #timestep for outputs
        if is_number(dlg.outputTimestep.text()):
            self.requestedOutputs['dt_outputs']=dlg.outputTimestep.text()
        else:
            self.iface.messageBar().pushMessage("Info", "Timestep for Output is not a number!", level=Qgis.Info)
            
        writeRequestedOutputs(self.plugin_dir,self.dictDB,self.requestedOutputs)
        
        #check difference between new and old requested outputs
        outputs_c={}
        outputs_ep={}
        new_outputTimestep=False
        for out in self.requestedOutputs:
            if self.requestedOutputs[out]!=dlg.requestedOutputs_old[out]:
                print('missmatch')
                if '_c' in out:
                    outputs_c[out]=self.requestedOutputs[out]
                if '_ep' in out:
                    outputs_ep[out]=self.requestedOutputs[out]
                if 'dt_outputs'==out:
                    new_outputTimestep=self.requestedOutputs[out]
        print('----')
        print(outputs_c)
        print(outputs_ep)
        
        if outputs_c or new_outputTimestep:
            self.updateAssettypesOutputs('customer',outputs_c,new_outputTimestep)
        if outputs_ep or new_outputTimestep:
            self.updateAssettypesOutputs('energy_plant',outputs_ep,new_outputTimestep)
        
        closeDialog(dlg)
        
    def setNetworkSimData(self,dlg):
        """run network simulation"""
        print ("run network simulation")
        networkSimData={}
        #-----------calc type------------
        if dlg.rbtn_calc_type_periodic.isChecked():
            networkSimData['calc_type']='periodic'
        else:
            networkSimData['calc_type']='dynamic'
        
        #-----------startup type------------
        if dlg.rbtn_startup_type_periodic.isChecked():
            networkSimData['startup_type']='periodic'
        else:
            networkSimData['startup_type']='dynamic'

        networkSimData['numb_of_periods']=dlg.numb_periods.text()
        networkSimData['startup_time_from']=dlg.dateedit_startupFrom.text()
        networkSimData['startup_time_to']=dlg.dateedit_startupTo.text()
        networkSimData['calc_time_from']=dlg.dateedit_calcFrom.text()
        networkSimData['calc_time_to']=dlg.dateedit_calcTo.text()
        if not is_number(dlg.max_timestep.text()):
            iface.messageBar().pushMessage("Warning", "Please enter a number as maximal timestep!", level=Qgis.Warning)
            return False
        else:
            networkSimData['max_timestep']=dlg.max_timestep.text()
        print(networkSimData)                
        writeNetworkSimData(self.plugin_dir,self.dictDB,networkSimData)
        return networkSimData
                
    def updateAssettypesOutputs(self,assettype,outputs,new_outputTimestep):           
        dir = getDataCenterDir(self.plugin_dir)+"\\"+self.dictDB['projectName']+"\\"+assettype+"_assettypes\\"
        print(dir)
                   
        for at_name in getAssettypeNames(self.cur,assettype):
            print(at_name)
            assetgroup=at_name.split('_')[0]
            at=at_name.split('_')[1]
            if new_outputTimestep:
                print('----update timestep for outputs----')
                fname=dir+at_name+'.idm'
                print(fname)
                components_idm=propertyListCompsIDM(getIDAListComponents(readFileToString(fname)))
                data_idm=[]
                output_step=False
                for comp in components_idm:
                    new_comp=[]
                    if getCompClass(comp)=='SIMULATION_DATA':
                        #print('++++++++simulation data+++++++')
                        for i in comp:
                            if getCompName(i)=='CALCULATION-PHASE':
                                i_new=[]
                                #print('++++++++CALCULATION-PHASE+++++++')
                                for j in i:
                                    if getCompName(j)=='OUTPUT-STEP':
                                        #print('++++++++OUTPUT-STEP+++++++')
                                        output_step=True
                                        j[':V']=new_outputTimestep
                                    i_new.append(j)
                                if not output_step:
                                    i_new.append({':C': ':PAR', ':N': 'OUTPUT-STEP', ':V': new_outputTimestep})
                                new_comp.append(i_new)
                            else:
                                new_comp.append(i)
                        data_idm.append(new_comp)              
                    else:
                        data_idm.append(comp) 
                print(data_idm)        
                writePropertyListIDMToFile(data_idm,dir+at_name,fname)
            print('----update outputs----')

            if outputs:
                fname=dir+at_name+'\\'+at_name+'.idm'
                print(fname)
                components_idm=propertyListCompsIDM(getIDAListComponents(readFileToString(fname)))
                data_idm=[]
                conn_bundle_type_id=getConnBundleByAssettype(1 if assettype=='customer' else 2,at,assetgroup,self.cur,self.dictDB)
                connValues=getConnsValues(conn_bundle_type_id,self.cur)
                print(connValues)
                conn_type_seq=set([x['conn_type_seq'] for x in connValues])
                print(conn_type_seq)
                flowmeters=['"'+str(conn_bundle_type_id)+'_'+str(seq)+'_Flowmeter2"' for seq in conn_type_seq]
                print(flowmeters)   
                pmtmuxs={'"PMT2mux_{}_{}_{}_{}_T{}"'.format(value['conn_bundle_type_id'],value['conn_type_seq'],value['conn_type_id'],value['conn_seq'],value['temp']) : {'seq':seq,'conn_bundle_type_id':value['conn_bundle_type_id'],'conn_seq':value['conn_seq']} for seq in conn_type_seq for value in connValues if seq==value['conn_type_seq']}
                print(pmtmuxs)            
                for comp in components_idm:
                    print(getCompName(comp))
                    if getCompTemplate(comp) in ['|lM_H_G_L|','FLOWMETER2','PMT2\\m\\u\\x'] or getCompClass(comp) in 'OUTPUT-FILE':
                        if not isinstance(comp, list):
                            comp=[comp]
                        new_comp=[]
                        if getCompTemplate(comp) in ['|lM_H_G_L|'] and 'tair_c' in [i for i in outputs if outputs[i]]:
                            print('---add tair output----')
                            #print(comp)
                            new_comp=[]
                            outputs_to_set=['|TRoom|']
                            for i in comp:
                                if getCompName(i)=='|TRoom|':
                                    i[':L']='"TAir"'
                                    new_comp.append(i)
                                    outputs_to_set.remove('|TRoom|')
                                else:
                                    new_comp.append(i)
                            for i in outputs_to_set:
                                new_comp.append({':C': ':VAR', ':N': i, ':L': '"TAir"'})
                            comp=new_comp
                            data_idm.append([{':C': 'OUTPUT-FILE', ':N': '"TAir"', ':T': 'OUTPUT-FILE'}])
                        if getCompTemplate(comp) in ['|lM_H_G_L|'] and 'heatbalance_c' in [i for i in outputs if outputs[i]]:
                            print('---add heatbalance output----')
                            #print(comp)
                            new_comp=[]
                            outputs_to_set={'|PhiSolar|':'Solar irradiation','|Occupancy|':'Occupancy','|Electricity|':'Electricty','|PhiInt|':'Internal gains','|PhiRad|':'Heating','|PhiOut|':'Heat transmission','|PhiLeakage|': 'Leakage','|PhiVent|':'Ventilation'}
                            for i in comp:
                                if getCompName(i) in outputs_to_set:
                                    i[':L']='"Heatbalance"'
                                    i[':AS']='"{}"'.format(outputs_to_set[getCompName(i)])
                                    new_comp.append(i)
                                    del outputs_to_set[getCompName(i)]
                                else:
                                    new_comp.append(i)
                            for i in outputs_to_set:
                                new_comp.append({':C': ':VAR', ':N': i, ':L': '"Heatbalance"',':AS':'"{}"'.format(outputs_to_set[i])})
                            comp=new_comp
                            data_idm.append([{':C': 'OUTPUT-FILE', ':N': '"Heatbalance"', ':T': 'OUTPUT-FILE'}])
                        if getCompTemplate(comp) in ['|lM_H_G_L|'] and 'heatbalance_c' in [i for i in outputs if not outputs[i]]:
                            print('---remove heatbalance_c output----')
                            outputs_to_del={'|PhiSolar|':'Solar irradiation','|Occupancy|':'Occupancy','|Electricity|':'Electricty','|PhiInt|':'Internal gains','|PhiRad|':'Heating','|PhiOut|':'Heat transmission','|PhiLeakage|': 'Leakage','|PhiVent|':'Ventilation'}
                            new_comp=[]
                            for i in comp:
                                if getCompName(i) in outputs_to_del:
                                    try:
                                        del i[':L']
                                        del i[':AS']
                                    except:
                                        pass
                                    new_comp.append(i)
                                else:
                                    new_comp.append(i)
                            comp=new_comp
                        if getCompTemplate(comp) in ['|lM_H_G_L|'] and 'tair_c' in [i for i in outputs if not outputs[i]]:
                            print('---remove tair output----')
                            new_comp=[]
                            for i in comp:
                                if getCompName(i)=='|TRoom|':
                                    try:
                                        del i[':L']
                                    except:
                                        pass
                                    new_comp.append(i)
                                else:
                                    new_comp.append(i)
                            comp=new_comp
                        if getCompName(comp) in pmtmuxs:
                            print('-------pmtmux-----')
                            #print(comp)
                            new_comp=[]
                            outputs_to_set=[]
                            outputs_to_del=[]
                            if 'p_c' in [i for i in outputs if outputs[i]] or 'p_ep' in [i for i in outputs if outputs[i]]:
                                outputs_to_set.append('|P_var|')
                            print(outputs_to_set)
                            if 'p_c' in [i for i in outputs if not outputs[i]] or 'p_ep' in [i for i in outputs if not outputs[i]]:
                                outputs_to_del.append('|P_var|')
                            print(outputs_to_del)
                            if outputs_to_set and not getCompPerName(data_idm,'"Connection type sequence_{}"'.format(pmtmuxs[getCompName(comp)]['seq'])):
                                data_idm.append([{':C': 'OUTPUT-FILE', ':N': '"Connection type sequence_{}"'.format(pmtmuxs[getCompName(comp)]['seq']), ':T': 'OUTPUT-FILE'}])
                            if outputs_to_set or outputs_to_del:
                                for i in comp:
                                    if getCompName(i)=='|P_var|' and '|P_var|' in outputs_to_set:
                                        print('++++add p+++++')
                                        i[':L']='"Connection type sequence_{}"'.format(pmtmuxs[getCompName(comp)]['seq'])
                                        i[':AS']='"p_{}_{}"'.format(pmtmuxs[getCompName(comp)]['conn_bundle_type_id'],pmtmuxs[getCompName(comp)]['conn_seq'])
                                        new_comp.append(i)
                                        outputs_to_set.remove('|P_var|')
                                    else:
                                        print('***rest***')
                                        print(getCompName(comp))
                                        if getCompName(i)=='|P_var|' and '|P_var|' in outputs_to_del:
                                            print('del :L and :AS')
                                            new_comp.append({j:i[j] for j in i if j not in [':L',':AS']})
                                        else:
                                            new_comp.append(i)
                                for i in outputs_to_set:
                                    new_comp.append({':C': ':VAR', ':N': i, ':L': '"Connection type sequence_{}"'.format(pmtmuxs[getCompName(comp)]['seq']),':AS':'"p_{}_{}"'.format(pmtmuxs[getCompName(comp)]['conn_bundle_type_id'],pmtmuxs[getCompName(comp)]['conn_seq'])})
                                comp=new_comp
                            
                        if getCompName(comp) in flowmeters:
                            print('-------flow meter-----')
                            #print(comp)
                            new_comp=[]
                            n_sup=1
                            n_ret=1
                            conn_type_seq=getCompName(comp).split('_')[1]
                            outputs_to_set=[]
                            if 'power_c' in [i for i in outputs if outputs[i]] or 'power_ep' in [i for i in outputs if outputs[i]]:
                                outputs_to_set.append('P')
                            if 'temp_c' in [i for i in outputs if outputs[i]] or 'temp_ep' in [i for i in outputs if outputs[i]]:
                                outputs_to_set.append('TSUP')
                                outputs_to_set.append('TRET')
                            if 'mdot_c' in [i for i in outputs if outputs[i]] or 'mdot_ep' in [i for i in outputs if outputs[i]]:
                                outputs_to_set.append('FLOW_SUP')
                                outputs_to_set.append('FLOW_RET')
                            print(outputs_to_set)
                            if outputs_to_set and not getCompPerName(data_idm,'"Connection type sequence_{}"'.format(conn_type_seq)):
                                data_idm.append([{':C': 'OUTPUT-FILE', ':N': '"Connection type sequence_{}"'.format(conn_type_seq), ':T': 'OUTPUT-FILE'}])
                            outputs_to_del=[]
                            if 'power_c' in [i for i in outputs if not outputs[i]] or 'power_ep' in [i for i in outputs if not outputs[i]]:
                                outputs_to_del.append('P')
                            if 'temp_c' in [i for i in outputs if not outputs[i]] or 'temp_ep' in [i for i in outputs if not outputs[i]]:
                                outputs_to_del.append('TSUP')
                                outputs_to_del.append('TRET')
                            if 'mdot_c' in [i for i in outputs if not outputs[i]] or 'mdot_ep' in [i for i in outputs if not outputs[i]]:
                                outputs_to_del.append('FLOW_SUP')
                                outputs_to_del.append('FLOW_RET')
                            print(outputs_to_del)
                            if outputs_to_set or outputs_to_del:
                                for i in comp:
                                    if getCompName(i)=='N_SUP':
                                        n_sup=int(i[':V'])
                                    if getCompName(i)=='N_RET':
                                        n_ret=int(i[':V'])
                                        
                                    if getCompName(i)=='P' and 'P' in outputs_to_set:
                                        print('++++add power+++++')
                                        i[':L']='"Connection type sequence_{}"'.format(conn_type_seq)
                                        i[':AS']='"power"'
                                        new_comp.append(i)
                                        outputs_to_set.remove('P')
                                    elif getCompName(i)=='FLOW_SUP' and 'FLOW_SUP' in outputs_to_set:
                                        print('++++add flow sup+++++')
                                        i[':L']="""#S(MS-SPARSE DEFAULT-VALUE OFF DIMENSION 1 VALUE ({}))""".format(' '.join(['('+str(i)+ ' . '+'"Connection type sequence_{}"'.format(conn_type_seq)+')' for i in range(1,n_sup+1)]))
                                        i[':AS']="""#S(MS-SPARSE DEFAULT-VALUE NIL DIMENSION 1 VALUE ({}))""".format(' '.join(['('+str(i)+ ' . '+'"flow_supply_{}"'.format(conn_type_seq)+')' for i in range(1,n_sup+1)]))
                                        new_comp.append(i)
                                        outputs_to_set.remove('FLOW_SUP')
                                    elif getCompName(i)=='FLOW_RET' and 'FLOW_RET' in outputs_to_set:
                                        print('++++add flow ret+++++')
                                        i[':L']="""#S(MS-SPARSE DEFAULT-VALUE OFF DIMENSION 1 VALUE ({}))""".format(' '.join(['('+str(i)+ ' . '+'"Connection type sequence_{}"'.format(conn_type_seq)+')' for i in range(1,n_sup+1)]))
                                        i[':AS']="""#S(MS-SPARSE DEFAULT-VALUE NIL DIMENSION 1 VALUE ({}))""".format(' '.join(['('+str(i)+ ' . '+'"flow_return_{}"'.format(conn_type_seq)+')' for i in range(1,n_sup+1)]))
                                        new_comp.append(i)
                                        outputs_to_set.remove('FLOW_RET')
                                    elif getCompName(i)=='TSUP' and 'TSUP' in outputs_to_set:
                                        print('++++add T sup+++++')
                                        i[':L']="""#S(MS-SPARSE DEFAULT-VALUE OFF DIMENSION 1 VALUE ({}))""".format(' '.join(['('+str(i)+ ' . '+'"Connection type sequence_{}"'.format(conn_type_seq)+')' for i in range(1,n_sup+1)]))
                                        i[':AS']="""#S(MS-SPARSE DEFAULT-VALUE NIL DIMENSION 1 VALUE ({}))""".format(' '.join(['('+str(i)+ ' . '+'"Tsup_{}"'.format(conn_type_seq)+')' for i in range(1,n_sup+1)]))
                                        new_comp.append(i)
                                        outputs_to_set.remove('TSUP')
                                    elif getCompName(i)=='TRET' and 'TRET' in outputs_to_set:
                                        print('++++add T ret+++++')
                                        i[':L']="""#S(MS-SPARSE DEFAULT-VALUE OFF DIMENSION 1 VALUE ({}))""".format(' '.join(['('+str(i)+ ' . '+'"Connection type sequence_{}"'.format(conn_type_seq)+')' for i in range(1,n_sup+1)]))
                                        i[':AS']="""#S(MS-SPARSE DEFAULT-VALUE NIL DIMENSION 1 VALUE ({}))""".format(' '.join(['('+str(i)+ ' . '+'"Tret_{}"'.format(conn_type_seq)+')' for i in range(1,n_sup+1)]))
                                        new_comp.append(i)
                                        outputs_to_set.remove('TRET')
                                    else:
                                        print('***rest***')
                                        print(getCompName(i))
                                        if getCompName(i) in outputs_to_del:
                                            print('del :L and :AS')
                                            new_comp.append({j:i[j] for j in i if j not in [':L',':AS']})
                                        else:
                                            new_comp.append(i)
                                for i in outputs_to_set:
                                    new_comp.append({':C': ':VAR', ':N': i, ':L': '"Connection type sequence_{}"'.format(conn_type_seq)})
                                comp=new_comp
                        if getCompClass(comp) in 'OUTPUT-FILE':
                            if (getCompName(comp)=='"TAir"' and 'tair_c' in [i for i in outputs if not outputs[i]] or
                                getCompName(comp)=='"Heatbalance"' and 'heatbalance_c' in [i for i in outputs if not outputs[i]] or
                                "Connection type sequence_" in getCompName(comp) and not [True for i in self.requestedOutputs if i in ['power_c','temp_c','p_c','mdot_c'] and self.requestedOutputs[i]]):
                                print('++++not outputfile++++')
                            else:
                                data_idm.append(comp)
                        else:
                            data_idm.append(comp)    
                    else:
                        data_idm.append(comp)
                #print('*************************')
                #for i in data_idm:
                #    print(i)
                writePropertyListIDMToFile(data_idm,dir+at_name,fname)

    
    def setModellingSettings(self,dlg):
        """set modelling settings"""
        print ("set modelling settings")
        
        #pipe settings
        #-------------fd pipe------------
        self.modellingSettings['fd_meterPerNode']=dlg.fd_meterPerNode.text()
        #-------------node------------
        self.modellingSettings['node_vol']=dlg.node_vol.text()
        
        #ambient settings
        #ground settings
        #-------------ground model------------
        self.modellingSettings['ground_model']=dlg.amb_ground_model.currentText() 

        #-------------kusuda------------
        #-------------tsurfmean------------
        self.modellingSettings['kusuda_tsurfmean']=dlg.amb_kusuda_tsurfmean.text()
        #-------------tsurfampl------------
        self.modellingSettings['kusuda_tsurfampl']=dlg.amb_kusuda_tsurfampl.text()  
        #-------------theta------------
        self.modellingSettings['kusuda_theta']=dlg.amb_kusuda_theta.text()     
        #-------------rho------------
        self.modellingSettings['kusuda_rho']=dlg.amb_kusuda_rho.text()       
        #-------------cp------------
        self.modellingSettings['kusuda_cp']=dlg.amb_kusuda_cp.text()  
        #-------------lambda------------
        self.modellingSettings['kusuda_lambda']=dlg.amb_kusuda_lambda.text()   
        #-------------depth------------
        self.modellingSettings['kusuda_depth']=dlg.amb_kusuda_depth.text()

        #-------------profile------------
        self.modellingSettings['ground_timeseries']=dlg.amb_ground_profile.currentText()
        
        #-------------temperatur------------
        self.modellingSettings['ground_temp']=dlg.amb_ground_temp.text()
        
        #duct settings
        #-------------duct model------------
        self.modellingSettings['duct_model']=dlg.amb_duct_model.currentText() 
        
        #-------------profile------------
        self.modellingSettings['duct_timeseries']=dlg.amb_duct_profile.currentText()
        
        #-------------temperatur------------
        self.modellingSettings['duct_temp']=dlg.amb_duct_temp.text()
    
        #ambient air settings
        #-------------air model------------
        self.modellingSettings['ambient_air_model']=dlg.amb_ambient_air_model.currentText()
        
        writeModellingSettings(self.plugin_dir,self.dictDB,self.modellingSettings)
        closeDialog(dlg)

    def showRequestedOutputs(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        print(self.dictDB)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)  
            self.dictDB=getDBConnectionData(self.plugin_dir)
            self.requestedOutputs=loadRequestedOutputs(self.plugin_dir,self.dictDB)
            self.dlg_outputs=RequestedOutputs(self.requestedOutputs)
            self.dlg_outputs.btn_ok.clicked.connect(lambda: self.setRequestedOutputs(self.dlg_outputs))
            self.dlg_outputs.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_outputs))
            self.dlg_outputs.show()

    def showCustomerParm(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        print(self.dictDB)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
            self.dlg_customerParm=CustomerModelParmDlg()
            self.dlg_customerParm.btn_add.clicked.connect(lambda: addParmTableRow(self.dlg_customerParm))
            self.dlg_customerParm.btn_remove.clicked.connect(lambda: deleteSelectedTableRow(self.dlg_customerParm.tableWidget_parameters))
            self.dlg_customerParm.btn_ok.clicked.connect(lambda: setCustParm(self.dlg_customerParm,self.conn,self.dictDB,self.plugin_dir))
            self.dlg_customerParm.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_customerParm))
            loadCustomerParm(self.dlg_customerParm,self.cur,self.dictDB)
            loadLayerFieldsToList(self.dlg_customerParm.listWidget_customerFields,'dhc_customers')
            self.dlg_customerParm.show()
        
    def openSupervisoryCtrl(self):
        Supervisory_control(self.plugin_dir)
        
        file = self.plugin_dir+'\\network_models\\{}\\{}\\supervisory_control\\supervisory_control.idm'.format(self.dictDB['projectName'],self.dictDB['versionName'])
        file=file.replace('/','\\')
        print(file)        # Open the ida file with the IDA ICE Python API
        #process = Process(target=WorkerOpenAPI(file,self.plugin_dir))
        openModelCmd(loadIDADistrictsConfig(self.plugin_dir)['path_ice'],file)
        
    def openTemplate(self,dlg):
        """ Open the selected template"""
        print('Open template')
        print(dlg.tableWidget_templates)
        row_index=dlg.tableWidget_templates.currentRow()
        print(row_index)
        if row_index!=-1:
            if self.conn:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor) 
                assettype=dlg.tableWidget_templates.item(row_index, 0).text()
                sql="""SELECT id AS assetgroup_id FROM customer_assetgroups WHERE assetgroup='{}';""".format(dlg.tableWidget_templates.item(row_index, 2).text())
                self.cur.execute(sql)
                assetgroup=self.cur.fetchone()['assetgroup_id']
                assettype_name=dlg.tableWidget_templates.item(row_index, 1).text()
                parmRun_name=dlg.tableWidget_templates.cellWidget(row_index, 3).currentText()

                name=str(assetgroup)+'_'+assettype+'_'+assettype_name
                dir=getDataCenterDir(self.plugin_dir).replace('/','\\')+"\\{}\\customer_assettypes\\".format(self.dictDB['projectName'])
                file=dir+"{}.idm".format(name)
                
                # Open the building with the IDA ICE Python API
                print('**********************************')
                print(file)
                #process = Process(target=WorkerOpenParRunAPI(file,self.plugin_dir,parmRun_name))
                openModelCmd(loadIDADistrictsConfig(self.plugin_dir)['path_ice'],file)
                
                print('finished open assettype')
        else:
            self.iface.messageBar().pushMessage("Info", "No item selected!", level=Qgis.Info)

    def openResult(self,dlg):
        """ Open the selected result"""
        print('Open result')
        print(dlg.list_tableWidgetResults[dlg.tabwidget.currentIndex()])
        idx=dlg.list_tableWidgetResults[dlg.tabwidget.currentIndex()].currentRow()
        print(idx)
        if idx!=-1:
            if self.conn:
                self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor) 
                
                id=dlg.list_tableWidgetResults[dlg.tabwidget.currentIndex()].item(idx,0).text()
                parmRun_name=[dlg.tableWidget_customer.cellWidget(idx, 3).currentText() for idx in range(0,dlg.tableWidget_customer.rowCount()) if dlg.tableWidget_customer.item(idx, 0).text()==id][0]
                print(parmRun_name)

                name='Customer_'+id
                dir=self.plugin_dir.replace('/','\\')+"\\network_models\\{}\\{}\\invoked_customers\\".format(self.dictDB['projectName'],self.dictDB['versionName'])
                file=dir+"{}.idm".format(name)
                
                # Open the building with the IDA ICE Python API
                print('**********************************')
                print(file)
                process = Process(target=WorkerOpenParRunAPI(file,self.plugin_dir,parmRun_name))
                
                print('finished open assettype')
        else:
            self.iface.messageBar().pushMessage("Info", "No item selected!", level=Qgis.Info)

    def calibrateCustomers(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            self.dlg_calibrateCustomers=CalibrateCustomers(self.dictDB,self.conn)
            self.dlg_calibrateCustomers.btn_startCallibration.clicked.connect(lambda: startCallibration(self.dlg_calibrateCustomers,self.plugin_dir,self.conn,self.dictDB,self.iface))
            self.dlg_calibrateCustomers.btn_saveCallibration.clicked.connect(lambda: saveCallibValues(self.dlg_calibrateCustomers,self.dictDB,self.conn,self.plugin_dir))
            self.dlg_calibrateCustomers.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_calibrateCustomers))
            self.dlg_calibrateCustomers.btn_openTemplate.clicked.connect(lambda: self.openTemplate(self.dlg_calibrateCustomers))
            self.dlg_calibrateCustomers.btn_showCallibCust.clicked.connect(lambda: self.openResult(self.dlg_calibrateCustomers))
            loadCustomerCalibrationData(self.dlg_calibrateCustomers,self.dictDB,self.conn,self.plugin_dir)
            self.dlg_calibrateCustomers.show()
    
    def showModel(self):    
        self.dictDB=getDBConnectionData(self.plugin_dir)
        print(self.dictDB)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)   
            submodels=getDrawnSubmodels(self.cur,self.dictDB)
            if submodels:
                if len(submodels)==1:
                    file = self.plugin_dir+'\\network_models\\{}\\{}\\network_{}.idm'.format(self.dictDB['projectName'],self.dictDB['versionName'],submodels[0])
                else:
                    item, okPressed = QInputDialog.getItem(self.dlg, "Please select a submodel","Submodel", submodels, 0, False)
                    if okPressed:
                        if item:
                            print(item)
                            file = self.plugin_dir+'\\network_models\\{}\\{}\\network_{}.idm'.format(self.dictDB['projectName'],self.dictDB['versionName'],item)
                        else:
                            iface.messageBar().pushMessage("Info", "No submodel is selected!", level=Qgis.Info)
                file=file.replace('/','\\')
                print(file)        # Open the ida file with the IDA ICE Python API
                process = Process(target=WorkerOpenAPI(file,self.plugin_dir))

    def showRunModel(self):
        """ Run IDA submodels; loop over submodels"""
        print('Run IDA model')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
            self.dlg_runModel=RunNetworkModelDialog(self.plugin_dir,self.dictDB)
            self.dlg_runModel.combo_submodels.addItem('Check all items')
            dir=self.plugin_dir+'\\network_models\\{}\\{}'.format(self.dictDB['projectName'],self.dictDB['versionName'])
            submodels=getNetworkFileSubmodels(dir)
            self.dlg_runModel.combo_submodels.addItems(submodels)
            for i in range(len(submodels)):
                self.dlg_runModel.combo_submodels.setItemChecked(int(i)+1,False)
            self.dlg_runModel.show()
            self.dlg_runModel.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_runModel))
            self.dlg_runModel.btn_runModel.clicked.connect(lambda: self.runModel(self.dlg_runModel))

    def showLoadResults(self):
        """ show load results; loop over submodels"""
        print('load results')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
            self.dlg_loadResults=LoadResultsDialog()
            self.dlg_loadResults.combo_submodels.addItem('Check all items')
            dir=self.plugin_dir+'\\network_models\\{}\\{}'.format(self.dictDB['projectName'],self.dictDB['versionName'])
            submodels=getNetworkFileSubmodels(dir)
            self.dlg_loadResults.combo_submodels.addItems(submodels)
            for i in range(len(submodels)):
                self.dlg_loadResults.combo_submodels.setItemChecked(int(i)+1,False)
            self.dlg_loadResults.show()
            self.dlg_loadResults.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_loadResults))
            self.dlg_loadResults.btn_loadResults.clicked.connect(lambda: self.loadResults(self.dlg_loadResults))

    def showOpenModel(self):
        """ Show IDA submodels; loop over submodels"""
        print('Show IDA model')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
            self.dlg_openModel=OpenNetworkModelDialog()
            self.dlg_openModel.combo_submodels.addItem('Check all items')
            dir=self.plugin_dir+'\\network_models\\{}\\{}'.format(self.dictDB['projectName'],self.dictDB['versionName'])
            submodels=getNetworkFileSubmodels(dir)
            print(submodels)
            self.dlg_openModel.combo_submodels.addItems(submodels)
            for i in range(len(submodels)):
                self.dlg_openModel.combo_submodels.setItemChecked(i+1,False)
            self.dlg_openModel.show()
            self.dlg_openModel.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_openModel))
            self.dlg_openModel.btn_openModel.clicked.connect(lambda: self.openModel(self.dlg_openModel))
            
    def loadResults(self,dlg):
        print('-***-')
        networkSimData=loadNetworkSimData(self.plugin_dir,self.dictDB)
        if len([i for i in range(dlg.combo_submodels.count()) if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i)])==0:
            self.iface.messageBar().pushMessage("Info", "Please select one or more submodels!", level=Qgis.Info)
            return False
        self.simulatedOutputs=loadSimulatedOutputs(self.plugin_dir,self.dictDB)
        srid=loadProjectConfig(self.plugin_dir,self.dictDB['projectName'])['srid']
        modellingSettings=loadModellingSettings(self.plugin_dir,self.dictDB)
        #re-create table line_seg, which holds the geometry of the simulated pipe segements
        sql="""DROP TABLE IF EXISTS {}.line_seg;
CREATE TABLE IF NOT EXISTS {}.line_seg
(
    id serial,
    lid integer NOT NULL,
    lid_seg integer NOT NULL,
    geom geometry(LineStringZ,{})
);
SELECT segmentize({},'{}','line_seg');""".format(self.dictDB['versionName'],self.dictDB['versionName'],srid,modellingSettings['fd_meterPerNode'],self.dictDB['versionName'])
        self.cur.execute(sql)
        
        for i in range(dlg.combo_submodels.count()):
            if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i):        
                submodel=dlg.combo_submodels.itemText(i)
                print(submodel)
                dir=self.plugin_dir+'\\network_models\\{}\\{}\\network_{}\\'.format(self.dictDB['projectName'],self.dictDB['versionName'],submodel)
                
                connTypeValues=getConnTypeConnValues(self.cur,getLinesConnTypes(self.cur,self.dictDB))
                #-----update DB tables--------
                sql=''
                #-----------create tables----------------
                #customer tables: customer_s_tair, customer_s_balance, customer_s_conntype_[conn type seq]
                
                
                #energy plant tables: customer_s_conntype_[conn type seq]
                
                
                #lines tables: line_s_t,line_s_v,nodes_s_mdot,nodes_s_p,nodes_s_t
                if self.simulatedOutputs['temp_lines']:
                    sql='\n'.join(["""DROP TABLE IF EXISTS {}.line_s_t${} CASCADE;
CREATE TABLE {}.line_s_t${}
(
	id serial,
    fid integer,
    time timestamp,
	geom geometry(LineStringZ,{}),
	segment integer,
	t numeric,
	CONSTRAINT line_s_t${}_pkey PRIMARY KEY (id)
);""".format(self.dictDB['versionName'],connValue['connection_id'],self.dictDB['versionName'],connValue['connection_id'],srid,connValue['connection_id']) for connValue in connTypeValues])
                print(sql)
                self.cur.execute(sql)
                
                #load data
                #get lids
                sql="""SELECT id FROM {}.dhc_lines ORDER BY id;""".format(self.dictDB['versionName'])
                self.cur.execute(sql)
                lids=self.cur.fetchall()
                
                #get connection sequence
                
                for id in lids:
                    fname=dir+'Line_t_{}.prn'.format(id['id'])
                    print(fname)
                    if os.path.exists(fname):
                        data=[]
                        with open(fname, "r") as myfile:
                            for line in myfile:
                                values_len=len(line.split())-3
                                conn_seq_len=len(set([int(i.split('_')[1]) for i in line.split()[3:]]))
                                value_per_conn_seq=values_len/conn_seq_len
                                print(value_per_conn_seq)
                                break

                        file_data = np.loadtxt(fname, skiprows=1,dtype=float)
                        print(file_data)
                        
                        start_datetime=getDatetimeFromString(networkSimData['calc_time_from'])
                                
                        if dlg.checkbox_timestep.checkState() == Qt.Checked:
                            #linear interpolation
                            time=[]
                            print(dlg.interpolation_dt.text())
                            if is_number(dlg.interpolation_dt.text()):
                                dt=float(dlg.interpolation_dt.text())
                                
                                #startyear_datetime=datetime(start_datetime.year,1,1)
                                start_hour=file_data[0,0]
                                start_hour=start_hour-start_hour%(dt/3600)
                                print(start_hour)
                                end_hour=file_data[-1,0]
                                end_hour=end_hour-end_hour%(dt/3600)+dt/3600
                                print(end_hour)

                                time=np.arange(start_hour, end_hour+dt/3600, dt/3600)

                                #file_data = np.interp(time, file_data[:,0], file_data[:,2:])
                                # apply the interpolation to each column
                                f = interp1d(file_data[:,0], file_data[:,2:], axis=0, fill_value="extrapolate")

                                # get final result
                                file_data=np.column_stack((time,f(time)))
                                
                                print(file_data)
                                

                            else:
                                self.iface.messageBar().pushMessage("Info", "Please enter a numerical interpolation time!", level=Qgis.Info)
                                return
                                
                        table_names=['line_s_t$'+str(i['connection_id']) for i in connTypeValues]
                        self.copy_string_iterator_sData(self.conn,file_data,id['id'],table_names,value_per_conn_seq,dlg,start_datetime,'linestring')

                    

    def copy_string_iterator_sData(self,connection, sdata,fid,table_names,value_per_conn_seq,dlg,start_datetime,mode) -> None:
        start_col_index=1
        end_col_index=1+value_per_conn_seq
        for table_name in table_names:
            max_id=getMaxIdSchema(self.cur,table_name,self.dictDB['versionName'])+1
            with connection.cursor() as cursor:
                mdata_string_iterator = StringIteratorIO((
                    '|'.join(map(clean_csv_value, (
                        int(row_counter*value_per_conn_seq+col_counter+max_id),
                        fid,
                        start_datetime+datetime.timedelta(hours=float(data[0])),
                        '',
                        int(col_counter+1),
                        cell
                    ))) + '\n'
                    for row_counter,data in enumerate(zip(sdata[:,0],sdata[:,int(start_col_index):int(end_col_index)])) for col_counter,cell in enumerate(data[1])
                ))
                cursor.copy_expert("COPY {}.{} FROM STDIN WITH (FORMAT csv, DELIMITER '|')".format(self.dictDB['versionName'],table_name),mdata_string_iterator)
            start_col_index=end_col_index
            end_col_index=start_col_index+value_per_conn_seq
            if mode=='linestring':
                sql="""UPDATE {}.{} r set geom = seg.geom 
    FROM (SELECT lid,lid_seg, geom FROM {}.line_seg) seg
    WHERE seg.lid=r.fid AND r.segment=seg.lid_seg;""".format(self.dictDB['versionName'],table_name,self.dictDB['versionName'])
                print(sql)
                self.cur.execute(sql)
            
    
    def openModel(self,dlg):
        print('-***-')
        if len([i for i in range(dlg.combo_submodels.count()) if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i)])==0:
            self.iface.messageBar().pushMessage("Info", "Please select one or more submodels!", level=Qgis.Info)
            return False
        self.requestedOutputs=loadRequestedOutputs(self.plugin_dir,self.dictDB)
        for i in range(dlg.combo_submodels.count()):
            if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i):        
                submodel=dlg.combo_submodels.itemText(i)
                print(submodel)
                dir=self.plugin_dir+'\\network_models\\{}\\{}\\'.format(self.dictDB['projectName'],self.dictDB['versionName'])
                fname=dir+'network_{}.idm'.format(submodel)
                print(fname)
                openModelCmd(loadIDADistrictsConfig(self.plugin_dir)['path_ice'],fname)


    def runModel(self,dlg):
        networkSimData=self.setNetworkSimData(dlg)
        if networkSimData:
            print('-***-')
            if len([i for i in range(dlg.combo_submodels.count()) if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i)])==0:
                self.iface.messageBar().pushMessage("Info", "Please select one or more submodels!", level=Qgis.Info)
                return False
            self.requestedOutputs=loadRequestedOutputs(self.plugin_dir,self.dictDB)
            self.invokedOutputs=loadInvokedOutputs(self.plugin_dir,self.dictDB)
            if self.checkSimOutputs():
                for i in range(dlg.combo_submodels.count()):
                    if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i):        
                        submodel=dlg.combo_submodels.itemText(i)
                        print(submodel)
                
                        print('----Update simulation data----')
                        dir=self.plugin_dir+'\\network_models\\{}\\{}\\'.format(self.dictDB['projectName'],self.dictDB['versionName'])
                        fname=dir+'network_{}.idm'.format(submodel)
                        print(fname)
                        print(getIDAListComponents(readFileToString(fname)))
                        components_idm=propertyListCompsIDM(getIDAListComponents(readFileToString(fname)))
                        
                        data_idm=[]
                        for comp in components_idm:
                            print(comp)
                            if getCompClass(comp)=='SIMULATION_DATA':
                                print('++++++++simulation data+++++++')
                                print(propertyListCompsIDM(getIDAListComponents(getSimData(self.requestedOutputs,networkSimData))))
                                data_idm.append(propertyListCompsIDM(getIDAListComponents(getSimData(self.requestedOutputs,networkSimData))))             
                            else:
                                data_idm.append(comp) 
                        
                        print(data_idm)
                        writePropertyListIDMToFile(data_idm,dir,fname)
                        writeSimulatedOutputs(self.plugin_dir,self.dictDB,self.requestedOutputs)
                        runSimulationCmd(loadIDADistrictsConfig(self.plugin_dir)['path_ice'],fname,submodel)
            else:
                self.iface.messageBar().pushMessage("Error", "The requested outputs differ from the invoked outputs. Please reinvoke the templates.", level=Qgis.Critical)

            closeDialog(dlg)  
    
    def checkSimOutputs(self):
        #check customers plants
        for type in ['dhc_customers','dhc_energy_plants']:
            for i in self.invokedOutputs['dhc_customers']:
                for j in self.invokedOutputs['dhc_customers'][i]:
                    if self.invokedOutputs['dhc_customers'][i][j]!=self.requestedOutputs[j]:
                        return False
        
        #check lines
        for i in self.invokedOutputs['dhc_lines']:
            if self.invokedOutputs['dhc_lines'][i]!=self.requestedOutputs[i]:
                return False
        
        return True
        
    def showModellingSettings(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        print(self.dictDB)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
            self.modellingSettings=loadModellingSettings(self.plugin_dir,self.dictDB)
            self.dlg_modellingSettings=ModellingSettings(self.plugin_dir,self.modellingSettings,self.cur)
            self.dlg_modellingSettings.btn_ok.clicked.connect(lambda: self.setModellingSettings(self.dlg_modellingSettings))
            self.dlg_modellingSettings.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_modellingSettings))
            self.dlg_modellingSettings.show()  
            
    def showSupervisoryCtrl(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        print(self.dictDB)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
            self.dlg_supervisoryCrtl=SupervisoryCtrlDlg(self.cur,self.dictDB)
            self.dlg_supervisoryCrtl.btn_ok.clicked.connect(lambda: self.setSupervisoryCrtlSubmodel(self.dlg_supervisoryCrtl))
            self.dlg_supervisoryCrtl.btn_open.clicked.connect(lambda: self.openSupervisoryCtrl())
            self.dlg_supervisoryCrtl.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_supervisoryCrtl))
            self.dlg_supervisoryCrtl.show()  
    
    def setSupervisoryCrtlSubmodel(self,dlg):
        sql="""UPDATE {}.supervisory_ctrl SET submodel={};""".format(self.dictDB['versionName'],dlg.combo_submodel.currentText())
        self.cur.execute(sql)
        closeDialog(dlg)
        
    def showFeatureDecoupling(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        print(self.dictDB)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
            self.dlg_featureDecoupling=FeatureDecouplingDlg(self.plugin_dir,self.cur,self.dictDB)
            self.dlg_featureDecoupling.btn_ok.clicked.connect(lambda: closeDialog(self.dlg_featureDecoupling))
            self.dlg_featureDecoupling.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_featureDecoupling))
            self.dlg_featureDecoupling.show()    
    
    def showInvokeFeatures(self):
        self.dictDB=getDBConnectionData(self.plugin_dir)
        InvokeFeatures(self.plugin_dir,self.dictDB,self.iface)
     
    def showBuildModel(self):
        """ Build IDA subnetwork models; loop over subnetworks"""
        print('Build IDA model')
        self.dictDB=getDBConnectionData(self.plugin_dir)
        self.conn=dbConnect(self.dictDB,False)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
            self.dlg_buildModel=BuildNetworkModelDialog()
            sql="""SELECT network FROM {}.dhc_lines GROUP BY network ORDER BY network;""".format(self.dictDB['versionName'])
            self.cur.execute(sql)
            self.dlg_buildModel.combo_network_models.addItem('Check all items')
            networks=self.cur.fetchall()
            self.dlg_buildModel.combo_network_models.addItems([str(i['network']) for i in networks])
            for i in range(len(networks)):
                self.dlg_buildModel.combo_network_models.setItemChecked(i+1,False)
            
            self.dlg_buildModel.combo_submodels.addItem('Check all items')
            submodels=getUsedSubmodels(self.cur,self.dictDB)
            self.dlg_buildModel.combo_submodels.addItems(submodels)
            for i in range(len(submodels)):
                self.dlg_buildModel.combo_submodels.setItemChecked(i+1,False)
            self.dlg_buildModel.show()
            self.dlg_buildModel.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_buildModel))
            self.dlg_buildModel.btn_buildNetworkModel.clicked.connect(lambda: self.buildModel(self.dlg_buildModel))
            
    def buildModel(self,dlg):
        networks=[]
        for i in range(dlg.combo_network_models.count()):
            if dlg.combo_network_models.itemText(i) != 'Check all items' and dlg.combo_network_models.itemChecked(i):        
                networks.append(dlg.combo_network_models.itemText(i))
                    
        print(networks)
        submodels=[dlg.combo_submodels.itemText(i) for i in range(dlg.combo_submodels.count()) if dlg.combo_submodels.itemText(i) != 'Check all items' and dlg.combo_submodels.itemChecked(i)]
        self.requestedOutputs=loadRequestedOutputs(self.plugin_dir,self.dictDB)
        self.modellingSettings=loadModellingSettings(self.plugin_dir,self.dictDB)
        self.networkSimData=loadNetworkSimData(self.plugin_dir,self.dictDB)
        InvokeNetworkModel(self.plugin_dir,self.requestedOutputs,self.modellingSettings,self.iface,networks,submodels,self.networkSimData,dlg.checkbox_reinvokeFeatures.checkState() == Qt.Checked)
        closeDialog(dlg)        
            
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = IDADistrictsModelingSimulationDialog()
            self.dlg.btn_requestedOutputs.clicked.connect(self.showRequestedOutputs)
            self.dlg.btn_custModelParm.clicked.connect(self.showCustomerParm)
            self.dlg.btn_supervisoryContr.clicked.connect(self.showSupervisoryCtrl)
            self.dlg.btn_calibrateCustomers.clicked.connect(self.calibrateCustomers)
            self.dlg.btn_invokeFeatures.clicked.connect(self.showInvokeFeatures)
            self.dlg.btn_modellingSettings.clicked.connect(self.showModellingSettings)
            self.dlg.btn_featureDecoupling.clicked.connect(self.showFeatureDecoupling)
            
            self.dlg.btn_buildModel.clicked.connect(self.showBuildModel)
            self.dlg.btn_openModel.clicked.connect(self.showOpenModel)
            self.dlg.btn_runModel.clicked.connect(self.showRunModel)
            self.dlg.btn_loadResults.clicked.connect(self.showLoadResults)

            # show the dialog
            self.dlg.show()
        else:
            self.dlg.show()
            self.dlg.activateWindow()
            print('activate')

