# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IDADistrictsModelingSimulationDialog
                                 A QGIS plugin
 This plugin does districts modeling and simulation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-29
        git sha              : $Format:%H$
        copyright            : (C) 2022 by EQUA
        email                : peter.nageler@equa.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.utils import iface
from plugins.utility_functions.dialog import *
from plugins.utility_functions.files import *
from plugins.utility_functions.db import *
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import QButtonGroup,QSpinBox,QShortcut,QListWidgetItem,QListWidget, QTabWidget, QTableWidgetItem,QTableWidget,QTreeView,QAction,QMainWindow,QWidget,QPushButton,QHBoxLayout,QVBoxLayout,QLabel,QLineEdit,QCheckBox,QComboBox, QProgressBar, QCheckBox,QRadioButton
from PyQt5 import QtCore
import psycopg2
import psycopg2.extras
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
from qgis.utils import iface
from qgis.core import Qgis
from PyQt5.QtGui import QKeySequence
import matplotlib.pyplot as plt



class RequestedOutputs(QMainWindow):
    def __init__(self,requestedOutputs):
        """Constructor."""
        super().__init__()
        self.setWindowTitle("Requested outputs") 
        
        #------------------Customers----------------------
        #titel
        label_customer_title =QLabel("Customers")
        font=label_customer_title.font()
        font.setPointSize(15)
        label_customer_title.setFont(font)
        self.requestedOutputs_old=requestedOutputs.copy()
        
        #checkbox for drop old features
        layout_customer_checkbox = QVBoxLayout()      
        
        self.checkBoxSubstationPower=QCheckBox("Substation power")
        if requestedOutputs['power_c']:
            self.checkBoxSubstationPower.setChecked(True)
        self.checkBoxSubstationConnTemp=QCheckBox("Substation connection temperatures")
        if requestedOutputs['temp_c']:
            self.checkBoxSubstationConnTemp.setChecked(True)
        self.checkBoxSubstationPressure=QCheckBox("Substation pressure")
        if requestedOutputs['p_c']:
            self.checkBoxSubstationPressure.setChecked(True)
        self.checkBoxSubstationMassflow=QCheckBox("Substation Massflow")
        if requestedOutputs['mdot_c']:
            self.checkBoxSubstationMassflow.setChecked(True)
        self.checkBoxSubstationHeatbalance=QCheckBox("Heat balance of the building")
        if requestedOutputs['heatbalance_c']:
            self.checkBoxSubstationHeatbalance.setChecked(True)
        self.checkBoxSubstationTair=QCheckBox("Room air temperature")
        if requestedOutputs['troom_c']:
            self.checkBoxSubstationTair.setChecked(True)
        layout_customer_checkbox.addWidget(self.checkBoxSubstationPower)
        layout_customer_checkbox.addWidget(self.checkBoxSubstationConnTemp)
        layout_customer_checkbox.addWidget(self.checkBoxSubstationPressure)
        layout_customer_checkbox.addWidget(self.checkBoxSubstationMassflow)
        layout_customer_checkbox.addWidget(self.checkBoxSubstationHeatbalance)
        layout_customer_checkbox.addWidget(self.checkBoxSubstationTair)
        
        #------------------Network----------------------
        #titel
        label_network_title =QLabel("Network")
        font=label_network_title.font()
        font.setPointSize(15)
        label_network_title.setFont(font)
        
        #checkboxes 
        layout_network_checkbox = QVBoxLayout()      
        print(requestedOutputs)
        self.checkBoxMdotNode=QCheckBox("Massflows in pipes")
        if requestedOutputs['mdot_lines']:
            self.checkBoxMdotNode.setChecked(True)
        self.checkBoxVPipe=QCheckBox("Velocity in pipes")
        if requestedOutputs['v_lines']:
            self.checkBoxVPipe.setChecked(True)
        self.checkBoxPressureDistribution=QCheckBox("Pressure distribution")
        if requestedOutputs['p_lines']:
            self.checkBoxPressureDistribution.setChecked(True)
        self.checkBoxTempPipe=QCheckBox("Temperature in pipes")
        if requestedOutputs['temp_lines']:
            self.checkBoxTempPipe.setChecked(True)
            
        layout_network_checkbox.addWidget(self.checkBoxPressureDistribution)
        layout_network_checkbox.addWidget(self.checkBoxMdotNode)
        layout_network_checkbox.addWidget(self.checkBoxVPipe)
        layout_network_checkbox.addWidget(self.checkBoxTempPipe)
        
        #------------------Energy plants----------------------
        #titel
        label_plants_title =QLabel("Energy plants")
        font=label_plants_title.font()
        font.setPointSize(15)
        label_plants_title.setFont(font)
        
        #checkbox for drop old features
        layout_plants_checkbox = QVBoxLayout()      
        
        self.checkBoxPlantPower=QCheckBox("Plant power")
        if requestedOutputs['power_ep']:
            self.checkBoxPlantPower.setChecked(True)
        self.checkBoxPlantConnTemp=QCheckBox("Plant connection temperatures")
        if requestedOutputs['temp_ep']:
            self.checkBoxPlantConnTemp.setChecked(True)
        self.checkBoxPlantPressure=QCheckBox("Plant pressure")
        if requestedOutputs['p_ep']:
            self.checkBoxPlantPressure.setChecked(True)
        self.checkBoxPlantMassflow=QCheckBox("Plant mass flow")
        if requestedOutputs['mdot_ep']:
            self.checkBoxPlantMassflow.setChecked(True)
        layout_plants_checkbox.addWidget(self.checkBoxPlantPower)
        layout_plants_checkbox.addWidget(self.checkBoxPlantConnTemp)
        layout_plants_checkbox.addWidget(self.checkBoxPlantPressure)
        layout_plants_checkbox.addWidget(self.checkBoxPlantMassflow)
        
        #------------------Supervisory control----------------------
        #titel
        label_supervisoryContr_title =QLabel("Supervisory control")
        font=label_supervisoryContr_title.font()
        font.setPointSize(15)
        label_supervisoryContr_title.setFont(font)
        
        #checkbox for drop old features
        layout_contr_checkbox = QVBoxLayout()      
        
        self.checkBoxSupervisoryCtrl=QCheckBox("Control signal")
        layout_contr_checkbox.addWidget(self.checkBoxSupervisoryCtrl)
        
        #------------------KPI`s----------------------
        #titel
        label_kpi_title =QLabel("KPI`s")
        font=label_kpi_title.font()
        font.setPointSize(15)
        label_kpi_title.setFont(font)
        
        #checkbox for drop old features
        layout_kpi_checkbox = QVBoxLayout()      
        
        self.checkBoxMeanSupplyTemp=QCheckBox("Mean supply temperature")
        layout_kpi_checkbox.addWidget(self.checkBoxMeanSupplyTemp)
        
        #timestep for output
        layout_outputTimestep = QHBoxLayout()      
        label_outputTimestep =QLabel("Timestep for output, h")
        self.outputTimestep=QLineEdit(requestedOutputs['dt_outputs'])
        layout_outputTimestep.addWidget(label_outputTimestep)
        layout_outputTimestep.addWidget(self.outputTimestep)
        
        #buttons     
        layout_buttons = QHBoxLayout()
        self.btn_ok=QPushButton("Ok")
        layout_buttons.addWidget(self.btn_ok)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addWidget(label_customer_title)
        layout_win.addLayout(layout_customer_checkbox)
        layout_win.addWidget(label_network_title)
        layout_win.addLayout(layout_network_checkbox)
        layout_win.addWidget(label_plants_title)
        layout_win.addLayout(layout_plants_checkbox)
        layout_win.addWidget(label_supervisoryContr_title)
        layout_win.addLayout(layout_contr_checkbox)
        layout_win.addWidget(label_kpi_title)
        layout_win.addLayout(layout_kpi_checkbox)
        layout_win.addLayout(layout_outputTimestep)
        layout_win.addLayout(layout_buttons)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
        self.shortcut = QShortcut(QKeySequence("Alt+F4"), self)
        self.shortcut.activated.connect(lambda : closeDialog(self))

class SupervisoryCtrlDlg(QMainWindow):
    def __init__(self,cur,dictDB):
        """Constructor."""
        super().__init__()
        self.setWindowTitle("Supervisory control") 
        
        #btn open
        self.btn_open=QPushButton("Open")
        
        #networks
        layout_submodel=QHBoxLayout()
        label_submodel =QLabel("Submodel")
        layout_submodel.addWidget(label_submodel)
        self.combo_submodel = QComboBox()
        submodels=getUsedSubmodels(cur,dictDB)
        self.combo_submodel.addItems(submodels)
        if getSupervisorySubmodel(cur,dictDB) in submodels:
            self.combo_submodel.setCurrentText(getSupervisorySubmodel(cur,dictDB))
        layout_submodel.addWidget(self.combo_submodel)
            
        #buttons     
        layout_buttons = QHBoxLayout()
        self.btn_ok=QPushButton("Ok")
        layout_buttons.addWidget(self.btn_ok)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addWidget(self.btn_open)
        layout_win.addLayout(layout_submodel)
        layout_win.addLayout(layout_buttons)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)

class BuildNetworkModelDialog(QMainWindow):
    def __init__(self):
        """Constructor."""
        super().__init__()
        self.setWindowTitle("Build network model") 
        
        #networks
        layout_networks=QVBoxLayout()
        label_networks =QLabel("Networks")
        font=label_networks.font()
        font.setPointSize(15)
        label_networks.setFont(font)
        self.combo_network_models = CheckableComboBox()
        layout_networks.addWidget(label_networks)
        layout_networks.addWidget(self.combo_network_models)
        
        #self.checkBoxCosim=QCheckBox("Apply decoupling")
        #self.checkBoxCosim.stateChanged.connect(self.cosim_state)
        self.label_submodels =QLabel("Submodels")
        self.label_submodels.setFont(font)
        #self.label_submodels.setHidden(True)
        #layout_networks.addWidget(self.checkBoxCosim)
        layout_networks.addWidget(self.label_submodels)
        self.combo_submodels = CheckableComboBox()
        #self.combo_submodels.setHidden(True)
        layout_networks.addWidget(self.combo_submodels)
        
        #reinvoke feature templates
        self.checkbox_reinvokeFeatures = QCheckBox("Reinvoke feature templates")
        self.checkbox_reinvokeFeatures.setChecked(True)
        
        #buttons     
        layout_buttons = QHBoxLayout()
        self.btn_buildNetworkModel=QPushButton("Build network model")
        layout_buttons.addWidget(self.btn_buildNetworkModel)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #progress bar
        self.progress=QProgressBar()
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addLayout(layout_networks)
        layout_win.addWidget(self.checkbox_reinvokeFeatures)
        layout_win.addLayout(layout_buttons)
        layout_win.addWidget(self.progress)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
                  
    def update_progress(self,progress):
        self.progress.setValue(progress)

class OpenNetworkModelDialog(QMainWindow):
    def __init__(self):
        """Constructor."""
        super().__init__()
        self.setWindowTitle("Open network submodels") 
        
        #submodels
        layout_submodels=QVBoxLayout()
        label_submodels =QLabel("Submodels")
        font=label_submodels.font()
        font.setPointSize(12)
        label_submodels.setFont(font)
        self.combo_submodels = CheckableComboBox()
        layout_submodels.addWidget(label_submodels)
        layout_submodels.addWidget(self.combo_submodels)
        
        #buttons     
        layout_buttons = QHBoxLayout()
        self.btn_openModel=QPushButton("Open network submodels")
        layout_buttons.addWidget(self.btn_openModel)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #progress bar
        self.progress=QProgressBar()
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addLayout(layout_submodels)
        layout_win.addLayout(layout_buttons)
        layout_win.addWidget(self.progress)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
        
    def update_progress(self,progress):
        self.progress.setValue(progress)
            
class LoadResultsDialog(QMainWindow):
    def __init__(self):
        """Constructor."""
        super().__init__()
        self.setWindowTitle("Load simulation results") 
        
        #submodels
        layout_submodels=QVBoxLayout()
        label_submodels =QLabel("Submodels")
        font=label_submodels.font()
        font.setPointSize(12)
        label_submodels.setFont(font)
        self.combo_submodels = CheckableComboBox()
        layout_submodels.addWidget(label_submodels)
        layout_submodels.addWidget(self.combo_submodels)
        
        #interpolate timestep
        layout_interpolation=QVBoxLayout()
        self.checkbox_timestep=QCheckBox('data interpolation, s')
        self.checkbox_timestep.stateChanged.connect(self.interpolation_dt_state)
        layout_interpolation.addWidget(self.checkbox_timestep)
        self.interpolation_dt=QLineEdit('')
        self.interpolation_dt.setHidden(True)
        layout_interpolation.addWidget(self.interpolation_dt)
        
        #buttons     
        layout_buttons = QHBoxLayout()
        self.btn_loadResults=QPushButton("Load results")
        layout_buttons.addWidget(self.btn_loadResults)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #progress bar
        self.progress=QProgressBar()
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addLayout(layout_submodels)
        layout_win.addLayout(layout_interpolation)
        layout_win.addLayout(layout_buttons)
        layout_win.addWidget(self.progress)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
        
    def interpolation_dt_state(self,s):
        if Qt.Checked==s:
            self.interpolation_dt.setHidden(False)
        else:
            self.interpolation_dt.setHidden(True)
    
    def update_progress(self,progress):
        self.progress.setValue(progress)

        
class RunNetworkModelDialog(QMainWindow):
    def __init__(self,plugin_dir,dictDB):
        """Constructor."""
        super().__init__()
        self.setWindowTitle("Run network submodels") 
        self.networkSimData=loadNetworkSimData(plugin_dir,dictDB)
        print(self.networkSimData)
        self.finished_sims=0
        
        #submodels
        layout_submodels=QVBoxLayout()
        label_submodels =QLabel("Submodels")
        font=label_submodels.font()
        font.setPointSize(12)
        label_submodels.setFont(font)
        self.combo_submodels = CheckableComboBox()
        layout_submodels.addWidget(label_submodels)
        layout_submodels.addWidget(self.combo_submodels)
        
        #------simulation------------
        layout_simtime=QVBoxLayout()
        label_simtime =QLabel("Simulation")
        font=label_simtime.font()
        font.setPointSize(12)
        label_simtime.setFont(font)
        
      
        #radio buttons calc type
        self.btngroup_calc_type = QButtonGroup()
        layout_rbtn_calc_type = QHBoxLayout()
        self.rbtn_calc_type_periodic = QRadioButton('Periodic')
        self.rbtn_calc_type_dynamic = QRadioButton('Dynamic')
        self.btngroup_calc_type.addButton(self.rbtn_calc_type_periodic)
        self.btngroup_calc_type.addButton(self.rbtn_calc_type_dynamic)
        layout_rbtn_calc_type.addWidget(self.rbtn_calc_type_periodic)
        layout_rbtn_calc_type.addWidget(self.rbtn_calc_type_dynamic)

        
        #maximal timestep
        layout_max_timestep = QHBoxLayout()
        label_max_timestep =QLabel("Maximal timestep, h")
        layout_max_timestep.addWidget(label_max_timestep)
        self.max_timestep=QLineEdit(self.networkSimData['max_timestep'])
        layout_max_timestep.addWidget(self.max_timestep)
        
        #startup time
        layout_startup = QVBoxLayout()
        self.label_startup =QLabel("Startup")
        font=self.label_startup.font()
        font.setPointSize(10)
        self.label_startup.setFont(font)
        layout_startupDate = QHBoxLayout()
        self.label_calcStartupFrom =QLabel("From")
        layout_startupDate.addWidget(self.label_calcStartupFrom)
        
        #radio buttons startup type
        self.btngroup_startup_type = QButtonGroup()
        layout_rbtn_startup_type = QHBoxLayout()
        self.rbtn_startup_type_periodic = QRadioButton('Periodic')
        self.rbtn_startup_type_dynamic = QRadioButton('Dynamic')
        self.btngroup_startup_type.addButton(self.rbtn_startup_type_periodic)
        self.btngroup_startup_type.addButton(self.rbtn_startup_type_dynamic)
        layout_rbtn_startup_type.addWidget(self.rbtn_startup_type_periodic)
        layout_rbtn_startup_type.addWidget(self.rbtn_startup_type_dynamic)
        
        self.dateedit_startupFrom = QtWidgets.QDateTimeEdit(calendarPopup=True)
        if self.networkSimData['startup_time_from']:
            date_time=self.networkSimData['startup_time_from']
        else:
            date_time=str(QtCore.QDate.currentDate().year())+'-01-01 00:00:00'
        self.dateedit_startupFrom.setDateTime(QtCore.QDateTime.fromString(date_time, 'yyyy-MM-dd hh:mm:ss'))
        self.dateedit_startupFrom.setDisplayFormat("yyyy-MM-dd hh:mm:ss")
        layout_startupDate.addWidget(self.dateedit_startupFrom)

        self.label_calcStartupTo =QLabel("To")
        layout_startupDate.addWidget(self.label_calcStartupTo)
                
        self.dateedit_startupTo = QtWidgets.QDateTimeEdit(calendarPopup=True)
        if self.networkSimData['startup_time_to']:
            date_time=self.networkSimData['startup_time_to']
        else:
            date_time=str(QtCore.QDate.currentDate().year())+'-12-31 23:59:59'
        self.dateedit_startupTo.setDateTime(QtCore.QDateTime.fromString(date_time, 'yyyy-MM-dd hh:mm:ss'))
        self.dateedit_startupTo.setDisplayFormat("yyyy-MM-dd hh:mm:ss")
        layout_startupDate.addWidget(self.dateedit_startupTo)

        layout_startup.addWidget(self.label_startup)
        layout_startup.addLayout(layout_rbtn_startup_type)
        layout_startup.addLayout(layout_startupDate)

        #number of periods
        layout_numb_periods = QHBoxLayout()
        self.label_numb_periods =QLabel("Number of periods")
        layout_numb_periods.addWidget(self.label_numb_periods)    
        self.numb_periods =QSpinBox()
        self.numb_periods.setValue(int(self.networkSimData['numb_of_periods']))
        self.numb_periods.setMinimum(1) 
        layout_numb_periods.addWidget(self.numb_periods)        

        #simulation time
        layout_calctime = QVBoxLayout()
        label_calctime =QLabel("Simulation time")
        font=label_calctime.font()
        font.setPointSize(12)
        label_calctime.setFont(font)
        
        layout_calcdate = QHBoxLayout()
        label_calcFrom =QLabel("From")
        layout_calcdate.addWidget(label_calcFrom)
                
        self.dateedit_calcFrom = QtWidgets.QDateTimeEdit(calendarPopup=True)
        if self.networkSimData['calc_time_from']:
            print(self.networkSimData['calc_time_from'])
            date_time=self.networkSimData['calc_time_from']
        else:
            date_time=str(QtCore.QDate.currentDate().year())+'-01-01 00:00:00'
        self.dateedit_calcFrom.setDateTime(QtCore.QDateTime.fromString(date_time, 'yyyy-MM-dd hh:mm:ss'))
        self.dateedit_calcFrom.setDisplayFormat("yyyy-MM-dd hh:mm:ss")
        layout_calcdate.addWidget(self.dateedit_calcFrom)

        label_calcTo =QLabel("To")
        layout_calcdate.addWidget(label_calcTo)
                
        self.dateedit_calcTo = QtWidgets.QDateTimeEdit(calendarPopup=True)
        if self.networkSimData['calc_time_to']:
            print(self.networkSimData['calc_time_to'])
            date_time=self.networkSimData['calc_time_to']
        else:
            date_time=str(QtCore.QDate.currentDate().year())+'-12-31 23:59:59'
        self.dateedit_calcTo.setDateTime(QtCore.QDateTime.fromString(date_time, 'yyyy-MM-dd hh:mm:ss'))
        self.dateedit_calcTo.setDisplayFormat("yyyy-MM-dd hh:mm:ss")
        layout_calcdate.addWidget(self.dateedit_calcTo)
        
        layout_calctime.addWidget(label_calctime)
        layout_calctime.addLayout(layout_calcdate)
                
        layout_simtime.addWidget(label_simtime)
        layout_simtime.addLayout(layout_max_timestep)
        layout_simtime.addLayout(layout_rbtn_calc_type)
        layout_simtime.addLayout(layout_startup)
        layout_simtime.addLayout(layout_numb_periods)
        layout_simtime.addLayout(layout_calctime)
        
        #status bar
        self.status_bar = self.statusBar()
        self.status_bar.setStyleSheet("""
    QStatusBar {
                background-color: white;
                color: black;
                border-radius: 5px;
                border: 1px solid grey;
            }
""")
        self.status_bar.showMessage("Ready")
        
        #buttons     
        layout_buttons = QHBoxLayout()
        self.btn_runModel=QPushButton("Run network submodels")
        layout_buttons.addWidget(self.btn_runModel)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addLayout(layout_submodels)
        layout_win.addLayout(layout_simtime)
        layout_win.addLayout(layout_buttons)
        layout_win.addWidget(self.status_bar)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
        
        self.rbtn_calc_type_periodic.toggled.connect(self.onClickedRadioCalcType)
        self.rbtn_calc_type_dynamic.toggled.connect(self.onClickedRadioCalcType)
        self.rbtn_startup_type_periodic.toggled.connect(self.onClickedRadioStartupType)
        self.rbtn_startup_type_dynamic.toggled.connect(self.onClickedRadioStartupType)
        if self.networkSimData['calc_type']=='periodic':
            self.rbtn_calc_type_periodic.setChecked(True)
        else:
            self.rbtn_calc_type_dynamic.setChecked(True)
        if self.networkSimData['startup_type']=='periodic':
            self.rbtn_startup_type_periodic.setChecked(True)
        else:
            self.rbtn_startup_type_dynamic.setChecked(True)
        
    def onClickedRadioCalcType(self,s):
        print(s)
        
        if self.rbtn_calc_type_dynamic.isChecked():
            self.label_startup.setHidden(False)
            self.label_calcStartupFrom.setHidden(False)
            self.dateedit_startupFrom.setHidden(False)
            self.label_calcStartupTo.setHidden(False)
            self.dateedit_startupTo.setHidden(False)
            self.rbtn_startup_type_dynamic.setHidden(False)    
            self.rbtn_startup_type_periodic.setHidden(False)  
            if self.rbtn_startup_type_dynamic.isChecked():
                self.numb_periods.setHidden(True)
                self.label_numb_periods.setHidden(True)
                
        else:
            self.label_startup.setHidden(True)
            self.label_calcStartupFrom.setHidden(True)
            self.dateedit_startupFrom.setHidden(True)
            self.label_calcStartupTo.setHidden(True)
            self.dateedit_startupTo.setHidden(True)
            self.rbtn_startup_type_dynamic.setHidden(True)    
            self.rbtn_startup_type_periodic.setHidden(True) 
            self.label_numb_periods.setHidden(False)
            self.numb_periods.setHidden(False)    

    def onClickedRadioStartupType(self,s):
        print(s)
        if self.rbtn_startup_type_dynamic.isChecked():
            self.label_calcStartupFrom.setHidden(False)
            self.dateedit_startupFrom.setHidden(False)
            self.label_calcStartupTo.setHidden(False)
            self.dateedit_startupTo.setHidden(False)
            if self.rbtn_calc_type_dynamic.isChecked():
                self.label_numb_periods.setHidden(True)
                self.numb_periods.setHidden(True)
        else:
            self.label_numb_periods.setHidden(False)
            self.numb_periods.setHidden(False)
            
    def updateStatusBar(self,message):
        print(f"signal:{message}")
        if message=="Simulation finished" and self.statusBar().currentMessage()!="Simulation failed":
            self.finished_sims+=1
            print(f'finished_sims: {self.finished_sims}; n_sims: {self.n_sims}')
            if self.finished_sims==self.n_sims:
                self.status_bar.showMessage(message) 
        else:
            self.status_bar.showMessage(message)
    
    def show_error_message(self,message):
        iface.messageBar().pushMessage("Error", message, level=Qgis.Critical)
        self.status_bar.showMessage("Simulation failed")
        
class CalibrateCustomers(QMainWindow):
    def __init__(self,dictDB,conn):
        """Constructor."""
        super().__init__()
        self.setWindowTitle("Customer model calibration") 
        self.cur=conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)          
        
        #radio buttons devices/plants
        layout_rbtn = QHBoxLayout()
        self.rbtn_annualConumtion = QRadioButton('Use annual consumption data')
        self.rbtn_annualConumtion.setChecked(True)
        #self.rbtn_loadProfile = QRadioButton('Use load profile')
           
        layout_rbtn.addWidget(self.rbtn_annualConumtion)
        #layout_rbtn.addWidget(self.rbtn_loadProfile)
        
        #table templates
        layout_templates = QVBoxLayout()
        label_templates_title =QLabel("Templates")
        font=label_templates_title.font()
        font.setPointSize(15)
        label_templates_title.setFont(font)
        layout_templates.addWidget(label_templates_title)

        self.btn_openTemplate=QPushButton("Open Parametric Run")
        layout_templates.addWidget(self.btn_openTemplate)
        
        self.tableWidget_templates = QTableWidget(0,5)   
        self.tableWidget_templates.setHorizontalHeaderLabels(["Id","Asset type name","Asset group","Parametric Runs","Used"]) 
        layout_templates.addWidget(self.tableWidget_templates)
        
        #table select customers
        layout_selectCustomers = QVBoxLayout()
        label_selCust_title =QLabel("Customers")
        font=label_selCust_title.font()
        font.setPointSize(15)
        label_selCust_title.setFont(font)
        layout_selectCustomers.addWidget(label_selCust_title)
        self.tableWidget_customer = QTableWidget(0,4)   
        self.tableWidget_customer.setHorizontalHeaderLabels(["ID","Asset type name","Asset group","Parametric Runs"]) 
        layout_selectCustomers.addWidget(self.tableWidget_customer)

        #Results
        layout_results = QVBoxLayout()
        label_results_title =QLabel("Results (sorted by leftmost output parameter)")
        font=label_results_title.font()
        font.setPointSize(15)
        label_results_title.setFont(font)
        layout_results.addWidget(label_results_title)
        
        
        self.tabwidget = QTabWidget()
        layout_results.addWidget(self.tabwidget)
        
    
        #buttons     
        layout_buttons = QHBoxLayout()
        self.btn_startCallibration=QPushButton("Callibrate selected customers")
        layout_buttons.addWidget(self.btn_startCallibration)
        self.btn_showCallibCust=QPushButton("Open selected results")
        layout_buttons.addWidget(self.btn_showCallibCust)
        self.btn_saveCallibration=QPushButton("Save selected results/Invoke customers")
        layout_buttons.addWidget(self.btn_saveCallibration)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addLayout(layout_rbtn)
        layout_win.addLayout(layout_templates)
        layout_win.addLayout(layout_selectCustomers)
        layout_win.addLayout(layout_results)
        layout_win.addLayout(layout_buttons)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
        
class CustomerModelParmDlg(QMainWindow):
    def __init__(self):
        """Constructor."""
        super().__init__()
        self.setWindowTitle("Customer model parameter mapping") 
        
        layout_list=QHBoxLayout()
        #list widget for layer attributes
        layout_listWidget_customerFields = QVBoxLayout()
        label_listWidget_customerFields=QLabel("Fields of customers:")
        layout_listWidget_customerFields.addWidget(label_listWidget_customerFields)
        self.listWidget_customerFields = QListWidget()
        layout_listWidget_customerFields.addWidget(self.listWidget_customerFields)
        self.listWidget_customerFields.itemDoubleClicked.connect(self.mapAttributesDoubleClick)
        
        label_list_helptext=QLabel('Info: Double click on the \nfield in order to map it to \nthe selected mapping expression.\nYou can use also dictionaries in the form: {key: entry}[value/attribut]')
        layout_list.addLayout(layout_listWidget_customerFields)
        layout_list.addWidget(label_list_helptext)
       
        #table for mapped attributes  
        self.tableWidget_parameters = QTableWidget(0,5)   
        self.tableWidget_parameters.setHorizontalHeaderLabels(['Mapping expression','Mapping direction','Parameter name','Model name','Macro name'])
        
        #---------------ok/cancel buttons     
        layout_buttons_conns = QHBoxLayout()
        self.btn_add=QPushButton("Add")
        layout_buttons_conns.addWidget(self.btn_add)
        self.btn_remove=QPushButton("Remove")
        layout_buttons_conns.addWidget(self.btn_remove)
        
        #---------------ok/cancel buttons     
        layout_buttons = QHBoxLayout()
        self.btn_ok=QPushButton("Ok")
        layout_buttons.addWidget(self.btn_ok)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addLayout(layout_list)
        layout_win.addWidget(self.tableWidget_parameters)
        layout_win.addLayout(layout_buttons_conns)
        layout_win.addLayout(layout_buttons)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
        
    def mapAttributesDoubleClick(self,s):
        table_index=self.tableWidget_parameters.currentRow()
        if table_index!=-1:
            self.tableWidget_parameters.setItem(table_index,0,QTableWidgetItem(self.tableWidget_parameters.item(table_index,0).text()+'|'+s.text()+'|'))
        else:
            iface.messageBar().pushMessage("Info", "No model parameter selected!", level=Qgis.Info)

class FeatureDecouplingDlg(QMainWindow):
    def __init__(self,plugin_dir,cur,dictDB):
        """List the feature model names, which belongs to network side in decoupling mode"""
        super().__init__()
        self.cur=cur
        self.dictDB=dictDB
        self.setWindowTitle("Feature decoupling")   

        #Radio buttons customers, plants
        layout_rbtn = QHBoxLayout()
        self.rbtn_customers = QRadioButton('Customers')
        self.rbtn_customers.setChecked(True)
        self.rbtn_plants = QRadioButton('Energy plants')
        self.rbtn_customers.toggled.connect(self.onClickedRadio)
        self.rbtn_plants.toggled.connect(self.onClickedRadio)
        layout_rbtn.addWidget(self.rbtn_customers)
        layout_rbtn.addWidget(self.rbtn_plants)

        #Number of feature submodels
        layout_no_submodels = QHBoxLayout()
        label_no_submodels =QLabel("Number of decoupled feature submodels (Equal count of feature per submodel if set): ")
        layout_no_submodels.addWidget(label_no_submodels)
        self.no_submodels = QLineEdit()
        layout_no_submodels.addWidget(self.no_submodels)
        
        #combo templates
        self.feature_template = QComboBox()
        self.feature_template.currentIndexChanged.connect(self.onClickedTemplate)
        
        #label list
        label_list =QLabel("Component names, which belongs to the network side in decoupling mode")
        
        #list model names
        self.listWidget_featureModels = QListWidget()
        
        #buttons add/delete
        #table buttons     
        layout_buttons_action = QHBoxLayout()
        self.btn_add=QPushButton("Add")
        self.btn_add.clicked.connect(self.addListItem)
        layout_buttons_action.addWidget(self.btn_add)
        self.btn_delete=QPushButton("Delete")
        self.btn_delete.clicked.connect(self.removeSel)
        layout_buttons_action.addWidget(self.btn_delete)
                       
        #---------------ok/cancel buttons     
        layout_buttons = QHBoxLayout()
        self.btn_ok=QPushButton("Ok")
        layout_buttons.addWidget(self.btn_ok)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        self.btn_save=QPushButton("Save/Update")
        self.btn_save.clicked.connect(self.saveListContent)
        layout_buttons.addWidget(self.btn_save)
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addLayout(layout_rbtn)
        layout_win.addLayout(layout_no_submodels)
        layout_win.addWidget(self.feature_template)
        layout_win.addWidget(label_list)
        layout_win.addWidget(self.listWidget_featureModels)
        layout_win.addLayout(layout_buttons_action)
        layout_win.addLayout(layout_buttons) 
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
        self.onClickedRadio('')
        self.no_submodels.setText(str(len([i for i in getFeatureSubmodels(self.cur,self.dictDB,'customer' if self.rbtn_customers.isChecked() else 'energy_plant') if i not in getLineSubmodels(self.cur,self.dictDB)])))

    def addListItem(self):
        item=QListWidgetItem()
        item.setFlags(item.flags() | QtCore.Qt.ItemIsEditable)
        self.listWidget_featureModels.insertItem(0, item)    
        
    def onClickedRadio(self,s):
        print(s)
        self.listWidget_featureModels.clear()
        self.feature_template.clear()
        
        if self.rbtn_customers.isChecked():
            sql="""SELECT c_at.assettype,c_at.assettype_name,c_at.assetgroup,c_ag.assetgroup AS assetgroup_name, c_at.assettype_name||'('||c_ag.assetgroup||')' AS list_name
    FROM customer_assettypes c_at, customer_assetgroups c_ag WHERE c_at.assetgroup=c_ag.id ORDER BY c_at.assettype;"""
        else:
            sql="""SELECT ep_at.assettype,ep_at.assettype_name,ep_at.assetgroup,ep_ag.assetgroup AS assetgroup_name, ep_at.assettype_name||'('||ep_ag.assetgroup||')' AS list_name
    FROM energy_plant_assettypes ep_at, energy_plant_assetgroups ep_ag WHERE ep_at.assetgroup=ep_ag.id ORDER BY ep_at.assettype;"""
        print(sql)
        self.cur.execute(sql)
        self.feature_template.addItems([i['list_name'] for i in self.cur.fetchall()])

    def onClickedTemplate(self,s):
        print(s)
        self.listWidget_featureModels.clear()
        if self.rbtn_customers.isChecked():
            sql="""SELECT f_dec.comp_name
    FROM customer_assettypes c_at, customer_assetgroups c_ag, {}.feature_decoupling f_dec
    WHERE c_at.assetgroup=c_ag.id AND c_at.assettype_name||'('||c_ag.assetgroup||')'='{}' AND f_dec.assetgroup=c_at.assetgroup AND f_dec.assettype=c_at.assettype;
""".format(self.dictDB['versionName'],self.feature_template.itemText(s))
        else:
            sql="""SELECT f_dec.comp_name
    FROM energy_plant_assettypes ep_at, customer_assetgroups ep_ag, {}.feature_decoupling f_dec
    WHERE ep_at.assetgroup=ep_ag.id AND ep_at.assettype_name||'('||ep_ag.assetgroup||')'='{}' AND f_dec.assetgroup=ep_at.assetgroup AND f_dec.assettype=ep_at.assettype;
""".format(self.dictDB['versionName'],self.feature_template.itemText(s))
        print(sql)
        self.cur.execute(sql)
        self.listWidget_featureModels.addItems([i['comp_name'] for i in self.cur.fetchall()])
        
    def saveListContent(self):
        print('Save list conetent')
        if self.rbtn_customers.isChecked():
            type='customer'
        else:
            type='energy_plant'
        assetgroup=self.feature_template.currentText().split('(')[1][:-1]
        sql="""SELECT id FROM public.{}_assetgroups WHERE assetgroup='{}';""".format(type,assetgroup)
        print(sql)
        self.cur.execute(sql)
        assetgroup_id=self.cur.fetchone()['id']
        print(assetgroup_id)
        assettype=self.feature_template.currentText().split('(')[0]
        sql="""SELECT assettype FROM public.{}_assettypes WHERE assettype_name='{}';""".format(type,assettype)
        print(sql)
        self.cur.execute(sql)
        assettype_id=self.cur.fetchone()['assettype']
        print(assettype_id)
        
        sql="""DELETE FROM {}.feature_decoupling WHERE assetgroup ={} AND assettype={};\n""".format(self.dictDB['versionName'],assetgroup_id,assettype_id)
        sql+='\n'.join(["""INSERT INTO {}.feature_decoupling (assetgroup,assettype,comp_name,type) VALUES ({},{},'{}','{}');""".format(self.dictDB['versionName'],assetgroup_id,assettype_id,self.listWidget_featureModels.item(i).text(),type) for i in range(self.listWidget_featureModels.count())])

        try:
            no_submodels=int(self.no_submodels.text())
            self.cur.execute("SELECT row_number() OVER(ORDER BY id) enum, id FROM {}.{}s;".format(self.dictDB['versionName'],type))
            f_ids=self.cur.fetchall()
            submodel_counter=(getLineNetworks(self.cur,self.dictDB)[-1] if getLineNetworks(self.cur,self.dictDB) else 0)
            if no_submodels>0:
                self.cur.execute('SELECT count(*) AS count FROM {}.{}s;'.format(self.dictDB['versionName'],type))
                no_features=self.cur.fetchone()['count']
                f_per_submodel=int(no_features/no_submodels)
                rest=no_features%no_submodels
                                
                for f_id in f_ids:
                    if f_id['enum']>submodel_counter*f_per_submodel+(no_features%no_submodels-rest+1 if rest>0 else no_features%no_submodels):
                        submodel_counter+=1
                        rest-=1
                    sql+="UPDATE {}.{}s SET submodel={} WHERE id={};".format(self.dictDB['versionName'],type,submodel_counter+1,f_id['id'])
            elif no_submodels==0:
                sql+="UPDATE {}.{}s f SET submodel = s_m.submodel::int FROM (SELECT * FROM {}.submodels) s_m WHERE ST_DWithin(s_m.geom,f.geom,0.001);".format(self.dictDB['versionName'],type,self.dictDB['versionName'])
            else:
                iface.messageBar().pushMessage("Error", "Please enter a positive integer number in number of feature submodels!", level=Qgis.Critical)
        except:
           pass

        
        print(sql)
        if sql:
            self.cur.execute(sql)
            
    def removeSel(self):
        listItems=self.listWidget_featureModels.selectedItems()
        if not listItems: 
            return        
        for item in listItems:
            self.listWidget_featureModels.takeItem(self.listWidget_featureModels.row(item))

class IDADistrictsModelingSimulationDialog(QMainWindow):
    def __init__(self):
        """Constructor."""
        super().__init__()
        self.setWindowTitle("IDA Districts Modeling & Simulation")    
        
        #-------------Settings---------------
        #titel
        label_settings_title =QLabel("Settings")
        font=label_settings_title.font()
        font.setPointSize(15)
        label_settings_title.setFont(font)
        
        layout_modeling_settings = QVBoxLayout() 
        
        self.btn_requestedOutputs=QPushButton("Requested outputs")
        layout_modeling_settings.addWidget(self.btn_requestedOutputs)
        
        self.btn_modellingSettings=QPushButton("Modelling settings")
        layout_modeling_settings.addWidget(self.btn_modellingSettings)
        
        #set settings layout together
        layout_settings = QVBoxLayout()
        layout_settings.addWidget(label_settings_title)
        layout_settings.addLayout(layout_modeling_settings)
        
        
        #-------------Modeling---------------
        #titel
        label_modeling_title =QLabel("Modeling")
        font=label_modeling_title.font()
        font.setPointSize(15)
        label_modeling_title.setFont(font)
               
        #model buttons
        layout_modeling_btn = QVBoxLayout()   
        
        self.btn_custModelParm=QPushButton("Customer model parameter mapping")
        layout_modeling_btn.addWidget(self.btn_custModelParm)

        self.btn_supervisoryContr=QPushButton("Supervisory control")
        layout_modeling_btn.addWidget(self.btn_supervisoryContr)
        
        self.btn_calibrateCustomers=QPushButton("Calibrate customer models")
        layout_modeling_btn.addWidget(self.btn_calibrateCustomers)
        
        
        self.btn_invokeFeatures=QPushButton("Invoke feature models from templates")
        layout_modeling_btn.addWidget(self.btn_invokeFeatures)

        self.btn_featureDecoupling=QPushButton("Feature decoupling")
        layout_modeling_btn.addWidget(self.btn_featureDecoupling)
        
        layout_model_btn = QHBoxLayout()      
        
        self.btn_buildModel=QPushButton("Build model")
        layout_model_btn.addWidget(self.btn_buildModel)
        
        self.btn_openModel=QPushButton("Open model")
        layout_model_btn.addWidget(self.btn_openModel)
        
        
        #set modeling layout together
        layout_modeling = QVBoxLayout()
        layout_modeling.addWidget(label_modeling_title)
        layout_modeling_btn.addLayout(layout_model_btn)
        layout_modeling.addLayout(layout_modeling_btn)
        
        #-------------Simulation---------------
        #titel
        label_simulation_title =QLabel("Simulation")
        font=label_simulation_title.font()
        font.setPointSize(15)
        label_simulation_title.setFont(font)
        
        #buttons
        layout_simulation_btn = QHBoxLayout()      
        
        self.btn_runModel=QPushButton("Run model")
        layout_simulation_btn.addWidget(self.btn_runModel)
        
        self.btn_loadResults=QPushButton("Load results")
        layout_simulation_btn.addWidget(self.btn_loadResults)
        
        
        #set modeling layout together
        layout_simulation = QVBoxLayout()
        layout_simulation.addWidget(label_simulation_title)
        layout_simulation.addLayout(layout_simulation_btn)
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addLayout(layout_settings)
        layout_win.addLayout(layout_modeling)
        layout_win.addLayout(layout_simulation)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
        self.addShortCuts()
        
    def addShortCuts(self):
        self.shortcut_closeForm = QShortcut(QKeySequence("Alt+F4"), self)
        self.shortcut_closeForm.activated.connect(lambda : closeDialog(self))

class InvokeFeaturesDlg(QMainWindow):
    def __init__(self):
        """Constructor."""
        super().__init__()
        self.setWindowTitle("Invoke feature models from template")
        self.type=""        
        
        #-------------Invoke---------------
               
        #invoke buttons       
        layout_invoke_btn = QHBoxLayout()      
        
        self.btn_invokeOne=QPushButton("Invoke selected feature")
        layout_invoke_btn.addWidget(self.btn_invokeOne)
        
        self.btn_invokeAll=QPushButton("Invoke all features")
        layout_invoke_btn.addWidget(self.btn_invokeAll)
        
        #radio buttons devices/plants
        layout_rbtn = QHBoxLayout()
        self.rbtn_customers = QRadioButton('Customers')
        self.rbtn_customers.setChecked(True)
        self.rbtn_plants = QRadioButton('Energy plants')
        self.rbtn_devices = QRadioButton('Devices')  
           
        layout_rbtn.addWidget(self.rbtn_customers)
        layout_rbtn.addWidget(self.rbtn_plants)
        layout_rbtn.addWidget(self.rbtn_devices)
        
        #table
        self.tableWidget_customer = QTableWidget(0,2)   
        self.tableWidget_customer.setHorizontalHeaderLabels(["Id","Invoked"])      

        #---------------ok/Open buttons     
        layout_buttons = QHBoxLayout()
        self.btn_ok=QPushButton("Ok")
        layout_buttons.addWidget(self.btn_ok)
        self.btn_openInvoked=QPushButton("Open invoked feature")
        layout_buttons.addWidget(self.btn_openInvoked)      
        self.btn_simulateInvoked=QPushButton("Simulate invoked features")
        layout_buttons.addWidget(self.btn_simulateInvoked)      
        self.btn_showFeatureLoad=QPushButton("Plot selected features load/energy")
        layout_buttons.addWidget(self.btn_showFeatureLoad)    

        #progress bar
        self.progress=QProgressBar()        
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addLayout(layout_invoke_btn)
        layout_win.addLayout(layout_rbtn)
        layout_win.addWidget(self.tableWidget_customer)
        layout_win.addLayout(layout_buttons)
        layout_win.addWidget(self.progress)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
                
        
    def show_error_message(self, message):
        # Show the error message in a messageBar
        iface.messageBar().pushMessage("Error", message, level=Qgis.Critical)
        
    def update_progress(self,progress):
        self.progress.setValue(progress)

    def show_plots(self,plot):
        if plot:
            self.ax.set_title('Load profiles {}'.format(self.type))
            self.ax2.set_title('Cumulated energy {}'.format(self.type))
            self.ax.set_xlabel('Time, h')
            self.ax2.set_xlabel('Time, h')
            self.ax.set_ylabel('Power, W')
            self.ax2.set_ylabel('Energy, kWh')
        
            self.fig.legend()
            self.fig2.legend()
            self.fig.show()            
            self.fig2.show()  
        
    def plot_data(self, data):
        # Plotting in the main thread, which is non-blocking
        time=data[0]['time']
        valuesPowerInt=data[0]['data']
        label=data[0]['label']
        self.ax.plot(time, valuesPowerInt,label=label)
        time=data[1]['time']
        valuesEnergyInt=data[1]['data']
        label=data[1]['label']
        self.ax2.plot(time, valuesEnergyInt,label=label)
        
    def plot_total_data(self, data):
        try:
            fig1, ax1 = plt.subplots(layout='constrained')
            time=data[0]['time']
            power_sum=data[0]['data']
            ax1.plot(time, power_sum, label='Total power, W')
            time=data[1]['time']
            energy_sum=data[1]['data']
            ax1.plot(time, energy_sum, label='Total energy, kWh')
            ax1.set_title('Total load profiles')
            plt.legend()
            fig1.show()
        except:
            pass

#dublicated code
class ComboBox(QComboBox):
    popupAboutToBeShown = QtCore.pyqtSignal()

    def showPopup(self):
        self.popupAboutToBeShown.emit()
        super(ComboBox, self).showPopup()
        
class ModellingSettings(QMainWindow):
    def __init__(self,plugin_dir,modellingSettings,cur):
        """Constructor."""
        super().__init__()
        self.setWindowTitle("Modelling settings")    
        self.plugin_dir=plugin_dir
        self.cur=cur
        #-------------Settings FD pipe ---------------
        #titel
        label_fd_pipe_title =QLabel("Finite difference pipe model")
        font=label_fd_pipe_title.font()
        font.setPointSize(15)
        label_fd_pipe_title.setFont(font)
        
        #labels
        layout_fd_pipe_label = QVBoxLayout()
        
        label_fd_pipe_discretization =QLabel("Meter per node ")
        layout_fd_pipe_label.addWidget(label_fd_pipe_discretization)
        
        #values
        layout_fd_pipe_value = QVBoxLayout()
        
        self.fd_meterPerNode = QLineEdit(modellingSettings['fd_meterPerNode'])
        layout_fd_pipe_value.addWidget(self.fd_meterPerNode) 
        
        #set labes & values together
        layout_fd_pipe = QHBoxLayout() 
        layout_fd_pipe.addLayout(layout_fd_pipe_label)
        layout_fd_pipe.addLayout(layout_fd_pipe_value)     

        #-------------Settings node model---------------
        #titel
        label_node_title =QLabel("Node model")
        font=label_node_title.font()
        font.setPointSize(15)
        label_node_title.setFont(font)
        
        #labels
        layout_node_label = QVBoxLayout()
        
        label_node_vol =QLabel("Node volume, m3 ")
        layout_node_label.addWidget(label_node_vol)
        
        #values
        layout_node_value = QVBoxLayout()
        
        self.node_vol = QLineEdit(modellingSettings['node_vol'])
        layout_node_value.addWidget(self.node_vol) 
        
        #set labes & values together
        layout_node = QHBoxLayout() 
        layout_node.addLayout(layout_node_label)
        layout_node.addLayout(layout_node_value)     
        
        #-------------Ambient settings---------------
        #titel
        label_ambient_title =QLabel("Ambient temperatur settings")
        font=label_ambient_title.font()
        font.setPointSize(15)
        label_ambient_title.setFont(font)
        
        #titel
        label_ground_title =QLabel("Ground temperatur")
        font=label_ground_title.font()
        font.setPointSize(12)
        label_ground_title.setFont(font)
        
        #labels
        layout_ground_label = QVBoxLayout()
        
        label_ground_model =QLabel("Ground model:")
        layout_ground_label.addWidget(label_ground_model)
        
        
        self.label_amb_kusuda_tsurfmean =QLabel("Annual mean temperature, °C:")
        layout_ground_label.addWidget(self.label_amb_kusuda_tsurfmean)
        
        self.label_amb_kusuda_tsurfampl =QLabel("Daily mean temperature amplitude, K:")
        layout_ground_label.addWidget(self.label_amb_kusuda_tsurfampl)
        
        self.label_amb_kusuda_theta =QLabel("Phase shift of monthly minimum temperatur, days:")
        layout_ground_label.addWidget(self.label_amb_kusuda_theta)
        
        self.label_amb_kusuda_rho =QLabel("Ground density, kg/m3:")
        layout_ground_label.addWidget(self.label_amb_kusuda_rho)
        
        self.label_amb_kusuda_cp =QLabel("Specific heat capacity of the ground, J/(kg*K):")
        layout_ground_label.addWidget(self.label_amb_kusuda_cp)
        
        self.label_amb_kusuda_lambda =QLabel("Thermal conductivity of the ground, W/(k*K):")
        layout_ground_label.addWidget(self.label_amb_kusuda_lambda)
        
        self.label_amb_kusuda_depth =QLabel("Depth below the surface, m:")
        layout_ground_label.addWidget(self.label_amb_kusuda_depth)
        
        
        self.label_amb_ground_profile =QLabel("Ground temperatur timeseries:")
        layout_ground_label.addWidget(self.label_amb_ground_profile)
        
        
        self.label_amb_ground_temp =QLabel("Constant ground temperatur:")
        layout_ground_label.addWidget(self.label_amb_ground_temp)
        
        #values
        layout_ground_value = QVBoxLayout()
        
        self.amb_ground_model = QComboBox()
        self.amb_ground_model.addItems(['Kusuda','Timeseries','Constant'])
        self.amb_ground_model.setCurrentText(modellingSettings['ground_model'])
        layout_ground_value.addWidget(self.amb_ground_model) 
        
        self.amb_kusuda_tsurfmean = QLineEdit(modellingSettings['kusuda_tsurfmean'])
        layout_ground_value.addWidget(self.amb_kusuda_tsurfmean) 
        
        self.amb_kusuda_tsurfampl = QLineEdit(modellingSettings['kusuda_tsurfampl'])
        layout_ground_value.addWidget(self.amb_kusuda_tsurfampl) 
        
        self.amb_kusuda_theta = QLineEdit(modellingSettings['kusuda_theta'])
        layout_ground_value.addWidget(self.amb_kusuda_theta) 
        
        self.amb_kusuda_rho = QLineEdit(modellingSettings['kusuda_rho'])
        layout_ground_value.addWidget(self.amb_kusuda_rho) 
        
        self.amb_kusuda_cp = QLineEdit(modellingSettings['kusuda_cp'])
        layout_ground_value.addWidget(self.amb_kusuda_cp) 
        
        self.amb_kusuda_lambda = QLineEdit(modellingSettings['kusuda_lambda'])
        layout_ground_value.addWidget(self.amb_kusuda_lambda) 
        
        self.amb_kusuda_depth = QLineEdit(modellingSettings['kusuda_depth'])
        layout_ground_value.addWidget(self.amb_kusuda_depth) 
        
        
        self.amb_ground_profile = ComboBox()
        self.amb_ground_profile.addItems(self.getTimeseriesIds('temp_timeseries'))
        self.amb_ground_profile.setCurrentText(modellingSettings['ground_timeseries'])
        layout_ground_value.addWidget(self.amb_ground_profile) 
        
        
        self.amb_ground_temp = QLineEdit(modellingSettings['ground_temp'])
        layout_ground_value.addWidget(self.amb_ground_temp) 
        
        #set labes & values together
        layout_ground = QHBoxLayout() 
        layout_ground.addLayout(layout_ground_label)
        layout_ground.addLayout(layout_ground_value) 
        
        
        #titel
        label_duct_title =QLabel("Duct temperatur")
        font=label_duct_title.font()
        font.setPointSize(12)
        label_duct_title.setFont(font)
        
        #labels
        layout_duct_label = QVBoxLayout()
        
        label_duct_model =QLabel("Duct model:")
        layout_duct_label.addWidget(label_duct_model)            
        
        self.label_amb_duct_profile =QLabel("Duct temperatur timeseries:")
        layout_duct_label.addWidget(self.label_amb_duct_profile)
        
        self.label_amb_duct_temp =QLabel("Constant duct temperatur:")
        layout_duct_label.addWidget(self.label_amb_duct_temp)
        
        #values
        layout_duct_value = QVBoxLayout()
        
        self.amb_duct_model = QComboBox()
        self.amb_duct_model.addItems(['Timeseries','Constant'])
        self.amb_duct_model.setCurrentText(modellingSettings['duct_model'])
        layout_duct_value.addWidget(self.amb_duct_model)        
        
        self.amb_duct_profile = ComboBox()
        self.amb_duct_profile.addItems(self.getTimeseriesIds('temp_timeseries'))
        self.amb_duct_profile.setCurrentText(modellingSettings['duct_timeseries'])
        layout_duct_value.addWidget(self.amb_duct_profile) 
        
        self.amb_duct_temp = QLineEdit(modellingSettings['duct_temp'])
        layout_duct_value.addWidget(self.amb_duct_temp) 
        
        #set labes & values together
        layout_duct = QHBoxLayout() 
        layout_duct.addLayout(layout_duct_label)
        layout_duct.addLayout(layout_duct_value)   
        
        #titel
        label_air_title =QLabel("Ambient air temperatur")
        font=label_air_title.font()
        font.setPointSize(12)
        label_air_title.setFont(font)
        
        #labels
        layout_air_label = QVBoxLayout()
        
        label_amb_ambient_air_model =QLabel("Ambient air model:")
        layout_air_label.addWidget(label_amb_ambient_air_model)            
        
        #values
        layout_air_value = QVBoxLayout()
        
        self.amb_ambient_air_model = QComboBox()
        self.amb_ambient_air_model.addItems(['Climate'])
        self.amb_ambient_air_model.setCurrentText(modellingSettings['ambient_air_model'])
        layout_air_value.addWidget(self.amb_ambient_air_model)        

        
        #set labes & values together
        layout_air = QHBoxLayout() 
        layout_air.addLayout(layout_air_label)
        layout_air.addLayout(layout_air_value)     
        
        #set settings layout together
        layout_fd_pipe_settings = QVBoxLayout()
        layout_fd_pipe_settings.addWidget(label_fd_pipe_title)
        layout_fd_pipe_settings.addLayout(layout_fd_pipe)
        layout_fd_pipe_settings.addWidget(label_node_title)
        layout_fd_pipe_settings.addLayout(layout_node)
        layout_fd_pipe_settings.addWidget(label_ambient_title)
        layout_fd_pipe_settings.addWidget(label_ground_title)
        layout_fd_pipe_settings.addLayout(layout_ground)
        layout_fd_pipe_settings.addWidget(label_duct_title)
        layout_fd_pipe_settings.addLayout(layout_duct)
        layout_fd_pipe_settings.addWidget(label_air_title)
        layout_fd_pipe_settings.addLayout(layout_air)
        
        
        #---------------ok/cancel buttons     
        layout_buttons = QHBoxLayout()
        self.btn_ok=QPushButton("Ok")
        layout_buttons.addWidget(self.btn_ok)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addLayout(layout_fd_pipe_settings)
        layout_win.addLayout(layout_buttons)
        layout_win.addStretch()
        
        #trigger show/hide labels and value fields
        self.showGroundModelParameter(modellingSettings['ground_model'])
        self.showDuctModelParameter(modellingSettings['duct_model'])

        #connect signals
        self.amb_duct_model.currentTextChanged.connect(self.showDuctModelParameter)
        self.amb_ground_model.currentTextChanged.connect(self.showGroundModelParameter)
        self.amb_ground_profile.popupAboutToBeShown.connect(lambda: self.setTimeseriesIds(self.amb_ground_profile,'temp_timeseries'))            
        self.amb_duct_profile.popupAboutToBeShown.connect(lambda: self.setTimeseriesIds(self.amb_duct_profile,'temp_timeseries'))              

        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
    
    def setTimeseriesIds(self,combobox,table_name):
        ids=self.getTimeseriesIds(table_name)
        combobox.clear()
        combobox.addItems(ids)
        
    def getTimeseriesIds(self,table_name):
        sql="""SELECT id FROM {} ORDER BY id;""".format(table_name)
        print(sql)
        self.cur.execute(sql)
        return [str(i['id']) for i in self.cur.fetchall()]
              
    def showDuctModelParameter(self,s):
        print(s)
        if s=='Timeseries':
            self.amb_duct_profile.setHidden(False)
            self.label_amb_duct_profile.setHidden(False)
        
            self.amb_duct_temp.setHidden(True)
            self.label_amb_duct_temp.setHidden(True)
        elif 'Constant':
            self.amb_duct_temp.setHidden(False)
            self.label_amb_duct_temp.setHidden(False)
            self.amb_duct_profile.setHidden(True)
            self.label_amb_duct_profile.setHidden(True)
        self.adjustSize()
                
    def showGroundModelParameter(self,s):
        print(s)
        if s=='Kusuda':
            self.amb_kusuda_tsurfmean.setHidden(False)
            self.amb_kusuda_tsurfampl.setHidden(False)
            self.amb_kusuda_theta.setHidden(False)
            self.amb_kusuda_rho.setHidden(False)
            self.amb_kusuda_cp.setHidden(False)
            self.amb_kusuda_lambda.setHidden(False)
            self.amb_kusuda_depth.setHidden(False)
            self.label_amb_kusuda_tsurfmean.setHidden(False)
            self.label_amb_kusuda_tsurfampl.setHidden(False)
            self.label_amb_kusuda_theta.setHidden(False)
            self.label_amb_kusuda_rho.setHidden(False)
            self.label_amb_kusuda_cp.setHidden(False)
            self.label_amb_kusuda_lambda.setHidden(False)
            self.label_amb_kusuda_depth.setHidden(False)
            
            self.amb_ground_profile.setHidden(True)
            self.amb_ground_temp.setHidden(True)
            self.label_amb_ground_profile.setHidden(True)
            self.label_amb_ground_temp.setHidden(True)
        elif s=='Timeseries':
            self.amb_ground_profile.setHidden(False)
            self.label_amb_ground_profile.setHidden(False)
            
            self.amb_kusuda_tsurfmean.setHidden(True)
            self.amb_kusuda_tsurfampl.setHidden(True)
            self.amb_kusuda_theta.setHidden(True)
            self.amb_kusuda_rho.setHidden(True)
            self.amb_kusuda_cp.setHidden(True)
            self.amb_kusuda_lambda.setHidden(True)
            self.amb_kusuda_depth.setHidden(True)
            self.label_amb_kusuda_tsurfmean.setHidden(True)
            self.label_amb_kusuda_tsurfampl.setHidden(True)
            self.label_amb_kusuda_theta.setHidden(True)
            self.label_amb_kusuda_rho.setHidden(True)
            self.label_amb_kusuda_cp.setHidden(True)
            self.label_amb_kusuda_lambda.setHidden(True)
            self.label_amb_kusuda_depth.setHidden(True)
            self.amb_ground_temp.setHidden(True)
            self.label_amb_ground_temp.setHidden(True)
        elif s=='Constant':
            self.amb_ground_temp.setHidden(False)
            self.label_amb_ground_temp.setHidden(False)

            self.amb_ground_profile.setHidden(True)
            self.amb_kusuda_tsurfmean.setHidden(True)
            self.amb_kusuda_tsurfampl.setHidden(True)
            self.amb_kusuda_theta.setHidden(True)
            self.amb_kusuda_rho.setHidden(True)
            self.amb_kusuda_cp.setHidden(True)
            self.amb_kusuda_lambda.setHidden(True)
            self.amb_kusuda_depth.setHidden(True)
            self.label_amb_ground_profile.setHidden(True)
            self.label_amb_kusuda_tsurfmean.setHidden(True)
            self.label_amb_kusuda_tsurfampl.setHidden(True)
            self.label_amb_kusuda_theta.setHidden(True)
            self.label_amb_kusuda_rho.setHidden(True)
            self.label_amb_kusuda_cp.setHidden(True)
            self.label_amb_kusuda_lambda.setHidden(True)
            self.label_amb_kusuda_depth.setHidden(True)