# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Districts
                                 A QGIS plugin
 This is the Districts Modeler plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-16
        copyright            : (C) 2026 by EQUA
        email                : peter.nageler@equa.ch
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Districts class from file Districts.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .districts import Districts
    return Districts(iface)
