# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IDA_Districts_ProjectHandlingDialog
                                 A QGIS plugin
 IDA Districts Project Handling
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-14
        git sha              : $Format:%H$
        copyright            : (C) 2021 by EQUA
        email                : peter.nageler@euqa.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.utils import iface
from qgis.PyQt.QtCore import QObject,pyqtSignal
from qgis.PyQt.QtWidgets import QTreeView,QAction,QMainWindow,QWidget,QPushButton,QRadioButton, QHBoxLayout,QVBoxLayout,QLabel,QLineEdit,QCheckBox,QComboBox, QProgressBar,QFileDialog,QGroupBox
from qgis.core import Qgis
from qgis.PyQt.QtCore import Qt

class IDA_Districts_NameDialog(QMainWindow):
    def __init__(self,title,label_text,old_input,old_description):
        """Constructor."""
        super().__init__()
        self.setWindowTitle(title)     
        
        #label
        print(label_text)
        layout_label = QVBoxLayout() 
        label =QLabel(label_text)
        layout_label.addWidget(label)
        
        label_description =QLabel('You can add a description:')
        layout_label.addWidget(label_description)
        
        #input 
        layout_input = QVBoxLayout()         
        self.input =QLineEdit(old_input)
        layout_input.addWidget(self.input)
        
        self.input_description =QLineEdit(old_description)
        layout_input.addWidget(self.input_description)
        
        #set name settings together
        layout_name = QHBoxLayout() 
        layout_name.addLayout(layout_label)
        layout_name.addLayout(layout_input)
        
        #buttons     
        layout_buttons = QHBoxLayout()
        self.btn_ok=QPushButton("Ok")
        layout_buttons.addWidget(self.btn_ok)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addLayout(layout_name)
        layout_win.addLayout(layout_buttons)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
        
class ExportProjectDialog(QMainWindow):
    def __init__(self):
        """Constructor ExportProjectDialog"""
        super().__init__()
        self.setWindowTitle("Export project settings")    
        
        #comboboxes
        layout_settings = QVBoxLayout()
        self.exportInvokedFeatures =QCheckBox("Invoked features") 
        self.exportPrn =QCheckBox(".prn results") 
        self.exportDBResults =QCheckBox("Database results") 
        layout_settings.addWidget(self.exportInvokedFeatures)
        layout_settings.addWidget(self.exportPrn)
        layout_settings.addWidget(self.exportDBResults)
        
        #choose file
        layout_file = QHBoxLayout()
        self.filename=QLineEdit('')
        self.btn_selectFile=QPushButton("...")
        self.btn_selectFile.clicked.connect(self.fileDlg)
        
        layout_file.addWidget(self.filename)
        layout_file.addWidget(self.btn_selectFile)
        
        #buttons     
        layout_buttons = QHBoxLayout()
        self.btn_ok=QPushButton("Export")
        layout_buttons.addWidget(self.btn_ok)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #progress bar
        self.progress=QProgressBar()
        
        #set layout together       
        layout_export = QVBoxLayout()
        layout_export.addLayout(layout_settings)
        layout_export.addLayout(layout_file)
        layout_export.addLayout(layout_buttons)
        layout_export.addWidget(self.progress)
        
        widget=QWidget()
        widget.setLayout(layout_export)
        self.setCentralWidget(widget)
        
    def update_progress(self,progress):
        self.progress.setValue(progress)
        
    def show_error_message(self, message):
        # Show the error message in a messageBar
        iface.messageBar().pushMessage("Error", message, level=Qgis.Critical)
        
    def fileDlg(self):
        filename, _filter = QFileDialog.getSaveFileName(
            self, "Export IDA Districts project", '','*.ida')
        self.filename.setText(filename.replace('/','\\'))
      
class ProjectConfigDialog(QMainWindow):
    def __init__(self):
        """Constructor Project Configurations"""
        super().__init__()
        self.setWindowTitle("Project Configuration Settings")    
        
        #labels
        layout_labels = QVBoxLayout()
        label_srid =QLabel("Coordinate system SRID")
        layout_labels.addWidget(label_srid)   
        
        #values
        layout_values = QVBoxLayout()
        self.srid =QLineEdit("")
        layout_values.addWidget(self.srid)  
        
        layout_field_input = QHBoxLayout()
        layout_field_input.addLayout(layout_labels)
        layout_field_input.addLayout(layout_values)   
        
        #buttons     
        layout_buttons = QHBoxLayout()
        self.btn_ok=QPushButton("Ok")
        layout_buttons.addWidget(self.btn_ok)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #set layout together       
        layout_project = QVBoxLayout()
        layout_project.addLayout(layout_field_input)
        layout_project.addLayout(layout_buttons)
        
        widget=QWidget()
        widget.setLayout(layout_project)
        self.setCentralWidget(widget)
        
class ApproveDialog(QMainWindow):
    def __init__(self,title,label_text):
        super().__init__()
        self.setWindowTitle(title)
        
        #label
        label =QLabel(label_text)
        
        #buttons     
        layout_buttons = QHBoxLayout()
        self.btn_ok=QPushButton("Ok")
        layout_buttons.addWidget(self.btn_ok)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addWidget(label)
        layout_win.addLayout(layout_buttons)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)

class NewProjectDlg(QMainWindow):
    def __init__(self):
        """Constructor NewProjectDlg"""
        super().__init__()
        self.setWindowTitle("New IDA Districts project")  

        #project name 
        layout_project= QHBoxLayout() 

        label_project_name =QLabel('Project name:')
        layout_project.addWidget(label_project_name)
        
        self.project_name=QLineEdit()
        layout_project.addWidget(self.project_name)
      
        #template 
        self.selectTemplate =QComboBox()
        self.selectTemplate.addItems(['Empty project','DB default values','Heating network','Co-sim buildings with heating network'])
        self.selectTemplate.setCurrentText('Heating network')
        self.selectTemplate.currentTextChanged.connect(self.update_checkbox_dbDefaultValues)

        #Qheckboxes
        layout_settings = QVBoxLayout()
        self.checkbox_db_defaultValues =QCheckBox("DB default values")
        self.checkbox_db_defaultValues.setDisabled(True) 
        self.checkbox_invokedFeatures =QCheckBox("Invoked features") 
        self.checkbox_prn =QCheckBox(".prn results") 
        self.checkbox_DBResults =QCheckBox("Database results") 
        layout_settings.addWidget(self.checkbox_db_defaultValues)
        layout_settings.addWidget(self.checkbox_invokedFeatures)
        layout_settings.addWidget(self.checkbox_prn)
        layout_settings.addWidget(self.checkbox_DBResults)
        layout_settings.setContentsMargins(30, 0, 0, 0)
        
        self.group_box_autsave = QGroupBox("")
        self.group_box_autsave.setLayout(layout_settings)
        
        #buttons     
        layout_buttons = QHBoxLayout()
        self.btn_ok=QPushButton("Create")
        layout_buttons.addWidget(self.btn_ok)
        self.btn_cancel=QPushButton("Cancel")
        layout_buttons.addWidget(self.btn_cancel)
        
        self.progress=QProgressBar()

        
        #---------------set layouts together-------------------
        layout_win = QVBoxLayout()
        layout_win.addLayout(layout_project)
        layout_win.addWidget(self.selectTemplate)
        layout_win.addWidget(self.group_box_autsave)
        layout_win.addLayout(layout_buttons)
        layout_win.addWidget(self.progress)
        
        widget=QWidget()
        widget.setLayout(layout_win)
        self.setCentralWidget(widget)
        #self.update_checkbox_dbDefaultValues() 
        
    def update_checkbox_dbDefaultValues(self,text):
        if text in ['DB default values','Empty project']:
            self.checkbox_db_defaultValues.setCheckState(Qt.CheckState.Checked)
            self.checkbox_invokedFeatures.setCheckState(Qt.CheckState.Unchecked)
            self.checkbox_prn.setCheckState(Qt.CheckState.Unchecked)
            self.checkbox_DBResults.setCheckState(Qt.CheckState.Unchecked)
            self.checkbox_invokedFeatures.setDisabled(True) 
            self.checkbox_prn.setDisabled(True) 
            self.checkbox_DBResults.setDisabled(True) 
        else:
            self.checkbox_db_defaultValues.setCheckState(Qt.CheckState.Unchecked)
            self.checkbox_invokedFeatures.setEnabled(True) 
            self.checkbox_prn.setEnabled(True) 
            self.checkbox_DBResults.setEnabled(True) 
            
    def update_progress(self,progress):
        self.progress.setValue(progress)
        
    def show_error_message(self, message):
        # Show the error message in a messageBar
        iface.messageBar().pushMessage("Error", message, level=Qgis.Critical)
        









