# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IDA_Districts_ProjectHandling
                                 A QGIS plugin
 IDA Districts Project Handling
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-12-14
        git sha              : $Format:%H$
        copyright            : (C) 2021 by EQUA
        email                : peter.nageler@euqa.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from plugins.utility_functions.db import *
from plugins.utility_functions.layer_visualization import *
from plugins.utility_functions.utility import *
from plugins.utility_functions.files import *
from plugins.utility_functions.dialog import *
from plugins.utility_functions.reports import * 
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication,pyqtSignal,QThreadPool
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QApplication, QTreeWidget, QTreeWidgetItem

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .IDA_districts_project_handling_dialog import IDA_Districts_ProjectHandlingDialog, ProjectConfigDialog,ExportProjectDialog
from .Dialogs import IDA_Districts_NameDialog, ApproveDialog, NameFieldDialog
import os.path
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
import psycopg2.extras
import subprocess
import os
from qgis.core import QgsAttributeEditorAction,QgsAction,QgsProject, Qgis,QgsCredentials, QgsSettings,QgsSvgMarkerSymbolLayer, QgsAttributeEditorField, QgsAttributeEditorContainer, QgsEditFormConfig, QgsEditorWidgetSetup, QgsVectorLayer, QgsDataSourceUri, QgsSymbol, QgsRendererCategory, QgsStyle, QgsCategorizedSymbolRenderer, QgsGraduatedSymbolRenderer, QgsRendererRange, QgsMarkerSymbol, QgsClassificationRange, QgsApplication
from qgis.utils import iface
from PyQt5.QtGui import * 
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from functools import partial
from qgis.PyQt import QtGui 
import math
import numpy as np
import sys
from collections import deque
from PyQt5.QtCore import Qt
from pathlib import Path
import json
from qgis.PyQt.QtGui import QKeySequence
from qgis.PyQt.QtWidgets import QShortcut  

from plugins.utility_functions.workers import *
import shutil

def loadVersionLayers(dictDB,cur,plugin_dir):
    """Loads the layers in QGIS"""
    removeLayers()    
            
    print(dictDB['projectName'])
    uri = QgsDataSourceUri()
    uri.setConnection(dictDB['host'], dictDB['port'], dictDB['projectName'], dictDB['user'], dictDB['pwd'])
    print(uri)

    view = iface.layerTreeView()
    
    try: 
        uri.setDataSource(dictDB['versionName'], "submodels", "geom")
        vlayer = QgsVectorLayer(uri.uri(False), "submodels", dictDB['user'])
        QgsProject.instance().addMapLayer(vlayer)
        single_symbol_renderer = vlayer.renderer()
        symbol = single_symbol_renderer.symbol()
        symbol.setColor(QColor.fromRgb(255, 0, 0))
        view.refreshLayerSymbology(vlayer.id())

        uri.setDataSource(dictDB['versionName'], "streets", "geom")
        vlayer = QgsVectorLayer(uri.uri(False), "streets", dictDB['user'])
        QgsProject.instance().addMapLayer(vlayer) 
        single_symbol_renderer = vlayer.renderer()
        symbol = single_symbol_renderer.symbol()
        symbol.setColor(QColor.fromRgb(131, 131, 131))
        symbol.setWidth(0.75)  
        view.refreshLayerSymbology(vlayer.id())
        
        uri.setDataSource(dictDB['versionName'], "buildings", "geom")
        vlayer = QgsVectorLayer(uri.uri(False), "buildings", dictDB['user'])
        QgsProject.instance().addMapLayer(vlayer)
        single_symbol_renderer = vlayer.renderer()
        symbol = single_symbol_renderer.symbol()
        symbol.setColor(QColor.fromRgb(25, 25, 25))
        view.refreshLayerSymbology(vlayer.id())
        
    except Exception as e:
        print(f'error: {e}')
    
    view = iface.layerTreeView()
    view.setLayerVisible(QgsProject.instance().mapLayersByName('submodels')[0], False)    
    loadTopologyLayers(dictDB['versionName'],uri,dictDB)   
    loadProjectLayers(dictDB['versionName'],uri,dictDB,plugin_dir,cur)
    
    loadBoreholesLayer(dictDB['versionName'],uri,dictDB,plugin_dir,cur)

   
    versionLayersAliasNames()
    setupVersionForm(cur,dictDB)
    setupCustomerDataSheet()
      
    valueRelationPipeBundleType()    
    valueRelationDhwId()    
    valueRelationInternalLoadId() 
        
class WorkerLoadVersion(QRunnable):
    """Worker thread
    Inherits from QRunnable to handle worker thread setup, signals and wrap-up."""
    def __init__(self,*args,**kwargs):
        super().__init__()
        self.args=args
        print(args)
        self.signals=APISignals()
        self.dictDB=kwargs['dictDB']
        self.cur=kwargs['cur']
        self.plugin_dir=kwargs['plugin_dir']
        self.dlg=kwargs['dlg']
        self.item=kwargs['item']

    @pyqtSlot()
    def run(self):
        try:
            print('Load project version')
            self.signals.progress.emit(10)  
            print (self.dictDB['versionName'])
                
            #check if there are changes in the child versions and append the changes to the diff script
            sql='SELECT name AS version_name FROM public.versionhandling WHERE id_base in (SELECT id FROM public.versionhandling WHERE name=\'{}\');'.format(self.dictDB['versionName'])
            print(sql)
            self.cur.execute(sql)
            childs = self.cur.fetchall()     
            
            print(childs)
            for child in childs:
                print(child['version_name'])
                #read diff script
                diffData=''

                for table in ['customers','energy_plants','lines','devices','junctions','structure_boundarys','structure_junctions','structure_lines']:
                    #Check for inserted items
                    print(table)
                    sql="""SELECT id FROM "{}".{}
                            EXCEPT
                            SELECT id FROM "{}".{};""".format(child['version_name'],table,self.dictDB['versionName'],table)
                    print(sql)
                    self.cur.execute(sql)
                    for result in self.cur.fetchall():
                        sql='SELECT * FROM "{}".{} WHERE id={};'.format(child['version_name'],table,result['id'])     
                        self.cur.execute(sql)
                        diff ='INSERT INTO "{}".{} VALUES \n'.format(child['version_name'],table)+str(self.cur.fetchone()).replace('None','Null')+';'
                        if diff not in diffData:
                            diffData=diffData+diff

                    #Check for deleted items
                    sql="""SELECT id FROM "{}".{}
                            EXCEPT
                            SELECT id FROM "{}".{};""".format(self.dictDB['versionName'],table,child['version_name'],table)
                    print(sql)
                    self.cur.execute(sql)
                    for result in self.cur.fetchall():
                        diff ='DELETE FROM "{}".{} WHERE id={}; \n'.format(child['version_name'],table,result['id'])
                        if diff not in diffData:
                            diffData=diffData+diff
                            
                    #Check for updated items
                    sql='SELECT column_name, data_type FROM information_schema.columns WHERE table_schema=\'{}\' AND table_name=\'{}\';'.format(self.dictDB['versionName'],table)
                    print(sql)
                    self.cur.execute(sql)
                    columns=self.cur.fetchall()
                    for column in columns:
                        sql="""SELECT id,{} FROM "{}".{}
                            EXCEPT
                            SELECT id,{} FROM "{}".{};""".format(column['column_name'],child['version_name'],table,column['column_name'],self.dictDB['versionName'],table)
                        print(sql)
                        self.cur.execute(sql)
                        for updatedColumnValue in self.cur.fetchall():
                            print ('+++++++++++++++++++++++++++')
                            print (column['data_type'])
                        
                            if column['data_type'] in ['integer','numeric']:
                                print('value')
                                diff ='UPDATE "{}".{} SET {} = {} WHERE id={}; \n'.format(child['version_name'],table,column['column_name'],updatedColumnValue[1],updatedColumnValue[0])
                            else:
                                print('geom')
                                diff ='UPDATE "{}".{} SET {} = \'{}\' WHERE id={}; \n'.format(child['version_name'],table,column['column_name'],updatedColumnValue[1],updatedColumnValue[0])
                            if diff not in diffData:
                                diffData=diffData+diff
                
                print(diffData)
                with open(self.plugin_dir+"\\diff scripts\\version_{}_{}_diff_script.sql".format(self.dictDB['projectName'],child['version_name']),'w') as myfile:
                    myfile.write(diffData)   
            
            #copy schema from parent version if version is a child 
            if self.item.parent():
                sql = 'DROP SCHEMA '+self.dictDB['versionName']+' CASCADE;'
                print(sql)
                self.cur.execute(sql)
                copy_schema(self.item.parent().text(),self.dictDB['versionName'],self.dictDB,self.cur,self.plugin_dir)
                
                if os.path.exists(self.plugin_dir+"\\diff scripts\\version_{}_{}_diff_script.sql".format(self.dictDB['projectName'],self.dictDB['versionName'])):
                    os.environ['PGPASSWORD'] = self.dictDB['pwd']
                    path_postgres=loadIDADistrictsConfig(self.plugin_dir)['path_postgresql']
                    cmd = ' "{}\\bin\\psql" -d {} -h {} -U {} < "{}\\diff scripts\\version_{}_{}_diff_script.sql"'.format(path_postgres,self.dictDB['projectName'],self.dictDB['host'],self.dictDB['user'],self.plugin_dir,self.dictDB['projectName'],self.dictDB['versionName'])
                    print(cmd)
                    subprocess.call(cmd, shell=True)   
                    
            self.signals.progress.emit(100)            
            print('finished tables')
        except Exception as e:
            print(f'error: {e}')
            self.signals.error.emit("Loading version failed!")
        
class WorkerImportProject(QRunnable):
    """Worker thread
    Inherits from QRunnable to handle worker thread setup, signals and wrap-up."""
    def __init__(self,*args,**kwargs):
        super().__init__()
        self.args=args
        print(args)
        self.signals=APISignals()
        self.dictDB=kwargs['dictDB']
        self.filename=kwargs['filename']
        self.cur=kwargs['cur']
        self.plugin_dir=kwargs['plugin_dir']
        self.dlg=kwargs['dlg']

    @pyqtSlot()
    def run(self):
        print('Import project')
        self.signals.progress.emit(1)            
        dir='\\'.join(self.filename.split('\\')[0:-1])+'\\'
        name=self.filename.split('\\')[-1].split('.')[0]
        dir=dir+name
        
        if not os.path.exists(dir):
            if os.path.exists(loadIDADistrictsConfig(self.plugin_dir)['path_ice']+"bin\\7za.exe"):
                cmd="""\"{}bin\\7za.exe" x "{}" -o"{}\"""".format(loadIDADistrictsConfig(self.plugin_dir)['path_ice'],self.filename,dir)
                print(cmd)
                subprocess.call(cmd, shell=True)
            else:
                self.signals.error.emit("IDA ICE Directory cannot be found. Please check IDA Districts configuration data!")
                self.signals.progress.emit(0)            
                return False
        self.signals.progress.emit(15)            

        #get project name
        db_info=''
        if os.path.exists(dir+'\\DB_info.txt'):
            with open(dir+'\\DB_info.txt', "r") as myfile:   
                for line in myfile:        
                    db_info+=line
        db_info=strToDict(db_info)
        
        #check if project already exists
        if checkDBName(db_info['projectName'],self.cur,self.dictDB):
            print('project does not exist')
            print(dir)
            self.signals.progress.emit(20)
            try:
                print(dir+'\\ida_districts_data_center\\'+name)
                print(getDataCenterDir(self.plugin_dir)+'\\'+name)
                copy_tree_filter_extensions_and_folders(dir+'\\ida_districts_data_center\\'+name,getDataCenterDir(self.plugin_dir)+'\\'+name)
                self.signals.progress.emit(30)
            except Exception as e:
                print(f'error: {e}')
                self.signals.error.emit("Data center copying failed!")
                return False
            try:
                if os.path.exists(dir+'\\ida_districts_modeling_simulation'):
                    copy_tree_filter_extensions_and_folders(dir+'\\ida_districts_modeling_simulation\\'+name,getModellingDir(self.plugin_dir)+'\\network_models\\'+name)
                self.signals.progress.emit(50)
            except Exception as e:
                print(f'error: {e}')
                self.signals.error.emit("Modelling data copying failed!")
                return False
            try:
                copy_tree_filter_extensions_and_folders(dir+'\\ida_districts_project_handling\\'+name,self.plugin_dir+'\\'+name)
                self.signals.progress.emit(70)
            except Exception as e:
                print(f'error: {e}')
                self.signals.error.emit("Copying data failed!")
                return False
            sql = 'CREATE database '+db_info['projectName']+';'
            self.cur.execute(sql)
            self.signals.progress.emit(75)

            cmd="""\"{}bin\\psql" --dbname=postgresql://{}:{}@{}:{}/{} -f "{}\\{}.sql\"""".format(
                loadIDADistrictsConfig(self.plugin_dir)['path_postgresql'],self.dictDB['user'],self.dictDB['pwd'],self.dictDB['host'],self.dictDB['port'],db_info['projectName'],dir,name)
            print(cmd)
            subprocess.call(cmd, shell=True) 
            self.dlg.selectProject.addItem(db_info['projectName'])
        else:
            self.signals.error.emit("Project already exists in DB!")
            self.signals.progress.emit(0)  
                            dir=self.plugin_dir+'\\'+projectName
            if os.name == 'nt':
                dir='\\\\?\\'+dir
            shutil.rmtree(dir)            
            return False
            
        if os.name == 'nt':
            dir='\\\\?\\'+dir
        shutil.rmtree(dir)  
        self.signals.progress.emit(100)
            
class WorkerExportProject(QRunnable):
    """Worker thread
    Inherits from QRunnable to handle worker thread setup, signals and wrap-up."""
    def __init__(self,*args,**kwargs):
        super().__init__()
        self.args=args
        print(args)
        self.signals=APISignals()
        self.dictDB=kwargs['dictDB']
        self.filename=kwargs['filename']
        self.filter_folders=kwargs['filter_folders']
        self.filter_extensions=kwargs['filter_extensions']
        self.no_db_results=kwargs['no_db_results']
        self.conn=""
        self.cur=""
        self.plugin_dir=kwargs['plugin_dir']
        self.conn = dbConnect(self.dictDB,True)
        if self.conn:
            self.cur=self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            
    @pyqtSlot()
    def run(self):
        print('Export project')
        self.signals.progress.emit(1)
         
        print(self.filename)
        dir='\\'.join(self.filename.split('\\')[0:-1])+'\\'
        name=self.filename.split('\\')[-1].split('.')[0]
        print(dir)
        print(name)
        createDir(dir,name)
        dir=dir+name

        # Check if the folder exists and delete it
        if os.path.exists(dir) and os.path.isdir(dir):
            if os.name == 'nt':
                dir='\\\\?\\'+dir
            shutil.rmtree(dir)  
            
        path_postgres=loadIDADistrictsConfig(self.plugin_dir)['path_postgresql']
        
        # Ensure the directory exists, create it if necessary
        sql_path = dir+f"\\{name}.sql"

        os.makedirs(os.path.dirname(sql_path), exist_ok=True)
        cmd = [
            path_postgres+"bin\\pg_dump",  # Path to pg_dump
            "--dbname=postgresql://{}:{}@{}:{}/{}".format(self.dictDB['user'],self.dictDB['pwd'],self.dictDB['host'],self.dictDB['port'],self.dictDB['projectName'])
        ]
        if self.no_db_results:
            cmd.append("--exclude-table-data=*.customer_*")
            cmd.append("--exclude-table-data=*.line_*")
            cmd.append("--exclude-table-data=*.energy_plant_*")
        print(cmd)
        # Output file redirection (using stdout to redirect the output to a file)
        with open(sql_path, "w") as output_file:
            subprocess.call(cmd, stdout=output_file)        
            
        self.signals.progress.emit(25)

        print(getDataCenterDir(self.plugin_dir)+'\\'+self.dictDB['projectName'])
        try:
            copy_tree_filter_extensions_and_folders(getDataCenterDir(self.plugin_dir)+'\\'+self.dictDB['projectName'], dir+'\\ida_districts_data_center'+'\\'+name,self.signals,self.filter_extensions,self.filter_folders)
        except Exception as e:
            print(f'error: {e}')
            self.signals.error.emit("Data center files export failed!")
        self.signals.progress.emit(40)    
        try:
            copy_tree_filter_extensions_and_folders(self.plugin_dir+'\\'+self.dictDB['projectName'], dir+'\\ida_districts_project_handling'+'\\'+name,self.signals,self.filter_extensions,self.filter_folders)
        except Exception as e:
            print(f'error: {e}')
            self.signals.error.emit("Project handling files export failed!") 
        self.signals.progress.emit(55)  
        if os.path.exists(getModellingDir(self.plugin_dir)+'\\'+'network_models'+'\\'+self.dictDB['projectName']):
            try:
                copy_tree_filter_extensions_and_folders(getModellingDir(self.plugin_dir)+'\\'+'network_models'+'\\'+self.dictDB['projectName'], dir+'\\ida_districts_modeling_simulation'+'\\'+name,self.signals,self.filter_extensions,self.filter_folders)
            except Exception as e:
                print(f'error: {e}')
                self.signals.error.emit("Modelling files export failed!") 
        self.signals.progress.emit(70)  
        db_info={'projectName': name}
        if os.path.exists(dir):
            with open(dir+'\\DB_info.txt', "w") as myfile:   
                myfile.write(str(db_info))
        cmd="""\"{}bin\\7za.exe" a -t7z -r "{}.ida" "{}/*.*\"""".format(loadIDADistrictsConfig(self.plugin_dir)['path_ice'],dir,dir)
        print(cmd)
        subprocess.call(cmd, shell=True) 
        if os.name == 'nt':
            dir='\\\\?\\'+dir
        shutil.rmtree(dir)  
        self.signals.progress.emit(100)
            
class IDA_Districts_ProjectHandling:
    """QGIS Plugin Implementation."""
    
    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.threadpool = QThreadPool()            

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__).replace('/','\\')
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'IDA_Districts_ProjectHandling_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&IDA Districts Project Handling')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
          
        self.dictDB={'pwd' : '' , 'host' : '','port':'', 'user' : '', 'projectName' : '', 'versionName' : ''}
        self.conn=''
        self.cur=''
        self.conn_postgres=''
        self.cur_postgres=''
        self.projectConfig= {'srid': '25832'}
        
        shortcut = QShortcut(QKeySequence('Alt+Shift+I'), iface.mainWindow())
        shortcut.setContext(Qt.ApplicationShortcut)
        shortcut.activated.connect(self.openPlugin)

    def openPlugin(self):
        self.run()

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('IDA_Districts_ProjectHandling', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = ':/plugins/IDA_districts_project_handling/icons/icon-project-handling.png'
        self.add_action(
            icon_path,
            text=self.tr(u'IDA Districts Project Handling'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True
        
    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IDA Districts Project Handling'),
                action)
            self.iface.removeToolBarIcon(action)

    # Function to load version from treeview
    def TreeItem_Load(self, item, mdlIdx):
        if self.conn != '':
            self.dlg.update_progress(1)
            self.dictDB['versionName'] = item.text()
            writeDBSettings(self.plugin_dir,self.dictDB)
            uri = QgsDataSourceUri()
            uri.setConnection(self.dictDB['host'], self.dictDB['port'], self.dictDB['projectName'], self.dictDB['user'], self.dictDB['pwd'])
            loadVersionLayers(self.dictDB,self.cur,self.plugin_dir)
            
            self.worker_loadVersion = WorkerLoadVersion(dictDB=self.dictDB,plugin_dir=self.plugin_dir,cur=self.cur,dlg=self.dlg,item=item)
            self.worker_loadVersion.signals.progress.connect(self.dlg.update_progress)
            self.worker_loadVersion.signals.error.connect(self.dlg.show_error_message)      
            self.threadpool.start(self.worker_loadVersion)
        else:
            self.iface.messageBar().pushMessage("Error", "You are not connected to the DB!", level=Qgis.Critical)
    
    def connectDB(self):
        """make a connection to the DB and list the DBs in the dropdown menue"""
        self.disconnectDB()
        if not os.path.exists(loadIDADistrictsConfig(self.plugin_dir)['path_postgresql']):
            self.iface.messageBar().pushMessage("Error", "Postgres Directory cannot be found. Please check IDA Districts configuration data!", level=Qgis.Critical)  
            return false
            
        uri = QgsDataSourceUri()

        self.dictDB['port']=''
        self.dictDB['host']=''      
        uri.setConnection(self.dictDB['host'], self.dictDB['port'], self.dictDB['projectName'], None, None)
        connInfo = uri.connectionInfo()
        (success, user, passwd) = QgsCredentials.instance().get(connInfo, None, None)

        if success:
            uri.setPassword(passwd)
            self.dictDB['pwd']=passwd
            uri.setUsername(user)
            self.dictDB['user']=user
            QgsCredentials.instance().put( connInfo, user, passwd)     
            self.dictDB['port']=self.dlg.port.text()
            self.dictDB['host']=self.dlg.host.text()            

        writeDBSettings(self.plugin_dir,self.dictDB)
        print(self.dictDB)
        self.conn_postgres=dbConnectPerName(self.dictDB,"postgres",True)
        if self.conn_postgres:
            self.cur_postgres=self.conn_postgres.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
            project_names=loadProjectNames(self.cur_postgres,self.dictDB)
            self.dlg.selectProject.clear()
            self.dlg.selectProject.addItems(project_names)
            
        if not os.path.exists(loadIDADistrictsConfig(self.plugin_dir)['path_ice']):
            self.iface.messageBar().pushMessage("Error", "IDA ICE Directory cannot be found. Please check IDA Districts configuration data!", level=Qgis.Critical)
        
    def disconnectDB(self):
        """ empty DB dictionary"""
        print('disconnect DB')
        self.dictDB={'pwd' : '' , 'host' : '', 'port' : '', 'user' : '', 'projectName' : '', 'versionName' : ''}
        self.dlg.selectProject.clear()
        self.setTreeViewModel([])
        QgsCredentials.instance().put(None,None,None)
        removeLayers()
        writeDBSettings(self.plugin_dir,self.dictDB)
        if self.conn_postgres:
            self.conn_postgres.close()    
            print ('close postgres connection')
        if self.conn:
            self.conn.close()
            print ('close project connection')        

    def deleteProjectDialog(self):
        """Delete project dialog --> connects to the deleteProject function, which deletes the project"""
        print('Delete project dialog started')
        projectName=self.dlg.selectProject.currentText()
        if self.conn_postgres != '':
            title='Delete project'
            label_text='Are you sure you want to delete project {}?'.format(projectName)
            self.dlg_deleteProject = ApproveDialog(title,label_text)
            self.dlg_deleteProject.btn_ok.clicked.connect(lambda: self.deleteProject(projectName))
            self.dlg_deleteProject.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_deleteProject))
            self.dlg_deleteProject.show()               
        else:
            self.iface.messageBar().pushMessage("Error", "You are not connected to the DB!", level=Qgis.Critical)

    def deleteVersionDialog(self,item):
        """Delete project version dialog"""
        print('Delete project version dialog started')
        versionName=item.text()
        if self.conn_postgres != '':
            title='Delete project version'
            label_text='Are you sure you want to delete project version {}?'.format(versionName)
            self.dlg_deleteVersion = ApproveDialog(title,label_text)
            self.dlg_deleteVersion.btn_ok.clicked.connect(lambda: self.TreeItem_Delete(item,self.dlg_deleteVersion))
            self.dlg_deleteVersion.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_deleteVersion))
            self.dlg_deleteVersion.show()               
        else:
            self.iface.messageBar().pushMessage("Error", "You are not connected to the DB!", level=Qgis.Critical)
        
    def deleteProject(self,projectName):
        """Drop selected DB """
        index=self.dlg.selectProject.findText(projectName)
        if index:
            print('Delete DB: {}'.format(projectName))
            #close open connections
            sql="""SELECT pg_terminate_backend(pg_stat_activity.pid)
    FROM pg_stat_activity
    WHERE pg_stat_activity.datname = '{}'
      AND pid <> pg_backend_pid();""".format(projectName)
            print(sql)
            self.cur_postgres.execute(sql)

            sql='DROP DATABASE IF EXISTS {};'.format(projectName)
            self.cur_postgres.execute(sql)
            self.dlg.selectProject.removeItem(index)
            #delete folders
            if os.path.exists(self.plugin_dir+'\\'+projectName):
                dir=self.plugin_dir+'\\'+projectName
                if os.name == 'nt':
                    dir='\\\\?\\'+dir
                    print(dir)
                    shutil.rmtree(dir)
            if os.path.exists(getDataCenterDir(self.plugin_dir)+'\\'+projectName):
                dir=getDataCenterDir(self.plugin_dir)+'\\'+projectName
                if os.name == 'nt':
                    dir='\\\\?\\'+dir
                    print(dir)
                shutil.rmtree(dir)
            if os.path.exists(getModellingDir(self.plugin_dir)+'\\network_models\\'+projectName):
                dir=getModellingDir(self.plugin_dir)+'\\network_models\\'+projectName
                if os.name == 'nt':
                    dir='\\\\?\\'+dir
                    print(dir)
                shutil.rmtree(dir)
            self.dlg_deleteProject.close()
    
    def showCreateNewProject(self):
        """Creates a new Project"""
        if self.conn_postgres != '':
            self.dlg_createNewProject=NameFieldDialog('Create new project','Project name:','')
            self.dlg_createNewProject.btn_ok.clicked.connect(lambda: self.createNewProject(self.dlg_createNewProject))
            self.dlg_createNewProject.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_createNewProject))
            self.dlg_createNewProject.show()   
        else:
            self.iface.messageBar().pushMessage("Error", "You are not connected to the DB!", level=Qgis.Critical)
            
    def createNewProject(self,dlg):
        if checkString(dlg.input.text()):
            if checkDBName(dlg.input.text(),self.cur_postgres,self.dictDB):
                self.dictDB['projectName']=dlg.input.text()
                self.dlg.selectProject.addItem(self.dictDB['projectName'])
                print (self.dlg.selectProject.currentText())
                print (self.plugin_dir)
                
                dir_data_center=getDataCenterDir(self.plugin_dir)
                self.dlg.selectProject.setCurrentText(self.dictDB['projectName'])
                        
                sql = 'CREATE database '+self.dictDB['projectName']+';'
                self.cur_postgres.execute(sql)
                
                #add extensions and topology tables to new project
                self.conn=dbConnect(self.dictDB,True)
                self.cur = self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
                self.cur.execute('CREATE EXTENSION postgis;')
                self.cur.execute('CREATE EXTENSION pgrouting;')
                self.cur.execute('CREATE EXTENSION dblink;')
                self.cur.execute('CREATE EXTENSION postgis_raster;')
                
                #create temp folder
                sql = 'CREATE SCHEMA IF NOT EXISTS temp;'
                print(sql)
                self.cur.execute(sql) 
                
                sql=""
                #project tables
                if os.path.exists(self.plugin_dir+"\\DB_projectTablesDefault.txt"):
                    with open(self.plugin_dir+"\\DB_projectTablesDefault.txt", "r") as myfile:
                        for line in myfile:
                            sql=sql+line
                    sql = sql.replace("$srid$", self.projectConfig['srid'])
                    self.cur.execute(sql)
                sql=""
                #project values
                if os.path.exists(self.plugin_dir+"\\DB_projectTablesDefault_data.txt"):
                    with open(self.plugin_dir+"\\DB_projectTablesDefault_data.txt", "r") as myfile:
                        for line in myfile:
                            sql=sql+line
                    self.cur.execute(sql)
                    
                #add sql functions
                sql=""
                if os.path.exists(self.plugin_dir+"\\SQL_scripts.txt"):
                    with open(self.plugin_dir+"\\SQL_scripts.txt", "r") as myfile:
                        for line in myfile:
                            sql=sql+line
                    self.cur.execute(sql)
                
                data=self.getVersionData()
                self.setTreeViewModel(data)
                
                #make dir with db name and create project config file projectConfig.txt in project handling
                to_directory=self.plugin_dir+"\\"+self.dictDB['projectName']
                Path(to_directory).mkdir(parents=True, exist_ok=True)
                writeProjectConfig(self.plugin_dir,self.dictDB['projectName'],self.projectConfig)
                writeDBSettings(self.plugin_dir,self.dictDB)
                
                # copy templates
                for assettype in ['customer','energy_plant','device']:
                    from_directory = """{}\\templates\\{}_assettypes""".format(self.plugin_dir,assettype)
                    print(from_directory)
                    to_directory = dir_data_center+"\\"+self.dictDB['projectName']+"\\"+assettype+"_assettypes"
                    print(to_directory)
                    #Path(to_directory).mkdir(parents=True, exist_ok=True)
                    #if os.path.exists(to_directory):
                    shutil.copytree(from_directory, to_directory)
                        
                    #replace plugins path
                    for dname, dirs, files in os.walk(to_directory):
                        for fname in files:
                            fpath = os.path.join(dname, fname)
                            with open(fpath) as f:
                                s = f.read()
                            s = s.replace("$plugins_path$", getQGISPluginsDir(self.plugin_dir).replace("\\","\\\\"))
                            with open(fpath, "w") as f:
                                f.write(s)         
                closeDialog(dlg)
          
    def importData(self, data, root=None):
        self.model.setRowCount(0)
        if root is None:
            root = self.model.invisibleRootItem()
        seen = {}   # List of  QStandardItem
        values = deque(data)
        while values:
            value = values.popleft()
            if value['parent_id'] == 0:
                parent = root
            else:
                pid = value['parent_id']
                if pid not in seen:
                    values.append(value)
                    continue
                parent = seen[pid]
            unique_id = value['unique_id']
            parent.appendRow([
                QStandardItem(value['name']),
                QStandardItem(value['description'])
            ])
            seen[unique_id] = parent.child(parent.rowCount() - 1)
            
    # Function to add right click menu to treeview item
    def openMenu(self, position):
        indexes = self.dlg.treeViewVersions.selectedIndexes()
        mdlIdx = self.dlg.treeViewVersions.indexAt(position)
        if not mdlIdx.isValid():
            return
        item = self.model.itemFromIndex(mdlIdx)
        if len(indexes) > 0:
            level = 0
            index = indexes[0]
            while index.parent().isValid():
                index = index.parent()
                level += 1
        else:
            level = 0
        right_click_menu = QMenu()
        act_add = right_click_menu.addAction(self.tr("Add Child version"))
        act_add.triggered.connect(partial(self.TreeItem_AddDialog, level, mdlIdx))
        act_add = right_click_menu.addAction(self.tr("Save version as"))
        act_add.triggered.connect(partial(self.TreeItem_SaveAsDialog, level, mdlIdx))
        act_add = right_click_menu.addAction(self.tr("Rename version"))
        act_add.triggered.connect(partial(self.TreeItem_RenameDialog, level, mdlIdx,item))
        act_del = right_click_menu.addAction(self.tr("Delete Item"))
        act_del.triggered.connect(partial(self.deleteVersionDialog, item))
        act_del = right_click_menu.addAction(self.tr("Load version"))
        act_del.triggered.connect(partial(self.TreeItem_Load, item, mdlIdx))
        right_click_menu.exec_(self.dlg.treeViewVersions.viewport().mapToGlobal(position))
        
    def TreeItem_AddDialog(self, level, mdlIdx):
        """Project version add dialog --> connects to the TreeItem_Add function, which does the adding"""
        print('Add dialog started')
        if self.conn != '':
            title='Add project version'
            label_text='Project version name:'
            self.dlg_addVersion = IDA_Districts_NameDialog(title,label_text,'','')
            self.dlg_addVersion.btn_ok.clicked.connect(lambda: self.TreeItem_Add(level,mdlIdx,self.dlg_addVersion))
            self.dlg_addVersion.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_addVersion))
            self.dlg_addVersion.show()               
        else:
            self.iface.messageBar().pushMessage("Error", "You are not connected to the DB!", level=Qgis.Critical)

    def TreeItem_SaveAsDialog(self, level, mdlIdx):
        """Project version Save As dialog --> connects to the TreeItem_SaveAs function, which does the Save As"""
        print('Save As dialog started')
        if self.conn != '':
            title='Save project version as'
            label_text='Project version name:'
            self.dlg_saveAsVersion = IDA_Districts_NameDialog(title,label_text,'','')
            self.dlg_saveAsVersion.btn_ok.clicked.connect(lambda: self.TreeItem_SaveAs(level,mdlIdx))
            self.dlg_saveAsVersion.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_saveAsVersion))
            self.dlg_saveAsVersion.show()               
        else:
            self.iface.messageBar().pushMessage("Error", "You are not connected to the DB!", level=Qgis.Critical)
         
    def TreeItem_Add(self, level, mdlIdx,dlg):
        """Function to add new project version and add child item to treeview"""
        versionName=dlg.input.text()
        description=dlg.input_description.text()
        if versionName:
            newVersionName=self.checkIfVersionIsNew(versionName)
            if newVersionName:
                #Creating version --> new schema in project        
                idBase=0
                item = self.model.itemFromIndex(mdlIdx)
                if item:
                    baseName=item.text()
                    sql="SELECT id FROM public.versionhandling WHERE name = '"+baseName+"';"
                    print(sql)
                    self.cur.execute(sql)
                    for base in self.cur.fetchall():
                        idBase = base['id']         
                sql = 'INSERT INTO public.versionhandling (name,id_base,description) VALUES (\''+versionName+'\','+str(idBase)+',\''+description+'\');'
                print(sql)
                self.cur.execute(sql)

                temp_key = QStandardItem(versionName)
                temp_value1 = QStandardItem('')
                self.model.itemFromIndex(mdlIdx).appendRow([temp_key, temp_value1])
                copy_schema(item.text(),versionName,self.dictDB,self.cur,self.plugin_dir)
                data=self.getVersionData()
                self.importData(data)
                self.dlg.treeViewVersions.expandAll()   
            else:
                self.iface.messageBar().pushMessage("Error", "Base version {} does already exist!".format(versionName), level=Qgis.Critical)
        else:
            self.iface.messageBar().pushMessage("Error", "Please enter a version name!", level=Qgis.Critical)

    def TreeItem_SaveAs(self, level, mdlIdx):
        """Function to save project version As and add base item to treeview"""
        versionName=self.dlg_saveAsVersion.input.text()
        description=self.dlg_saveAsVersion.input_description.text()
        if versionName:
            newVersionName=self.checkIfVersionIsNew(versionName)
            if newVersionName:
                #Creating version --> new schema in project        
                item = self.model.itemFromIndex(mdlIdx)

                sql = 'INSERT INTO public.versionhandling (name,id_base,description) VALUES (\''+versionName+'\',0,\''+description+'\');'
                print(sql)
                self.cur.execute(sql)

                temp_key = QStandardItem(versionName)
                temp_value1 = QStandardItem('')
                self.model.itemFromIndex(mdlIdx).appendRow([temp_key, temp_value1])
                copy_schema(item.text(),versionName,self.dictDB,self.cur,self.plugin_dir)
                data=self.getVersionData()
                self.importData(data)
                self.dlg.treeViewVersions.expandAll()   
            else:
                self.iface.messageBar().pushMessage("Error", "Base version {} does already exist!".format(versionName), level=Qgis.Critical)
        else:
            self.iface.messageBar().pushMessage("Error", "Please enter a version name!", level=Qgis.Critical)

    def getDescription(self,versionName):
        sql='SELECT description FROM public.versionhandling WHERE name=\''+versionName+'\';'
        self.cur.execute(sql)
        return self.cur.fetchone()['description']   
            
    def TreeItem_RenameDialog(self, level, mdlIdx,item):
        """Project version rename dialog --> connects to the TreeItem_Rename function, which does the renameing"""
        print('Rename dialog started')
        title='Rename version'
        label_text='New version name:'
        if self.conn != '':
            description=self.getDescription(item.text())
            self.dlg_renameVersion = IDA_Districts_NameDialog(title,label_text,item.text(),description)
            self.dlg_renameVersion.btn_ok.clicked.connect(lambda: self.TreeItem_Rename(level,mdlIdx))
            self.dlg_renameVersion.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_renameVersion))
            self.dlg_renameVersion.show()               
        else:
            self.iface.messageBar().pushMessage("Error", "You are not connected to the DB!", level=Qgis.Critical)
        
    def TreeItem_Rename(self,level,mdlIdx): 
        """ Renames a project version, if the version name does not exist and is not empty"""
        print('Rename')
        versionName=self.dlg_renameVersion.input.text()
        description=self.dlg_renameVersion.input_description.text()
        if versionName:
            newVersionName=self.checkIfVersionIsNew(versionName)
            item = self.model.itemFromIndex(mdlIdx)
            oldSchemaName=item.text()
            if newVersionName:
                print(oldSchemaName)
                newSchemaName=versionName
                print(newSchemaName)
                self.model.setData(mdlIdx, versionName)
                sql = 'ALTER SCHEMA '+oldSchemaName+' RENAME TO '+newSchemaName+';'
                print(sql)
                self.cur.execute(sql)
                sql = 'UPDATE public.versionhandling SET name= \''+newSchemaName+'\' WHERE name= \''+oldSchemaName+'\';'
                print(sql)
                self.cur.execute(sql)
            else:
                self.iface.messageBar().pushMessage("Error", "Version {} does already exist!".format(versionName), level=Qgis.Critical)
            sql = 'UPDATE public.versionhandling SET description = \''+description+'\' WHERE name= \''+versionName+'\';'
            print(sql)
            self.cur.execute(sql)
            data=self.getVersionData()
            self.importData(data)
            self.dlg.treeViewVersions.expandAll()          
        else:
            self.iface.messageBar().pushMessage("Error", "Please enter a version name!", level=Qgis.Critical)           
        
    def TreeItem_Delete(self, item,dlg):
        """Function to delete project version and removes it from the tree"""
        print(item)
        print(item.parent())
        try:
            sql = 'DROP SCHEMA '+item.text()+' CASCADE;'
            print(sql)
            self.cur.execute(sql)
        except:
            pass
        try:
            idBase=''
            sql="SELECT id FROM public.versionhandling WHERE name = '"+item.text()+"';"
            print(sql)
            self.cur.execute(sql)
            for base in self.cur.fetchall():
                print(base)
                print(base['id'])
                idBase = base['id']
            sql = 'UPDATE public.versionhandling SET id_base = 0 WHERE id_base ='+str(idBase)+';'
            print(sql)
            self.cur.execute(sql)         
            
            sql = 'DELETE FROM public.versionhandling WHERE name = \''+item.text()+'\';'
            print(sql)
            self.cur.execute(sql)
        except:
            pass
        
        if item.parent():
            item.parent().removeRow(item.row())
        else:
            self.model.removeRow(item.row())
            
        data=self.getVersionData()
        self.importData(data)
        self.dlg.treeViewVersions.expandAll() 
        closeDialog(dlg)
        
    def setTreeViewModel(self,data):
        self.model = QStandardItemModel()   
        self.model.setHorizontalHeaderLabels(['Version name', 'Description'])
        self.dlg.treeViewVersions.header().setDefaultSectionSize(180)
        self.dlg.treeViewVersions.setModel(self.model)
        self.importData(data)
        self.dlg.treeViewVersions.expandAll()
        self.dlg.treeViewVersions.setEditTriggers(QAbstractItemView.NoEditTriggers)
        
    def getVersionData(self):
        sql = 'SELECT id ,id_base ,name ,description FROM public.versionhandling;'
        self.cur.execute(sql)
        data=[]
        for version in self.cur.fetchall():
            data.append({'unique_id': version['id'], 'parent_id': version['id_base'], 'name': version['name'], 'description': version['description']})
        print(data)
        return data
        
    def loadSelectedProject(self):
        print('loadSelectedProject')    
        self.dictDB['projectName']=self.dlg.selectProject.currentText()
        self.conn=dbConnect(self.dictDB,True)
        if self.conn:
            self.cur = self.conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)    
            writeDBSettings(self.plugin_dir,self.dictDB)
            data=self.getVersionData()
            self.setTreeViewModel(data)
            
    def checkIfVersionIsNew(self,versionName):
        sql='SELECT schema_name FROM information_schema.schemata;'
        self.cur.execute(sql)
        newVersionName=True
        for schema in self.cur.fetchall():
            if schema['schema_name']==versionName:
                newVersionName=False   
        return newVersionName
                
    def addBaseVersion(self):
        """add new base version to DB if a version name is entered and version does not exists in DB"""
        self.dictDB['versionName']=self.dlg_addBase.input.text()
        description=self.dlg_addBase.input_description.text()
        print(self.dictDB['versionName'])
        if self.dictDB['versionName']:
            #check if version name exists
            newVersionName=self.checkIfVersionIsNew(self.dictDB['versionName'])
            print (newVersionName)        
            if newVersionName:
                writeDBSettings(self.plugin_dir,self.dictDB)
                #Creating version --> new schema in project      
                sql = 'CREATE SCHEMA IF NOT EXISTS "'+self.dictDB['versionName']+'";'
                print(sql)
                self.cur.execute(sql) 

                idBase=0
                sql = 'INSERT INTO public.versionhandling (name,id_base,description) VALUES (\''+self.dictDB['versionName']+'\','+str(idBase)+',\''+description+'\');'
                print(sql)
                self.cur.execute(sql) 
                
                #create tables in new schema
                filedata=""
                if os.path.exists(self.plugin_dir+"\\DB_versionTablesDefault.txt"):
                    with open(self.plugin_dir+"\\DB_versionTablesDefault.txt", "r") as myfile:
                        for line in myfile:
                            filedata=filedata+line
                    newdata = filedata.replace("$versionName$", self.dictDB['versionName'])
                    newdata = newdata.replace("$srid$", self.projectConfig['srid'])
                    newdata = newdata.replace("$plugins_path$", getQGISPluginsDir(self.plugin_dir))
                    
                    with open(self.plugin_dir+"\\DB_versionTables.txt",'w') as myfile:
                        myfile.write(newdata)     
                    self.cur.execute(newdata)
                    
                #insert data in new schema
                filedata=""
                if os.path.exists(self.plugin_dir+"\\DB_versionTablesDefault_data.txt"):
                    with open(self.plugin_dir+"\\DB_versionTablesDefault_data.txt", "r") as myfile:
                        for line in myfile:
                            filedata=filedata+line
                    newdata = filedata.replace("$versionName$", self.dictDB['versionName'])
                    newdata = newdata.replace("$plugins_path$", getQGISPluginsDir(self.plugin_dir))
                    
                    with open(self.plugin_dir+"\\DB_versionTables_data.txt",'w') as myfile:
                        myfile.write(newdata)     
                    self.cur.execute(newdata)
                
                data=self.getVersionData()
                self.importData(data)
                self.dlg.treeViewVersions.expandAll() 
            else:
                self.iface.messageBar().pushMessage("Error", "Base version {} does already exist!".format(self.dictDB['versionName']), level=Qgis.Critical)
        else:
            self.iface.messageBar().pushMessage("Error", "Please enter a version name!", level=Qgis.Critical)
    
    def closeBaseVersionDialog(self):
        print('close closeBaseVersionDialog')
        self.dlg_addBase.close()
    
    def addBaseVersionDialog(self):
        #Creating version --> new schema in project 
        if self.conn != '':
            title='Add base version'
            label_text='Add base version:'
            self.dlg_addBase = IDA_Districts_NameDialog(title,label_text,'','')
            self.dlg_addBase.btn_ok.clicked.connect(self.addBaseVersion)
            self.dlg_addBase.btn_cancel.clicked.connect(self.closeBaseVersionDialog)
            self.dlg_addBase.show()               
        else:
            self.iface.messageBar().pushMessage("Error", "You are not connected to the DB!", level=Qgis.Critical)

    def loadResultLayer(self,version,tableName,layerName,columnName,uri,layerTreeRoot):
        uri.setDataSource(version, tableName, "geom")
        vlayer = QgsVectorLayer(uri.uri(False), layerName, self.dictDB['user'])
        QgsProject.instance().addMapLayer(vlayer)
        categorized_symbol_renderer = vlayer.renderer()   
        self.cur.execute('SELECT max('+columnName+') FROM ' +version+'.'+tableName+';')
        max=self.cur.fetchone()['max']
        if max is None:
            max=0
        else:
            max=math.ceil(max)
        value=0
        graduatedClasses = 10       
        graduated_renderer = QgsGraduatedSymbolRenderer()        
        while value < max:
            min=value
            value=round(value+max/graduatedClasses,2)
            mySymbol=QgsSymbol.defaultSymbol(vlayer.geometryType())
            graduated_renderer.addClassRange(QgsRendererRange(QgsClassificationRange(str(min)+ ' - ' + str(value), min, value), mySymbol))            
        graduated_renderer.setClassificationMethod(QgsApplication.classificationMethodRegistry().method("EqualInterval"))
        myStyle = QgsStyle().defaultStyle()
        ramp = myStyle.colorRamp('Spectral')
        graduated_renderer.updateColorRamp(ramp)
        graduated_renderer.setClassAttribute(columnName)        
        vlayer.setRenderer(graduated_renderer)
        layerTreeRoot.findLayer(vlayer).setItemVisibilityChecked(False)
        vlayer.triggerRepaint() 
    
    def loadStructureLayers(self,version,uri):
        for tableName in ['structure_lines','structure_junctions']:
            uri.setDataSource(version, tableName, "")
            vlayer = QgsVectorLayer(uri.uri(False), tableName, self.dictDB['user'])
            QgsProject.instance().addMapLayer(vlayer)
            
    def saveIDADistrictsConfigSettings(self,dlg):
        """ save the config data to file configIDADistricts.txt"""
        print('saveIDADistrictsConfigSettings')
        configIDADistricts={}
        configIDADistricts['path_ice']=dlg.input[0].text()
        configIDADistricts['path_postgresql']=dlg.input[1].text()
        print(configIDADistricts)
        if writeIDADistrictsConfig(self.plugin_dir,configIDADistricts):
            dlg.close()
        
    def saveProjectConfigSettings(self,dlg):
        """ save project config data to file projectConfig.txt"""
        print('saveProjectConfigSettings')    
        srid_old=self.projectConfig['srid']        
        self.projectConfig['srid']=dlg.srid.text()

        if checkDBProjectConnected(self.dictDB,False):
            writeProjectConfig(self.plugin_dir,self.dictDB['projectName'],self.projectConfig)
            projectVersions=getProjectVersionNames(self.cur)
            
            if srid_old!=self.projectConfig['srid']:
                updateTableSrid(projectVersions,self.cur,self.projectConfig['srid'])
            if checkDBVersionConnected(self.dictDB,False) and srid_old!=self.projectConfig['srid']:
                loadVersionLayers(self.dictDB,self.cur,self.plugin_dir)
                
        dlg.close()
        
    def showIDADistrictsConfigData(self,dlg):
        """ Show the onfiguration data from file configIDADistricts.txt"""
        print('showConfigData')
        configIDADistricts=loadIDADistrictsConfig(self.plugin_dir)
        dlg.input[0].setText(configIDADistricts['path_ice'])
        dlg.input[1].setText(configIDADistricts['path_postgresql'])
        
    def showProjectConfigData(self,dlg):
        """ Show the onfiguration data from file configIDADistricts.txt"""
        print('showConfigData')
        if checkDBProjectConnected(self.dictDB,False):
            self.projectConfig=loadProjectConfig(self.plugin_dir,self.dictDB['projectName'])       
        print(self.projectConfig)
        dlg.srid.setText(self.projectConfig['srid'])  
    
    def setIDADistrictsConfig(self):
        """ open Dialog to set IDA Districts configuration data"""
        print("IDA Districts config dialog")
        title="IDA Districts Configuration Settings"
        inputs=[{'label':'IDA ICE path','text':'path_ice'},{'label':'PostgreSQL path','text':'path_postgresql'}]
        dlg = LabelTextOkCancelDialog(title,inputs)
        dlg.btn_ok.clicked.connect(lambda: self.saveIDADistrictsConfigSettings(dlg))
        dlg.btn_cancel.clicked.connect(lambda: closeDialog(dlg))
        self.showIDADistrictsConfigData(dlg)
        dlg.show()
        
    def setProjectConfig(self):
        """ open Dialog to set Project configuration data"""
        print("Project config dialog")
        dlg = ProjectConfigDialog()
        dlg.btn_ok.clicked.connect(lambda: self.saveProjectConfigSettings(dlg))
        dlg.btn_cancel.clicked.connect(lambda: closeDialog(dlg))
        self.showProjectConfigData(dlg)
        dlg.show()
        
    def importProject(self):
        """ import a project from a sql file and write the data center and modelling files to the folders"""
        print("import project")
        if self.cur_postgres:
            filename, _filter = QFileDialog.getOpenFileName(
                self.dlg, "Import IDA Districts project",'','*.ida')
            print(filename)
            filename=filename.replace('/','\\')

            if filename:
                self.worker_import = WorkerImportProject(filename=filename,dictDB=self.dictDB,plugin_dir=self.plugin_dir,cur=self.cur_postgres,dlg=self.dlg)
                self.worker_import.signals.progress.connect(self.dlg.update_progress)
                self.worker_import.signals.error.connect(self.dlg.show_error_message)      
                self.threadpool_import = QThreadPool()            
                self.threadpool_import.start(self.worker_import)    
        else:
            self.iface.messageBar().pushMessage("Error", "You are not connected to the DB!", level=Qgis.Critical)

        
    def showExportProject(self):
        if self.conn != '':
            self.dlg_export = ExportProjectDialog()
            self.dlg_export.btn_ok.clicked.connect(lambda: self.exportProject(self.dlg_export))
            self.dlg_export.btn_cancel.clicked.connect(lambda: closeDialog(self.dlg_export))
            self.dlg_export.show()               
        else:
            self.iface.messageBar().pushMessage("Error", "You are not connected to the DB!", level=Qgis.Critical)
    
    def exportProject(self,dlg):
        """Export the DB to a sql file and write the data center and modelling files to the folders + dDB description file --> zip"""
        print("Export project")
        filename=dlg.filename.text()
        filter_extensions=[]
        if not dlg.exportPrn.isChecked():
            filter_extensions.append('.prn')
        filter_folders=[]
        if not dlg.exportInvokedFeatures.isChecked():
            filter_folders.append('invoked_customers')
            filter_folders.append('invoked_energy_plants')
            filter_folders.append('invoked_devices')
        if not dlg.exportDBResults.isChecked():
            no_db_results=True
        else:
            no_db_results=False
        
        if filename and self.dictDB['projectName']:
            worker_export = WorkerExportProject(filename=filename,dictDB=self.dictDB,plugin_dir=self.plugin_dir,filter_extensions=filter_extensions,filter_folders=filter_folders,no_db_results=no_db_results)
            worker_export.signals.progress.connect(dlg.update_progress)
            worker_export.signals.error.connect(dlg.show_error_message)      
            self.threadpool_export = QThreadPool.globalInstance()            
            self.threadpool_export.start(worker_export)    
            
    def showDeleteVersionDialog(self):
        try:
            item=self.model.itemFromIndex(self.dlg.treeViewVersions.selectedIndexes()[0])
            self.deleteVersionDialog(item)
        except:
            self.iface.messageBar().pushMessage("Info", "No item selected!", level=Qgis.Info)
            print('No item selected!')
    
    def loadVersion(self):
        try:
            mdlIdx=self.dlg.treeViewVersions.selectedIndexes()[0]
            item=self.model.itemFromIndex(mdlIdx)
            self.TreeItem_Load(item, mdlIdx)
        except:
            self.iface.messageBar().pushMessage("Info", "No item selected!", level=Qgis.Info)
            print('No item selected!')

    def renameVersion(self):
        try:
            mdlIdx=self.dlg.treeViewVersions.selectedIndexes()[0]
            item=self.model.itemFromIndex(mdlIdx)
            level = 0
            index = mdlIdx
            while index.parent().isValid():
                index = index.parent()
                level += 1
            self.TreeItem_RenameDialog(level, mdlIdx,item)
        except:
            self.iface.messageBar().pushMessage("Info", "No item selected!", level=Qgis.Info)
            print('No item selected!')
        
        
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = IDA_Districts_ProjectHandlingDialog()
            self.dictDB={'pwd' : '' , 'host' : self.dlg.host.text(), 'port' :  self.dlg.port.text(), 'user' : '', 'projectName' : '', 'versionName' : ''}
            self.dlg.btn_createProject.clicked.connect(self.showCreateNewProject)
            self.dlg.btn_deleteProject.clicked.connect(self.deleteProjectDialog)
            self.dlg.btn_loadProject.clicked.connect(self.loadSelectedProject)
            self.dlg.btn_configProject.clicked.connect(self.setProjectConfig)
            self.dlg.btn_importProject.clicked.connect(self.importProject)
            self.dlg.btn_exportProject.clicked.connect(self.showExportProject)
            self.dlg.btn_addVersion.clicked.connect(self.addBaseVersionDialog)
            self.dlg.btn_loadVersion.clicked.connect(self.loadVersion)
            self.dlg.btn_deleteVersion.clicked.connect(self.showDeleteVersionDialog)
            self.dlg.btn_renameVersion.clicked.connect(self.renameVersion)
            self.dlg.btn_connect.clicked.connect(self.connectDB)
            self.dlg.btn_disconnect.clicked.connect(self.disconnectDB)
            self.dlg.btn_idaDistrictsConfig.clicked.connect(self.setIDADistrictsConfig)
            
            self.dlg.treeViewVersions.setContextMenuPolicy(Qt.CustomContextMenu)
            self.dlg.treeViewVersions.customContextMenuRequested.connect(self.openMenu)
            self.dlg.signals.close.connect(self.disconnectDB)
                      
            # show the dialog
            self.dlg.show()
        else:
            self.dlg.show()
            self.dlg.activateWindow()
            print('activate')

