# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IDA_Districts_ProjectHandling
                                 A QGIS plugin
 IDA Districts Project Handling
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-14
        copyright            : (C) 2021 by EQUA
        email                : peter.nageler@euqa.ch
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IDA_Districts_ProjectHandling class from file IDA_Districts_ProjectHandling.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ida_ph import IDA_Districts_ProjectHandling
    return IDA_Districts_ProjectHandling(iface)
